---
title: "FEAST OF THE TRANSFIGURATION OF THE LORD"
subtitle: "August 6"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "To Jesus Christ, Our Sovereign King"
          book: G
          priority: optional
        - name: "Love Divine, All Loves Excelling"
          book: G
          note: "*all verses*"
          priority: optional
    psalm:
      list:
        - name: "The Lord is king, the most high over all the earth."
          book: RA
          priority: required
    offertory:
      list:
        - name: "How Good, Lord, To Be Here!"
          book: G
          priority: required
    communion:
      list:
        - name: "Transform Us"
          book: G
          priority: required
    meditation:
      list:
        - name: "You, Lord, Are Both Lamb and Shepherd"
          noteL Year A
          book: G
          priority: required
        - name: "Tree of Life"
          note: "Year B (General and 4th Sunday verses)"
          book: G
          priority: preferred
        - name: "Behold the Lamb"
          note: Year C
          book: G
          priority: required
    recessional:
      list:
        - name: "Rejoice, the Lord is King"
          book: G
          priority: optional
        - name: "Change Our Hearts"
          book: G
          priority: optional
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

glory, hope, splendor, fulfillment of Old Testament

:::  {.red}
#### **Entrance Antiphon**
:::

> In a resplendent cloud the Holy Spirit appeared.  
> The Father’s voice was heard: This is my beloved Son,  
> with whom I am well pleased. Listen to him.

:::  {.red}
#### **Communion Antiphon**
:::

> When Christ appears, we shall be like him,  
for we shall see him as he is.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Daniel 7:9-10, 13-14]{style="float:right" .small}
:::

As I watched:  

Thrones were set up  
and the Ancient One took his throne.  
His clothing was bright as snow,  
and the hair on his head as white as wool;  
his throne was flames of fire,  
with wheels of burning fire.  
A surging stream of fire  
flowed out from where he sat;  
Thousands upon thousands were ministering to him,  
and myriads upon myriads attended him.  
The court was convened and the books were opened.  

As the visions during the night continued, I saw:  

One like a Son of man coming,  
on the clouds of heaven;  
When he reached the Ancient One  
and was presented before him,  
The one like a Son of man received dominion, glory, and kingship;  
all peoples, nations, and languages serve him.  
His dominion is an everlasting dominion  
that shall not be taken away,  
his kingship shall not be destroyed.  

***

::: {.red}
#### Responsorial Psalm [Psalm 97:1-2, 5-6, 9]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is king, the Most High over all the earth.**  

The LORD is king; let the earth rejoice;  
let the many islands be glad.  
Clouds and darkness are round about him,  
justice and judgment are the foundation of his throne. **[℟.]{.red}**  

The mountains melt like wax before the LORD,  
before the LORD of all the earth.  
The heavens proclaim his justice,  
and all peoples see his glory. **[℟.]{.red}**  

Because you, O LORD, are the Most High over all the earth,  
exalted far above all gods. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [2 Peter 1:16-19]{style="float:right" .small}
:::

Beloved:  
We did not follow cleverly devised myths  
when we made known to you  
the power and coming of our Lord Jesus Christ,  
but we had been eyewitnesses of his majesty.  
For he received honor and glory from God the Father  
when that unique declaration came to him from the majestic glory,  
“This is my Son, my beloved, with whom I am well pleased.”  
We ourselves heard this voice come from heaven  
while we were with him on the holy mountain.  
Moreover, we possess the prophetic message that is altogether reliable.  
You will do well to be attentive to it,  
as to a lamp shining in a dark place,  
until day dawns and the morning star rises in your hearts.  

***

::: {.red}
#### Gospel Acclamation [Matthew 17:5]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
This is my beloved Son, with whom I am well pleased;  
listen to him. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 17:1-9]{style="float:right" .small}
:::

Jesus took Peter, James, and his brother, John,  
and led them up a high mountain by themselves.  
And he was transfigured before them;  
his face shone like the sun  
and his clothes became white as light.  
And behold, Moses and Elijah appeared to them,  
conversing with him.  
Then Peter said to Jesus in reply,  
“Lord, it is good that we are here.  
If you wish, I will make three tents here,  
one for you, one for Moses, and one for Elijah.”  
While he was still speaking, behold,  
a bright cloud cast a shadow over them,  
then from the cloud came a voice that said,  
“This is my beloved Son, with whom I am well pleased;  
listen to him.”  
When the disciples heard this, they fell prostrate  
and were very much afraid.  
But Jesus came and touched them, saying,  
“Rise, and do not be afraid.”  
And when the disciples raised their eyes,  
they saw no one else but Jesus alone.  

As they were coming down from the mountain,  
Jesus charged them,  
“Do not tell the vision to anyone  
until the Son of Man has been raised from the dead.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
