---
title: "SOLEMNITY OF THE ASSUMPTION OF THE BLESSED VIRGIN MARY: MASS DURING THE DAY"
subtitle: "August 15"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Immaculate Mary"
          book: G
          priority: required
    psalm:
      list:
        - name: "The queen stands at your right hand, arrayed in gold."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Hail, Holy Queen, Enthroned Above"
          book: G
          priority: required
    communion:
      list:
        - name: "Luke 1:46-53: My Soul Gives Glory"
          book: G
          priority: required
    meditation:
      list:
        - name: "O Sanctissima"
          book: G
          priority: optional
        - name: "O Most Holy One"
          book: G
          priority: optional
    recessional:
      list:
        - name: "Sing of Mary"
          book: G
          priority: required
    anthems:
      list:
        - name: "Holy Is His Name"
          composer: Talbot
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

Mary's dignity, heavenly life, hope

:::  {.red}
#### **Entrance Antiphon**
:::

> A great sign appeared in heaven:  
> a woman clothed with the sun, and the moon beneath her feet,  
> and on her head a crown of twelve stars.  
>  
> [Or:]{.red}  
>  
> Let us all rejoice in the Lord,  
> as we celebrate the feast day in honor of the Virgin Mary,  
> at whose Assumption the Angels rejoice  
> and praise the Son of God.

:::  {.red}
#### **Communion Antiphon**
:::

> All generations will call me blessed,  
> for he who is mighty has done great things for me.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Revelation 11:19a; 12:1-6a, 10ab]{style="float:right" .small}
:::

God’s temple in heaven was opened,  
and the ark of his covenant could be seen in the temple.  

A great sign appeared in the sky, a woman clothed with the sun,  
with the moon under her feet,  
and on her head a crown of twelve stars.  
She was with child and wailed aloud in pain as she labored to give birth.  
Then another sign appeared in the sky;  
it was a huge red dragon, with seven heads and ten horns,  
and on its heads were seven diadems.  
Its tail swept away a third of the stars in the sky  
and hurled them down to the earth.  
Then the dragon stood before the woman about to give birth,  
to devour her child when she gave birth.  
She gave birth to a son, a male child,  
destined to rule all the nations with an iron rod.  
Her child was caught up to God and his throne.  
The woman herself fled into the desert  
where she had a place prepared by God.  

Then I heard a loud voice in heaven say:  
“Now have salvation and power come,  
and the Kingdom of our God  
and the authority of his Anointed One.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 45:10, 11, 12, 16]{style="float:right" .small}
:::

**[℟.]{.red}** **The queen stands at your right hand, arrayed in gold.**  

The queen takes her place at your right hand in gold of Ophir. **[℟.]{.red}**  

Hear, O daughter, and see; turn your ear,  
forget your people and your father’s house. **[℟.]{.red}**  

So shall the king desire your beauty;  
for he is your lord. **[℟.]{.red}**  

They are borne in with gladness and joy;  
they enter the palace of the king. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 15:20-27]{style="float:right" .small}
:::

Brothers and sisters:  
Christ has been raised from the dead,  
the firstfruits of those who have fallen asleep.  
For since death came through man,  
the resurrection of the dead came also through man.  
For just as in Adam all die,  
so too in Christ shall all be brought to life,  
but each one in proper order:  
Christ the firstfruits;  
then, at his coming, those who belong to Christ;  
then comes the end,  
when he hands over the Kingdom to his God and Father,  
when he has destroyed every sovereignty  
and every authority and power.  
For he must reign until he has put all his enemies under his feet.  
The last enemy to be destroyed is death,  
for “he subjected everything under his feet.”  

***

::: {.red}
#### Gospel Acclamation
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Mary is taken up to heaven;  
a chorus of angels exults. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 1:39-56]{style="float:right" .small}
:::

Mary set out  
and traveled to the hill country in haste  
to a town of Judah,  
where she entered the house of Zechariah  
and greeted Elizabeth.  
When Elizabeth heard Mary’s greeting,  
the infant leaped in her womb,  
and Elizabeth, filled with the Holy Spirit,  
cried out in a loud voice and said,  
“Blessed are you among women,  
and blessed is the fruit of your womb.  
And how does this happen to me,  
that the mother of my Lord should come to me?  
For at the moment the sound of your greeting reached my ears,  
the infant in my womb leaped for joy.  
Blessed are you who believed  
that what was spoken to you by the Lord  
would be fulfilled.”  

And Mary said:  
“My soul proclaims the greatness of the Lord;  
my spirit rejoices in God my Savior  
for he has looked with favor on his lowly servant.  
From this day all generations will call me blessed:  
the Almighty has done great things for me  
and holy is his Name.  
He has mercy on those who fear him  
in every generation.  
He has shown the strength of his arm,  
and has scattered the proud in their conceit.  
He has cast down the mighty from their thrones,  
and has lifted up the lowly.  
He has filled the hungry with good things,  
and the rich he has sent away empty.  
He has come to the help of his servant Israel  
for he has remembered his promise of mercy,  
the promise he made to our fathers,  
to Abraham and his children forever.”  

Mary remained with her about three months  
and then returned to her home.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* The music for the Mass During the Day is the same as for the [Vigil Mass](aug14-assumption-vigil.qmd), but the antiphons, readings, and Responsorial Psalm are diﬀerent.
* The **Gloria** is sung or recited. If sung, all Mass parts are taken from the Mass setting for the given year as specified in the [Ordinary Time
preamble](../ordinary-time/ot-summer.qmd).
