---
title: "THE MOST HOLY BODY AND BLOOD OF CHRIST (*CORPUS CHRISTI*)"
subtitle: "Second Sunday after Pentecost"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Praise to the Lord, the Almighty"
          book: G
          priority: required
    psalm:
      list:
        - name: "Praise the Lord, Jerusalem."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for *Corpus Christi*"
          book: "[Appx H](../appendices/H-corpus-christi-sequence.qmd)"
          priority: required
    offertory:
      list:
        - name: "One Bread, One Body"
          book: G
          priority: required
    communion:
      list:
        - name: "Shepherd of Souls"
          book: G
          priority: required
    meditation:
      list:
        - name: "Let All Mortal Flesh Keep Silence"
          book: G
          priority: required
    recessional:
      list:
        - name: "Holy God, We Praise Thy Name"
          book: G
          priority: required
    anthems:
      list:
        - name: "Lauda, Jerusalem"
  b:
    processional:
      list:
        - name: "At the Lamb's High Feast We Sing"
          book: G
          priority: required
    psalm:
      list:
        - name: "I will take the cup of salvation, and call on the name of the Lord."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for *Corpus Christi*"
          book: "[Appx H](../appendices/H-corpus-christi-sequence.qmd)"
          priority: required
    offertory:
      list:
        - name: "Alleluia! Sing to Jesus"
          book: G
          priority: required
    communion:
      list:
        - name: "Draw Near"
          book: G
          priority: required
    meditation:
      list:
        - name: "Hail Our Savior's Glorious Body"
          book: G
          priority: required
    recessional:
      list:
        - name: "Holy God, We Praise Thy Name"
          book: G
          priority: required
    anthems:
      list:
        - name: "Panis Angelicus"
          composer: Franck
  c:
    processional:
      list:
        - name: "Alleluia! Sing to Jesus"
          book: G
          priority: required
    psalm:
      list:
        - name: "You are a priest for ever, in the line of Melchizedek."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for *Corpus Christi*"
          book: "[Appx H](../appendices/H-corpus-christi-sequence.qmd)"
          priority: required
    offertory:
      list:
        - name: "Gift of Finest Wheat"
          book: G
          priority: required
    communion:
      list:
        - name: "Take and Eat"
          book: G
          priority: required
    meditation:
      list:
        - name: "I Come With Joy"
          book: G
          priority: required
    recessional:
      list:
        - name: "Holy God, We Praise Thy Name"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

Eucharist, love

:::  {.red}
#### **Entrance Antiphon**
:::

> He fed them with the finest wheat  
> and satisfied them with honey from the rock.

:::  {.red}
#### **Communion Antiphon**
:::

> Whoever eats my flesh and drinks my blood  
> remains in me and I in him, says the Lord.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Deuteronomy 8:2-3, 14b-16a]{style="float:right" .small}
:::

Moses said to the people:  
"Remember how for forty years now the LORD, your God,  
has directed all your journeying in the desert,  
so as to test you by affliction  
and find out whether or not it was your intention  
to keep his commandments.  
He therefore let you be afflicted with hunger,  
and then fed you with manna,  
a food unknown to you and your fathers,  
in order to show you that not by bread alone does one live,  
but by every word that comes forth from the mouth of the LORD.  

"Do not forget the LORD, your God,  
who brought you out of the land of Egypt,  
that place of slavery;  
who guided you through the vast and terrible desert  
with its saraph serpents and scorpions,  
its parched and waterless ground;  
who brought forth water for you from the flinty rock  
and fed you in the desert with manna,  
a food unknown to your fathers."  

***

::: {.red}
#### Responsorial Psalm [Psalm 147:12-13, 14-15, 19-20]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise the Lord, Jerusalem.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Glorify the LORD, O Jerusalem;  
praise your God, O Zion.  
For he has strengthened the bars of your gates;  
he has blessed your children within you. **[℟.]{.red}**  

He has granted peace in your borders;  
with the best of wheat he fills you.  
He sends forth his command to the earth;  
swiftly runs his word! **[℟.]{.red}**  

He has proclaimed his word to Jacob,  
his statutes and his ordinances to Israel.  
He has not done thus for any other nation;  
his ordinances he has not made known to them. Alleluia. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 10:16-17]{style="float:right" .small}
:::

Brothers and sisters:  
The cup of blessing that we bless,  
is it not a participation in the blood of Christ?  
The bread that we break,  
is it not a participation in the body of Christ?  
Because the loaf of bread is one,  
we, though many, are one body,  
for we all partake of the one loaf.  

***

::: {.red}
#### Sequence [*Lauda Sion*]{style="float:right" .small}
:::

Laud, O Zion, your salvation,  
Laud with hymns of exultation,  
Christ, your king and shepherd true:  

Bring him all the praise you know,  
He is more than you bestow.  
Never can you reach his due.  

Special theme for glad thanksgiving  
Is the quick'ning and the living  
Bread today before you set:  

From his hands of old partaken,  
As we know, by faith unshaken,  
Where the Twelve at supper met.  

Full and clear ring out your chanting,  
Joy nor sweetest grace be wanting,  
From your heart let praises burst:  

For today the feast is holden,  
When the institution olden  
Of that supper was rehearsed.  

Here the new law's new oblation,  
By the new king's revelation,  
Ends the form of ancient rite:  

Now the new the old effaces,  
Truth away the shadow chases,  
Light dispels the gloom of night.  

What he did at supper seated,  
Christ ordained to be repeated,  
His memorial ne'er to cease:  

And his rule for guidance taking,  
Bread and wine we hallow, making  
Thus our sacrifice of peace.  

This the truth each Christian learns,  
Bread into his flesh he turns,  
To his precious blood the wine:  

Sight has fail'd, nor thought conceives,  
But a dauntless faith believes,  
Resting on a pow'r divine.  

Here beneath these signs are hidden  
Priceless things to sense forbidden;  
Signs, not things are all we see:  

Blood is poured and flesh is broken,  
Yet in either wondrous token  
Christ entire we know to be.  

Whoso of this food partakes,  
Does not rend the Lord nor breaks;  
Christ is whole to all that taste:  

Thousands are, as one, receivers,  
One, as thousands of believers,  
Eats of him who cannot waste.  

Bad and good the feast are sharing,  
Of what divers dooms preparing,  
Endless death, or endless life.  

Life to these, to those damnation,  
See how like participation  
Is with unlike issues rife.  

When the sacrament is broken,  
Doubt not, but believe 'tis spoken,  
That each sever'd outward token  
doth the very whole contain.  

Nought the precious gift divides,  
Breaking but the sign betides  
Jesus still the same abides,  
still unbroken does remain.  

[The shorter form of the sequence begins here.]{.red}  

Lo! the angel's food is given  
To the pilgrim who has striven;  
see the children's bread from heaven,  
which on dogs may not be spent.  

Truth the ancient types fulfilling,  
Isaac bound, a victim willing,  
Paschal lamb, its lifeblood spilling,  
manna to the fathers sent.  

Very bread, good shepherd, tend us,  
Jesu, of your love befriend us,  
You refresh us, you defend us,  
Your eternal goodness send us  
In the land of life to see.  

You who all things can and know,  
Who on earth such food bestow,  
Grant us with your saints, though lowest,  
Where the heav'nly feast you show,  
Fellow heirs and guests to be. Amen. Alleluia.  

***

::: {.red}
#### Gospel Acclamation [John 6:51]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I am the living bread that came down from heaven, says the Lord;  
whoever eats this bread will live forever. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 6:51-58]{style="float:right" .small}
:::

Jesus said to the Jewish crowds:  
"I am the living bread that came down from heaven;  
whoever eats this bread will live forever;  
and the bread that I will give  
is my flesh for the life of the world."  

The Jews quarreled among themselves, saying,  
"How can this man give us his flesh to eat?"  
Jesus said to them,  
"Amen, amen, I say to you,  
unless you eat the flesh of the Son of Man and drink his blood,  
you do not have life within you.  
Whoever eats my flesh and drinks my blood  
has eternal life,  
and I will raise him on the last day.  
For my flesh is true food,  
and my blood is true drink.  
Whoever eats my flesh and drinks my blood  
remains in me and I in him.  
Just as the living Father sent me  
and I have life because of the Father,  
so also the one who feeds on me  
will have life because of me.  
This is the bread that came down from heaven.  
Unlike your ancestors who ate and still died,  
whoever eats this bread will live forever."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Exodus 24:3-8]{style="float:right" .small}
:::

When Moses came to the people  
and related all the words and ordinances of the LORD,  
they all answered with one voice,  
"We will do everything that the LORD has told us."  
Moses then wrote down all the words of the LORD and,  
rising early the next day,  
he erected at the foot of the mountain an altar  
and twelve pillars for the twelve tribes of Israel.  
Then, having sent certain young men of the Israelites  
to offer holocausts and sacrifice young bulls  
as peace offerings to the LORD,  
Moses took half of the blood and put it in large bowls;  
the other half he splashed on the altar.  
Taking the book of the covenant, he read it aloud to the people,  
who answered, "All that the LORD has said, we will heed and do."  
Then he took the blood and sprinkled it on the people, saying,  
"This is the blood of the covenant  
that the LORD has made with you  
in accordance with all these words of his."  

***

::: {.red}
#### Responsorial Psalm [Psalm 116:12-13, 15-16, 17-18]{style="float:right" .small}
:::

**[℟.]{.red}** **I will take the cup of salvation, and call on the name of the Lord.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

How shall I make a return to the LORD  
for all the good he has done for me?  
The cup of salvation I will take up,  
and I will call upon the name of the LORD. **[℟.]{.red}**  

Precious in the eyes of the LORD  
is the death of his faithful ones.  
I am your servant, the son of your handmaid;  
you have loosed my bonds. **[℟.]{.red}**  

To you will I offer sacrifice of thanksgiving,  
and I will call upon the name of the LORD.  
My vows to the LORD I will pay  
in the presence of all his people. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Hebrews 9:11-15]{style="float:right" .small}
:::

Brothers and sisters:  
When Christ came as high priest  
of the good things that have come to be,  
passing through the greater and more perfect tabernacle  
not made by hands, that is, not belonging to this creation,  
he entered once for all into the sanctuary,  
not with the blood of goats and calves  
but with his own blood, thus obtaining eternal redemption.  
For if the blood of goats and bulls  
and the sprinkling of a heifer's ashes  
can sanctify those who are defiled  
so that their flesh is cleansed,  
how much more will the blood of Christ,  
who through the eternal Spirit offered himself unblemished to God,  
cleanse our consciences from dead works  
to worship the living God.  

For this reason he is mediator of a new covenant:  
since a death has taken place for deliverance  
from transgressions under the first covenant,  
those who are called may receive the promised eternal inheritance.  

***

::: {.red}
#### Sequence [*Lauda Sion*]{style="float:right" .small}
:::

Laud, O Zion, your salvation,  
Laud with hymns of exultation,  
Christ, your king and shepherd true:  

Bring him all the praise you know,  
He is more than you bestow.  
Never can you reach his due.  

Special theme for glad thanksgiving  
Is the quick'ning and the living  
Bread today before you set:  

From his hands of old partaken,  
As we know, by faith unshaken,  
Where the Twelve at supper met.  

Full and clear ring out your chanting,  
Joy nor sweetest grace be wanting,  
From your heart let praises burst:  

For today the feast is holden,  
When the institution olden  
Of that supper was rehearsed.  

Here the new law's new oblation,  
By the new king's revelation,  
Ends the form of ancient rite:  

Now the new the old effaces,  
Truth away the shadow chases,  
Light dispels the gloom of night.  

What he did at supper seated,  
Christ ordained to be repeated,  
His memorial ne'er to cease:  

And his rule for guidance taking,  
Bread and wine we hallow, making  
Thus our sacrifice of peace.  

This the truth each Christian learns,  
Bread into his flesh he turns,  
To his precious blood the wine:  

Sight has fail'd, nor thought conceives,  
But a dauntless faith believes,  
Resting on a pow'r divine.  

Here beneath these signs are hidden  
Priceless things to sense forbidden;  
Signs, not things are all we see:  

Blood is poured and flesh is broken,  
Yet in either wondrous token  
Christ entire we know to be.  

Whoso of this food partakes,  
Does not rend the Lord nor breaks;  
Christ is whole to all that taste:  

Thousands are, as one, receivers,  
One, as thousands of believers,  
Eats of him who cannot waste.  

Bad and good the feast are sharing,  
Of what divers dooms preparing,  
Endless death, or endless life.  

Life to these, to those damnation,  
See how like participation  
Is with unlike issues rife.  

When the sacrament is broken,  
Doubt not, but believe 'tis spoken,  
That each sever'd outward token  
doth the very whole contain.  

Nought the precious gift divides,  
Breaking but the sign betides  
Jesus still the same abides,  
still unbroken does remain.  

[The shorter form of the sequence begins here.]{.red}  

Lo! the angel's food is given  
To the pilgrim who has striven;  
see the children's bread from heaven,  
which on dogs may not be spent.  

Truth the ancient types fulfilling,  
Isaac bound, a victim willing,  
Paschal lamb, its lifeblood spilling,  
manna to the fathers sent.  

Very bread, good shepherd, tend us,  
Jesu, of your love befriend us,  
You refresh us, you defend us,  
Your eternal goodness send us  
In the land of life to see.  

You who all things can and know,  
Who on earth such food bestow,  
Grant us with your saints, though lowest,  
Where the heav'nly feast you show,  
Fellow heirs and guests to be. Amen. Alleluia.  

***

::: {.red}
#### Gospel Acclamation [John 6:51]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I am the living bread that came down from heaven, says the Lord;  
whoever eats this bread will live forever. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 14:12-16, 22-26]{style="float:right" .small}
:::

On the first day of the Feast of Unleavened Bread,  
when they sacrificed the Passover lamb,  
Jesus’ disciples said to him,  
"Where do you want us to go  
and prepare for you to eat the Passover?"  
He sent two of his disciples and said to them,  
"Go into the city and a man will meet you,  
carrying a jar of water.  
Follow him.  
Wherever he enters, say to the master of the house,  
'The Teacher says, "Where is my guest room  
where I may eat the Passover with my disciples?"'  
Then he will show you a large upper room furnished and ready.  
Make the preparations for us there."  
The disciples then went off, entered the city,  
and found it just as he had told them;  
and they prepared the Passover.  

While they were eating,  
he took bread, said the blessing,  
broke it, gave it to them, and said,  
"Take it; this is my body."  
Then he took a cup, gave thanks, and gave it to them,  
and they all drank from it.  
He said to them,  
"This is my blood of the covenant,  
which will be shed for many.  
Amen, I say to you,  
I shall not drink again the fruit of the vine  
until the day when I drink it new in the kingdom of God."  
Then, after singing a hymn,  
they went out to the Mount of Olives.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Genesis 14:18-20]{style="float:right" .small}
:::

In those days, Melchizedek, king of Salem, brought out bread and wine,  
and being a priest of God Most High,  
he blessed Abram with these words:  
&emsp; "Blessed be Abram by God Most High,  
&emsp; &emsp; the creator of heaven and earth;  
&emsp; and blessed be God Most High,  
&emsp; &emsp; who delivered your foes into your hand."  
Then Abram gave him a tenth of everything.  

***

::: {.red}
#### Responsorial Psalm [Psalm 110:1, 2, 3, 4]{style="float:right" .small}
:::

**[℟.]{.red}** **You are a priest for ever, in the line of Melchizedek.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

The LORD said to my Lord: "Sit at my right hand  
&emsp; till I make your enemies your footstool." **[℟.]{.red}**  

The scepter of your power the LORD will stretch forth from Zion:  
&emsp; "Rule in the midst of your enemies." **[℟.]{.red}**  

"Yours is princely power in the day of your birth, in holy splendor;  
&emsp; before the daystar, like the dew, I have begotten you." **[℟.]{.red}**  

The LORD has sworn, and he will not repent:  
&emsp; "You are a priest forever, according to the order of  Melchizedek." **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 11:23-26]{style="float:right" .small}
:::

Brothers and sisters:  
I received from the Lord what I also handed on to you,  
that the Lord Jesus, on the night he was handed over,  
took bread, and, after he had given thanks,  
broke it and said, "This is my body that is for you.  
Do this in remembrance of me."  
In the same way also the cup, after supper, saying,  
"This cup is the new covenant in my blood.  
Do this, as often as you drink it, in remembrance of me."  
For as often as you eat this bread and drink the cup,  
you proclaim the death of the Lord until he comes.  

***

::: {.red}
#### Sequence [*Lauda Sion*]{style="float:right" .small}
:::

Laud, O Zion, your salvation,  
Laud with hymns of exultation,  
Christ, your king and shepherd true:  

Bring him all the praise you know,  
He is more than you bestow.  
Never can you reach his due.  

Special theme for glad thanksgiving  
Is the quick'ning and the living  
Bread today before you set:  

From his hands of old partaken,  
As we know, by faith unshaken,  
Where the Twelve at supper met.  

Full and clear ring out your chanting,  
Joy nor sweetest grace be wanting,  
From your heart let praises burst:  

For today the feast is holden,  
When the institution olden  
Of that supper was rehearsed.  

Here the new law's new oblation,  
By the new king's revelation,  
Ends the form of ancient rite:  

Now the new the old effaces,  
Truth away the shadow chases,  
Light dispels the gloom of night.  

What he did at supper seated,  
Christ ordained to be repeated,  
His memorial ne'er to cease:  

And his rule for guidance taking,  
Bread and wine we hallow, making  
Thus our sacrifice of peace.  

This the truth each Christian learns,  
Bread into his flesh he turns,  
To his precious blood the wine:  

Sight has fail'd, nor thought conceives,  
But a dauntless faith believes,  
Resting on a pow'r divine.  

Here beneath these signs are hidden  
Priceless things to sense forbidden;  
Signs, not things are all we see:  

Blood is poured and flesh is broken,  
Yet in either wondrous token  
Christ entire we know to be.  

Whoso of this food partakes,  
Does not rend the Lord nor breaks;  
Christ is whole to all that taste:  

Thousands are, as one, receivers,  
One, as thousands of believers,  
Eats of him who cannot waste.  

Bad and good the feast are sharing,  
Of what divers dooms preparing,  
Endless death, or endless life.  

Life to these, to those damnation,  
See how like participation  
Is with unlike issues rife.  

When the sacrament is broken,  
Doubt not, but believe 'tis spoken,  
That each sever'd outward token  
doth the very whole contain.  

Nought the precious gift divides,  
Breaking but the sign betides  
Jesus still the same abides,  
still unbroken does remain.  

[The shorter form of the sequence begins here.]{.red}  

Lo! the angel's food is given  
To the pilgrim who has striven;  
see the children's bread from heaven,  
which on dogs may not be spent.  

Truth the ancient types fulfilling,  
Isaac bound, a victim willing,  
Paschal lamb, its lifeblood spilling,  
manna to the fathers sent.  

Very bread, good shepherd, tend us,  
Jesu, of your love befriend us,  
You refresh us, you defend us,  
Your eternal goodness send us  
In the land of life to see.  

You who all things can and know,  
Who on earth such food bestow,  
Grant us with your saints, though lowest,  
Where the heav'nly feast you show,  
Fellow heirs and guests to be. Amen. Alleluia.  

***

::: {.red}
#### Gospel Acclamation [John 6:51]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I am the living bread that came down from heaven, says the Lord;  
whoever eats this bread will live forever. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [Luke 9:11b-17]{style="float:right" .small}
:::

Jesus spoke to the crowds about the kingdom of God,  
and he healed those who needed to be cured.  
As the day was drawing to a close,  
the Twelve approached him and said,  
"Dismiss the crowd  
so that they can go to the surrounding villages and farms  
and find lodging and provisions;  
for we are in a deserted place here."  
He said to them, "Give them some food yourselves."  
They replied, "Five loaves and two fish are all we have,  
unless we ourselves go and buy food for all these people."  
Now the men there numbered about five thousand.  
Then he said to his disciples,  
"Have them sit down in groups of about fifty."  
They did so and made them all sit down.  
Then taking the five loaves and the two fish,  
and looking up to heaven,  
he said the blessing over them, broke them,  
and gave them to the disciples to set before the crowd.  
They all ate and were satisfied.  
And when the leftover fragments were picked up,  
they filled twelve wicker baskets.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The optional **Sequence**, found in [Appendix H](../appendices/H-corpus-christi-sequence.qmd), is sung by the cantor only immediately after the Second Reading. Either the long or short version may be used at the discretion of the presider. Musicians must coordinate with the presider before Mass to determine if the Sequence is desired, and if so, whether the long or short version is preferred. Accompaniment should be soft and reverent, like Meditation hymns.
* If a Eucharist Procession takes place after Mass, “Lauda, Jerusalem”, as
found in [Appendix I](../appendices/I-lauda-jerusalem.qmd), can be sung, cycling through verses 1-4 as many times as needed and concluding with either verse 5 or 6 upon reaching the final destination, as in the recording.
* If Adoration of the Blessed Sacrament takes place during or after Mass,
the music is taken from [Appendix J](../appendices/J-adoration.qmd).