---
title: "SOLEMNITY OF THE IMMACULATE CONCEPTION OF THE BLESSED VIRGIN MARY"
subtitle: "December 8"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Immaculate Mary"
          book: "G"
          priority: required
    psalm:
      list:
        - name: "Sing to the Lord a new song, for he has done marvelous deeds."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Mary, First among Believers"
          book: G
          verses: "1,3, 5"
          priority: required
    communion:
      list:
        - name: "Luke 1:46-53: Magnificat"
          book: G
          priority: required
    meditation:
      list:
        - name: "Hail Mary, Gentle Woman"
          book: G
          priority: required
    recessional:
      list:
        - name: "I Sing a Maid"
          book: G
          verses: "1"
          priority: required
    anthems:
      list:
        - name: "Dixit Maria"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

Mary, purity, the benevolence of God

:::  {.red}
#### **Entrance Antiphon**
:::

> I rejoice heartily in the Lord,  
> in my God is the joy of my soul;  
> for he has clothed me with a robe of salvation,  
> and wrapped me in a mantle of justice,  
> like a bride adorned with her jewels

:::  {.red}
#### **Communion Antiphon**
:::

> Glorious things are spoken of you, O Mary,  
> for from you arose the sun of justice,  
> Christ our God.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Genesis 3:9-15, 20]{style="float:right" .small}
:::

After the man, Adam, had eaten of the tree,  
the LORD God called to the man and asked him, "Where are you?"  
He answered, "I heard you in the garden;  
but I was afraid, because I was naked,  
so I hid myself."  
Then he asked, "Who told you that you were naked?  
You have eaten, then,  
from the tree of which I had forbidden you to eat!"  
The man replied, "The woman whom you put here with me--  
she gave me fruit from the tree, and so I ate it."  
The LORD God then asked the woman,  
"Why did you do such a thing?"  
The woman answered, "The serpent tricked me into it, so I ate it."  

Then the LORD God said to the serpent:  
"Because you have done this, you shall be banned  
from all the animals  
and from all the wild creatures;  
on your belly shall you crawl,  
and dirt shall you eat  
all the days of your life.  
I will put enmity between you and the woman,  
and between your offspring and hers;  
he will strike at your head,  
while you strike at his heel."  

The man called his wife Eve,  
because she became the mother of all the living.  

***

::: {.red}
#### Responsorial Psalm [Psalm 98:1, 2-3ab, 3cd-4]{style="float:right" .small}
:::

**[℟.]{.red}** **Sing to the Lord a new song, for he has done marvelous deeds.**  

Sing to the LORD a new song,  
for he has done wondrous deeds;  
His right hand has won victory for him,  
his holy arm. **[℟.]{.red}**  

The LORD has made his salvation known:  
in the sight of the nations he has revealed his justice.  
He has remembered his kindness and his faithfulness  
toward the house of Israel. **[℟.]{.red}**  

All the ends of the earth have seen  
the salvation by our God.  
Sing joyfully to the LORD, all you lands;  
break into song; sing praise. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Ephesians 1:3-6, 11-12]{style="float:right" .small}
:::

Brothers and sisters:  
Blessed be the God and Father of our Lord Jesus Christ,  
who has blessed us in Christ  
with every spiritual blessing in the heavens,  
as he chose us in him, before the foundation of the world,  
to be holy and without blemish before him.  
In love he destined us for adoption to himself through Jesus Christ,  
in accord with the favor of his will,  
for the praise of the glory of his grace  
that he granted us in the beloved.  

In him we were also chosen,  
destined in accord with the purpose of the One  
who accomplishes all things according to the intention of his will,  
so that we might exist for the praise of his glory,  
we who first hoped in Christ.  

***

::: {.red}
#### Gospel Acclamation [See Luke 1:28]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Hail, Mary, full of grace, the Lord is with you;  
blessed are you among women. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 1:26-38]{style="float:right" .small}
:::

The angel Gabriel was sent from God  
to a town of Galilee called Nazareth,  
to a virgin betrothed to a man named Joseph,  
of the house of David,  
and the virgin's name was Mary.  
And coming to her, he said,  
"Hail, full of grace! The Lord is with you."  
But she was greatly troubled at what was said  
and pondered what sort of greeting this might be.  
Then the angel said to her,  
"Do not be afraid, Mary,  
for you have found favor with God.  
Behold, you will conceive in your womb and bear a son,  
and you shall name him Jesus.  
He will be great and will be called Son of the Most High,  
and the Lord God will give him the throne of David his father,  
and he will rule over the house of Jacob forever,  
and of his Kingdom there will be no end."  
But Mary said to the angel,  
"How can this be,  
since I have no relations with a man?"  
And the angel said to her in reply,  
"The Holy Spirit will come upon you,  
and the power of the Most High will overshadow you.  
Therefore the child to be born  
will be called holy, the Son of God.  
And behold, Elizabeth, your relative,  
has also conceived a son in her old age,  
and this is the sixth month for her who was called barren;  
for nothing will be impossible for God."  
Mary said, "Behold, I am the handmaid of the Lord.  
May it be done to me according to your word."  
Then the angel departed from her.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc-advent >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```

```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* The **Gloria** is sung or recited. If sung, all Mass parts are taken from the Mass setting for the given year as specified in the [Christmas season preamble](../christmas/christmas.qmd).
