---
title: "FEAST OF THE PRESENTATION OF THE LORD"
subtitle: "February 2"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "The King of Glory"
          book: G
          priority: optional
        - name: "All Glory, Laud, and Honor"
          book: G
          priority: optional
    psalm:
      list:
        - name: "Who is the king of glory? It is the Lord."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Luke 2:29-34: Nunc Dimittis"
          book: G
          priority: required
    communion:
      list:
        - name: "Behold the Lamb"
          book: G
          priority: required
    meditation:
      list:
        - name: "Now Let Your Servant Go in Peace"
          book: G
          priority: required
    recessional:
      list:
        - name: "Christ, Be Our Light"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

light, splendor, glory, meeting Christ

:::  {.red}
#### **Entrance Antiphon**
:::

> Your merciful love, O God,  
> we have received in the midst of your temple.  
> Your praise, O God, like your name,  
> reaches to the ends of the earth;  
> your right hand is filled with saving justice.

:::  {.red}
#### **Communion Antiphon**
:::

> My eyes have seen your salvation,  
> which you prepared in the sight of all peoples.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Malachi 3:1-4]{style="float:right" .small}
:::
  
&emsp; Thus says the Lord GOD:  
Lo, I am sending my messenger  
&emsp; to prepare the way before me;  
And suddenly there will come to the temple  
&emsp; the LORD whom you seek,  
And the messenger of the covenant whom you desire.  
&emsp; Yes, he is coming, says the LORD of hosts.  
But who will endure the day of his coming?  
&emsp; And who can stand when he appears?  
For he is like the refiner’s fire,  
&emsp; or like the fuller’s lye.  
He will sit refining and purifying silver,  
&emsp; and he will purify the sons of Levi,  
Refining them like gold or like silver  
&emsp; that they may offer due sacrifice to the LORD.  
Then the sacrifice of Judah and Jerusalem  
&emsp; will please the LORD,  
&emsp; as in the days of old, as in years gone by.

***

::: {.red}
#### Responsorial Psalm [Psalm 24:7, 8, 9, 10]{style="float:right" .small}
:::

**[℟.]{.red}** **Who is this king of glory?  It is the Lord!**  

Lift up, O gates, your lintels;  
&emsp; reach up, you ancient portals,  
&emsp; that the king of glory may come in! **[℟.]{.red}**  

Who is this king of glory?  
&emsp; The LORD, strong and mighty,  
&emsp; the LORD, mighty in battle. **[℟.]{.red}**  

Lift up, O gates, your lintels;  
&emsp; reach up, you ancient portals,  
&emsp; that the king of glory may come in! **[℟.]{.red}**  

Who is this king of glory?  
&emsp; The LORD of hosts; he is the king of glory. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Hebrews 2:14-18]{style="float:right" .small}
:::

Since the children share in blood and flesh,  
Jesus likewise shared in them,  
that through death he might destroy the one  
who has the power of death, that is, the Devil,  
and free those who through fear of death  
had been subject to slavery all their life.  
Surely he did not help angels  
but rather the descendants of Abraham;  
therefore, he had to become like his brothers and sisters  
in every way,  
that he might be a merciful and faithful high priest before God  
to expiate the sins of the people.  
Because he himself was tested through what he suffered,  
he is able to help those who are being tested.  

***

::: {.red}
#### Gospel Acclamation [Luke 2:32]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
A light of revelation to the Gentiles,  
and glory for your people Israel. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Luke 2:22-40 or 2:22-32]{style="float:right" .small}
:::

When the days were completed for their purification  
according to the law of Moses,  
Mary and Joseph took Jesus up to Jerusalem  
to present him to the Lord,  
just as it is written in the law of the Lord,  
*Every male that opens the womb shall be consecrated to the Lord,*  
and to offer the sacrifice of  
*a pair of turtledoves or two young pigeons,*  
in accordance with the dictate in the law of the Lord.  

Now there was a man in Jerusalem whose name was Simeon.  
This man was righteous and devout,  
awaiting the consolation of Israel,  
and the Holy Spirit was upon him.  
It had been revealed to him by the Holy Spirit  
that he should not see death  
before he had seen the Christ of the Lord.  
He came in the Spirit into the temple;  
and when the parents brought in the child Jesus  
to perform the custom of the law in regard to him,  
he took him into his arms and blessed God, saying:  

&emsp; “Now, Master, you may let your servant go  
&emsp; &emsp; in peace, according to your word,  
&emsp; for my eyes have seen your salvation,  
&emsp; &emsp; which you prepared in the sight of all the peoples:  
&emsp; a light for revelation to the Gentiles,  
&emsp; &emsp; and glory for your people Israel.”  

The child’s father and mother were amazed at what was said about him;  
and Simeon blessed them and said to Mary his mother,  
“Behold, this child is destined  
for the fall and rise of many in Israel,  
and to be a sign that will be contradicted  
--and you yourself a sword will pierce--  
so that the thoughts of many hearts may be revealed.”  
There was also a prophetess, Anna,  
the daughter of Phanuel, of the tribe of Asher.  
She was advanced in years,  
having lived seven years with her husband after her marriage,  
and then as a widow until she was eighty-four.  
She never left the temple,  
but worshiped night and day with fasting and prayer.  
And coming forward at that very time,  
she gave thanks to God and spoke about the child  
to all who were awaiting the redemption of Jerusalem.  

When they had fulfilled all the prescriptions  
of the law of the Lord,  
they returned to Galilee, to their own town of Nazareth.  
The child grew and became strong, filled with wisdom;  
and the favor of God was upon him.  

[Or:]{.red}

When the days were completed for their purification  
according to the law of Moses,  
Mary and Joseph took Jesus up to Jerusalem  
to present him to the Lord,  
just as it is written in the law of the Lord,  
*Every male that opens the womb shall be consecrated to the Lord,*. 
and to offer the sacrifice of  
*a pair of turtledoves or two young pigeons,*  
in accordance with the dictate in the law of the Lord.  

Now there was a man in Jerusalem whose name was Simeon.  
This man was righteous and devout,  
awaiting the consolation of Israel,  
and the Holy Spirit was upon him.  
It had been revealed to him by the Holy Spirit  
that he should not see death  
before he had seen the Christ of the Lord.  
He came in the Spirit into the temple;  
and when the parents brought in the child Jesus  
to perform the custom of the law in regard to him,  
he took him into his arms and blessed God, saying:  

&emsp; “Now, Master, you may let your servant go  
&emsp; &emsp; in peace, according to your word,  
&emsp; for my eyes have seen your salvation,  
&emsp; &emsp; which you prepared in the sight of all the peoples:  
&emsp; a light for revelation to the Gentiles,  
&emsp; &emsp; and glory for your people Israel.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```

```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
