---
title: "SOLEMNITY OF THE NATIVITY OF SAINT JOHN THE BAPTIST: MASS DURING THE DAY"
subtitle: "June 24"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "On Jordan's Bank"
          book: G
          priority: required
    psalm:
      list:
        - name: "I praise you for I am wonderfully made."
          book: RA
          priority: required
    offertory:
      list:
        - name: "In Christ There Is No East or West"
          book: G
          priority: optional
        - name: "Canticle of the Turning"
          book: G
          priority: optional
    communion:
      list:
        - name: "Behold the Lamb"
          book: G
          priority: required
    meditation:
      list:
        - name: "O God, You Search Me"
          book: G
          priority: required
    recessional:
      list:
        - name: "Ye Watchers and Ye Holy Ones"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

light, preparation, joy, repentance, Lamb of God

:::  {.red}
#### **Entrance Antiphon**
:::

> A man was sent from God, whose name was John.  
> He came to testify to the light,  
> to prepare a people fit for the Lord.

:::  {.red}
#### **Communion Antiphon**
:::

> Through the tender mercy of our God,  
> the Dawn from on high will visit us.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Isaiah 49:1-6]{style="float:right" .small}
:::

Hear me, O coastlands,  
&emsp; listen, O distant peoples.  
The LORD called me from birth,  
&emsp; from my mother’s womb he gave me my name.  
He made of me a sharp-edged sword  
&emsp; and concealed me in the shadow of his arm.  
He made me a polished arrow,  
&emsp; in his quiver he hid me.  
You are my servant, he said to me,  
&emsp; Israel, through whom I show my glory.  

Though I thought I had toiled in vain,  
&emsp; and for nothing, uselessly, spent my strength,  
yet my reward is with the LORD,  
&emsp; my recompense is with my God.  
For now the LORD has spoken  
&emsp; who formed me as his servant from the womb,  
that Jacob may be brought back to him  
&emsp; and Israel gathered to him;  
and I am made glorious in the sight of the LORD,  
&emsp; and my God is now my strength!  
It is too little, he says, for you to be my servant,  
&emsp; to raise up the tribes of Jacob,  
&emsp; and restore the survivors of Israel;  
I will make you a light to the nations,  
&emsp; that my salvation may reach to the ends of the earth.  

***

::: {.red}
#### Responsorial Psalm [Psalm 139:1b-3, 13-14ab, 14c-15]{style="float:right" .small}
:::

**[℟.]{.red}** **I praise you, for I am wonderfully made.**  

O LORD, you have probed me, you know me:  
&emsp; you know when I sit and when I stand;  
&emsp; you understand my thoughts from afar.  
My journeys and my rest you scrutinize,  
&emsp; with all my ways you are familiar. **[℟.]{.red}**  

Truly you have formed my inmost being;  
&emsp; you knit me in my mother’s womb.  
I give you thanks that I am fearfully, wonderfully made;  
&emsp; wonderful are your works. **[℟.]{.red}**  

My soul also you knew full well;  
&emsp; nor was my frame unknown to you  
When I was made in secret,  
&emsp; when I was fashioned in the depths of the earth. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Acts 13:22-26]{style="float:right" .small}
:::

In those days, Paul said:  
“God raised up David as king;  
of him God testified,  
*I have found David, son of Jesse, a man after my own heart;*  
*he will carry out my every wish.*  
From this man’s descendants God, according to his promise,  
has brought to Israel a savior, Jesus.  
John heralded his coming by proclaiming a baptism of repentance  
to all the people of Israel;  
and as John was completing his course, he would say,  
‘What do you suppose that I am? I am not he.  
Behold, one is coming after me;   
I am not worthy to unfasten the sandals of his feet.’  

“My brothers, sons of the family of Abraham,  
and those others among you who are God-fearing,  
to us this word of salvation has been sent.”  

***

::: {.red}
#### Gospel Acclamation [See Luke 1:76]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
You, child, will be called prophet of the Most High,  
for you will go before the Lord to prepare his way. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [Luke 1:57-66, 80]{style="float:right" .small}
:::

When the time arrived for Elizabeth to have her child  
she gave birth to a son.  
Her neighbors and relatives heard  
that the Lord had shown his great mercy toward her,  
and they rejoiced with her.  
When they came on the eighth day to circumcise the child,  
they were going to call him Zechariah after his father,  
but his mother said in reply,  
“No. He will be called John.”  
But they answered her,  
“There is no one among your relatives who has this name.”  
So they made signs, asking his father what he wished him to be called.  
He asked for a tablet and wrote, “John is his name,”  
and all were amazed.  
Immediately his mouth was opened, his tongue freed,  
and he spoke blessing God.  
Then fear came upon all their neighbors,  
and all these matters were discussed  
throughout the hill country of Judea.  
All who heard these things took them to heart, saying,  
“What, then, will this child be?”  
For surely the hand of the Lord was with him.  
The child grew and became strong in spirit,  
and he was in the desert until the day  
of his manifestation to Israel.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* *The first (generic) verse should be sung followed by the special verse for this feast.
* The music for the Mass During the Day is the same as for the [Vigil Mass](jun23-nativity-john-baptist-vigil.qmd), but the antiphons, readings, and Responsorial Psalm are diﬀerent.
* The **Gloria** is sung or recited. If sung, all Mass parts are taken from the Mass setting for the given year as specified in the [Ordinary Time
preamble](../ordinary-time/ot-summer.qmd).
