---
title: "SOLEMNITY OF SAINTS PETER AND PAUL, APOSTLES: MASS DURING THE DAY"
subtitle: "June 29"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "A Living Faith"
          book: G
          verse: "1, 4 (if needed)"
          priority: preferred
    psalm:
      list:
        - name: "The angel of the Lord will rescue those who fear him."
          book: RA
          priority: required
    offertory:
      list:
        - name: "The Summons"
          book: G
          priority: required
    communion:
      list:
        - name: "Only This I Want"
          book: G
          priority: optional
        - name: "Taste and See"
          book: G
          priority: optional
    meditation:
      list:
        - name: "The Love of the Lord"
          book: G
          priority: optional
        - name: "Heart of a Shepherd"
          book: G
          priority: optional
        - name: "Psalm 34: The Cry of the Poor"
          book: G
          priority: optional
    recessional:
      list:
        - name: "Canticle of the Sun"
          book: G
          priority: preferred
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

Peter, Paul, faith, evangelization, Church

:::  {.red}
#### **Entrance Antiphon**
:::

> These are the ones who, living in the flesh,  
> planted the Church with their blood;  
> they drank the chalice of the Lord  
> and became the friends of God.

:::  {.red}
#### **Communion Antiphon**
:::

> Peter said to Jesus: You are the Christ, the Son of the living God.  
> And Jesus replied: You are Peter,  
> and upon this rock I will build my Church.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Acts 12:1-11]{style="float:right" .small}
:::

In those days, King Herod laid hands upon some members of the Church to harm them.  
He had James, the brother of John, killed by the sword,  
and when he saw that this was pleasing to the Jews  
he proceeded to arrest Peter also.  
–It was the feast of Unleavened Bread.–  
He had him taken into custody and put in prison  
under the guard of four squads of four soldiers each.  
He intended to bring him before the people after Passover.  
Peter thus was being kept in prison,  
but prayer by the Church was fervently being made  
to God on his behalf.  

On the very night before Herod was to bring him to trial,  
Peter, secured by double chains,  
was sleeping between two soldiers,  
while outside the door guards kept watch on the prison.  
Suddenly the angel of the Lord stood by him  
and a light shone in the cell.  
He tapped Peter on the side and awakened him, saying,  
“Get up quickly.”  
The chains fell from his wrists.  
The angel said to him, “Put on your belt and your sandals.”  
He did so.  
Then he said to him, “Put on your cloak and follow me.”  
So he followed him out,  
not realizing that what was happening through the angel was real;  
he thought he was seeing a vision.  
They passed the first guard, then the second,  
and came to the iron gate leading out to the city,  
which opened for them by itself.  
They emerged and made their way down an alley,  
and suddenly the angel left him.  
Then Peter recovered his senses and said,  
&emsp; “Now I know for certain  
&emsp; that the Lord sent his angel  
&emsp; and rescued me from the hand of Herod  
&emsp; and from all that the Jewish people had been expecting.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 34:2-3, 4-5, 6-7, 8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **The angel of the Lord will rescue those who fear him.**  

I will bless the LORD at all times;  
&emsp; his praise shall be ever in my mouth.  
Let my soul glory in the LORD;  
&emsp; the lowly will hear me and be glad. **[℟.]{.red}**  

Glorify the LORD with me,  
&emsp; let us together extol his name.  
I sought the LORD, and he answered me  
&emsp; and delivered me from all my fears. **[℟.]{.red}**  

Look to him that you may be radiant with joy,  
&emsp; and your faces may not blush with shame.  
When the poor one called out, the LORD heard,  
&emsp; and from all his distress he saved him. **[℟.]{.red}**  

The angel of the LORD encamps  
&emsp; around those who fear him, and delivers them.  
Taste and see how good the LORD is;  
&emsp; blessed the man who takes refuge in him. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [2 Timothy 4:6-8, 17-18]{style="float:right" .small}
:::

I, Paul, am already being poured out like a libation,  
and the time of my departure is at hand.  
I have competed well; I have finished the race;  
I have kept the faith.  
From now on the crown of righteousness awaits me,  
which the Lord, the just judge,  
will award to me on that day, and not only to me,  
but to all who have longed for his appearance.  

The Lord stood by me and gave me strength,  
so that through me the proclamation might be completed  
and all the Gentiles might hear it.  
And I was rescued from the lion’s mouth.  
The Lord will rescue me from every evil threat  
and will bring me safe to his heavenly Kingdom.  
To him be glory forever and ever.  Amen.  

***

::: {.red}
#### Gospel Acclamation [Matthew 16:18]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
You are Peter and upon this rock I will build my Church,  
and the gates of the netherworld shall not prevail against it. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 16:13-19]{style="float:right" .small}
:::

When Jesus went into the region of Caesarea Philippi  
he asked his disciples,  
“Who do people say that the Son of Man is?”  
They replied, “Some say John the Baptist, others Elijah,  
still others Jeremiah or one of the prophets.”  
He said to them, “But who do you say that I am?”  
Simon Peter said in reply,  
“You are the Christ, the Son of the living God.”  
Jesus said to him in reply, “Blessed are you, Simon son of Jonah.  
For flesh and blood has not revealed this to you, but my heavenly Father.  
And so I say to you, you are Peter,  
and upon this rock I will build my Church,  
and the gates of the netherworld shall not prevail against it.  
I will give you the keys to the Kingdom of heaven.  
Whatever you bind on earth shall be bound in heaven;  
and whatever you loose on earth shall be loosed in heaven.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* *The first (generic) verse should be sung followed by the special verse for this solemnity.
* The music for the Mass During the Day is the same as for the [Vigil Mass](jun27-peter-paul-vigil.qmd), but the antiphons, readings, and Responsorial Psalm are diﬀerent.
* The **Gloria** is sung or recited. If sung, all Mass parts are taken from the Mass setting for the given year as specified in the [Ordinary Time
preamble](../ordinary-time/ot-summer.qmd).
