---
title: "SOLEMNITY OF SAINT JOSEPH, SPOUSE OF MARY"
subtitle: "March 19"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Mary, First among Believers"
          book: G
          priority: required
    psalm:
      list:
        - name: "The son of David will live forever."
          book: "[Appx C](../appendices/C-mar19-psalm.qmd)"
          priority: required
    offertory:
      list:
        - name: "Be Not Afraid"
          book: G
          priority: preferred
    communion:
      list:
        - name: "I Come with Joy"
          book: G
          priority: flexible
    meditation:
      list:
        - name: "The Aye Carol"
          book: G
          priority: preferred
    recessional:
      list:
        - name: "Faith of Our Fathers"
          verse: 1 only
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

fidelity, righteousness, stewardship

:::  {.red}
#### **Entrance Antiphon**
:::

> Behold, a faithful and prudent steward,  
> whom the Lord set over his household.

:::  {.red}
#### **Communion Antiphon**
:::

> Well done, good and faithful servant.  
> Come, share you master's joy.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [2 Samuel 7:4-5a, 12-14a, 16]{style="float:right" .small}
:::

The LORD spoke to Nathan and said:  
“Go, tell my servant David,  
‘When your time comes and you rest with your ancestors,  
I will raise up your heir after you, sprung from your loins,  
and I will make his kingdom firm.  
It is he who shall build a house for my name.  
And I will make his royal throne firm forever.  
I will be a father to him,  
and he shall be a son to me.  
Your house and your kingdom shall endure forever before me;  
your throne shall stand firm forever.’”  

***

::: {.red}
#### Responsorial Psalm [Psalm 89:2-3, 4-5, 27, 29]{style="float:right" .small}
:::

**[℟.]{.red}** **The son of David will live for ever.**  

The promises of the LORD I will sing forever;  
&emsp; through all generations my mouth shall proclaim your faithfulness,  
For you have said, “My kindness is established forever”;  
&emsp; in heaven you have confirmed your faithfulness. **[℟.]{.red}**  

“I have made a covenant with my chosen one,  
&emsp; I have sworn to David my servant:  
Forever will I confirm your posterity  
&emsp; and establish your throne for all generations.” **[℟.]{.red}**  

“He shall say of me, ‘You are my father  
&emsp; my God, the Rock, my savior.’  
Forever I will maintain my kindness toward him,  
&emsp; and my covenant with him stands firm.” **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Romans 4:13, 16-18, 22]{style="float:right" .small}
:::

Brothers and sisters:  
It was not through the law  
that the promise was made to Abraham and his descendants  
that he would inherit the world,  
but through the righteousness that comes from faith.  
For this reason, it depends on faith,  
so that it may be a gift,  
and the promise may be guaranteed to all his descendants,  
not to those who only adhere to the law. 
but to those who follow the faith of Abraham,  
who is the father of all of us, as it is written,  
*I have made you father of many nations.*  
He is our father in the sight of God,  
in whom he believed, who gives life to the dead  
and calls into being what does not exist.  
He believed, hoping against hope,  
that he would become *the father of many nations*,  
according to what was said, *Thus shall your descendants be.*  
That is why *it was credited to him as righteousness.*  

***

::: {.red}
#### Gospel Acclamation [Psalm 84:5]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
Blessed are those who dwell in your house, O Lord;  
they never cease to praise you. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Matthew 1:16, 18-21, 24a]{style="float:right" .small}
:::

Jacob was the father of Joseph, the husband of Mary.  
Of her was born Jesus who is called the Christ.  

Now this is how the birth of Jesus Christ came about.  
When his mother Mary was betrothed to Joseph,  
but before they lived together,  
she was found with child through the Holy Spirit.  
Joseph her husband, since he was a righteous man,  
yet unwilling to expose her to shame,  
decided to divorce her quietly.  
Such was his intention when, behold,  
the angel of the Lord appeared to him in a dream and said,  
“Joseph, son of David,  
do not be afraid to take Mary your wife into your home.  
For it is through the Holy Spirit  
that this child has been conceived in her.  
She will bear a son and you are to name him Jesus,  
because he will save his people from their sins.”  
When Joseph awoke,  
he did as the angel of the Lord had commanded him  
and took his wife into his home.  

[Or:]{.red} [Luke 2:41-51a]{style="float:right" .small .red}

Each year Jesus’ parents went to Jerusalem for the feast of Passover,  
and when he was twelve years old,  
they went up according to festival custom.  
After they had completed its days, as they were returning,  
the boy Jesus remained behind in Jerusalem,  
but his parents did not know it.  
Thinking that he was in the caravan,  
they journeyed for a day  
and looked for him among their relatives and acquaintances,  
but not finding him,  
they returned to Jerusalem to look for him.  
After three days they found him in the temple,  
sitting in the midst of the teachers,  
listening to them and asking them questions,  
and all who heard him were astounded  
at his understanding and his answers.  
When his parents saw him,  
they were astonished,  
and his mother said to him,  
“Son, why have you done this to us?  
Your father and I have been looking for you with great anxiety.”  
And he said to them,  
“Why were you looking for me?  
Did you not know that I must be in my Father’s house?”  
But they did not understand what he said to them.  
He went down with them and came to Nazareth,  
and was obedient to them.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* *The first (generic) verse should be sung followed by the special verse for this feast.
* The **Responsorial Psalm** is found in [Appendix C](../appendices/C-mar19-psalm.qmd).
* If this Solemnity falls within the season of Lent, the **Lenten Gospel Acclamation** in [Appendix C](../appendices/C-mar19-psalm.qmd) is sung.
* If this Solemnity *does not* fall within the season of Lent, the verse text in [Appendix C](../appendices/C-mar19-psalm.qmd) is sung with a familiar “Alleluia” refrain. In this case, if the verse accompaniment from [Appendix C](../appendices/C-mar19-psalm.qmd) is also used, either the chosen refrain should be in the same key as the verse (F major or D minor), or the verse should be transposed to the key signature of the chosen refrain.
