---
title: "SOLEMNITY OF THE ANNUNCIATION OF THE LORD"
subtitle: "March 25"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "I Sing a Maid"
          book: G
          priority: required
    psalm:
      list:
        - name: "Here I am, Lord; I come to do your will."
          book: RA
          priority: preferred
        - name: "Psalm 40: Here I Am"
          composer: Cooney
          book: G
          priority: optional
    offertory:
      list:
        - name: "Here I Am, Lord" 
          book: G
          priority: required
    communion:
      list:
        - name: "Hail Mary, Gentle Woman"
          book: G
          priority: required
    meditation:
      list:
        - name: "Sing of Mary"
          book: G
          priority: required
    recessional:
      list:
        - name: "Hail, Holy Queen"
          book: G
          priority: required
    anthems:
      list:
        - name: "Dixit Maria"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

faith, fidelity, Mary, trust

:::  {.red}
#### **Entrance Antiphon**
:::

> The Lord said, as he entered the world:  
> Behold, I come to do your will, O God.

:::  {.red}
#### **Communion Antiphon**
:::

> Behold, a Virgin shall conceive and bear a son;  
> and his name will be called Emmanuel.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Isaiah 7:10-14; 8:10]{style="float:right" .small}
:::

The LORD spoke to Ahaz, saying:  
Ask for a sign from the Lord, your God;  
let it be deep as the nether world, or high as the sky!  
But Ahaz answered,  
“I will not ask! I will not tempt the LORD!”  
Then Isaiah said:  
Listen, O house of David!  
Is it not enough for you to weary people,  
must you also weary my God?  
Therefore the Lord himself will give you this sign:  
the virgin shall be with child, and bear a son,  
and shall name him Emmanuel,  
which means “God is with us!”  

***

::: {.red}
#### Responsorial Psalm [Psalm 40:7-8a, 8b-9, 10, 11]{style="float:right" .small}
:::

**[℟.]{.red}** **Here I am, Lord; I come to do your will.**  

Sacrifice or oblation you wished not,  
&emsp; but ears open to obedience you gave me.  
Holocausts or sin-offerings you sought not;  
&emsp; then said I, “Behold I come.” **[℟.]{.red}**  

“In the written scroll it is prescribed for me,  
To do your will, O my God, is my delight,  
&emsp; and your law is within my heart!” **[℟.]{.red}**  

I announced your justice in the vast assembly;  
&emsp; I did not restrain my lips, as you, O LORD, know. **[℟.]{.red}**  

Your justice I kept not hid within my heart;  
&emsp; your faithfulness and your salvation I have spoken of;  
I have made no secret of your kindness and your truth  
&emsp; in the vast assembly. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Hebrews 10:4-10]{style="float:right" .small}
:::

Brothers and sisters:  
It is impossible that the blood of bulls and goats  
take away sins.  
For this reason, when Christ came into the world, he said:  

&emsp; “Sacrifice and offering you did not desire,  
&emsp; &emsp; but a body you prepared for me;  
&emsp; in holocausts and sin offerings you took no delight.  
&emsp; Then I said, ‘As is written of me in the scroll,  
&emsp; behold, I come to do your will, O God.’”  

First he says, “Sacrifices and offerings,  
holocausts and sin offerings,  
you neither desired nor delighted in.”  
These are offered according to the law.  
Then he says, “Behold, I come to do your will.”  
He takes away the first to establish the second.  
By this “will,” we have been consecrated  
through the offering of the Body of Jesus Christ once for all.  

***

::: {.red}
#### Gospel Acclamation [John 1:14ab]{style="float:right" .small}
:::

[If March 25 occurs after Easter:]{.red}  
**[℟.]{.red}** **Alleluia, Alleluia.**  

[Otherwise:]{.red}  
**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  

The Word of God became flesh and made his dwelling among us;  
and we saw his glory. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Luke 1:26-38]{style="float:right" .small}
:::

The angel Gabriel was sent from God  
to a town of Galilee called Nazareth,  
to a virgin betrothed to a man named Joseph,  
of the house of David,  
and the virgin’s name was Mary.  
And coming to her, he said,  
“Hail, full of grace! The Lord is with you.”  
But she was greatly troubled at what was said  
and pondered what sort of greeting this might be.  
Then the angel said to her,  
“Do not be afraid, Mary,  
for you have found favor with God.  
Behold, you will conceive in your womb and bear a son,  
and you shall name him Jesus.  
He will be great and will be called Son of the Most High,  
and the Lord God will give him the throne of David his father,  
and he will rule over the house of Jacob forever,  
and of his Kingdom there will be no end.”  
But Mary said to the angel,  
“How can this be,  
since I have no relations with a man?”  
And the angel said to her in reply,  
“The Holy Spirit will come upon you,  
and the power of the Most High will overshadow you.  
Therefore the child to be born  
will be called holy, the Son of God.  
And behold, Elizabeth, your relative,  
has also conceived a son in her old age,  
and this is the sixth month for her who was called barren;  
for nothing will be impossible for God.”  
Mary said, “Behold, I am the handmaid of the Lord.  
May it be done to me according to your word.”  
Then the angel departed from her.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* *The first (generic) verse should be sung followed by the special verse for this solemnity.
* The **Gloria** is sung or recited. If sung, all Mass parts are taken from the Mass setting for the given year as specified in the [Ordinary Time
preamble](../ordinary-time/ot-winter.qmd).
* If this solemnity falls within the season of Lent, the **Lenten Gospel
Acclamation** found in Appendix D is sung.
* If this Solemnity *does not* fall within the season of Lent, the verse text in Appendix D is sung with a familiar “Alleluia” refrain. In this case, if the verse accompaniment from Appendix D is also used, either the chosen refrain should be in the same key as the verse (F major or D minor), or the verse should be transposed to the key signature of the chosen refrain.
