---
title: "COMMEMORATION OF ALL THE FAITHFUL DEPARTED (ALL SOULS' DAY)"
subtitle: November 2
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "O God, Our Help in Ages Past"
          book: G
          priority: required
    psalm:
      list:
        - name: "The salvation of the just comes from the Lord."
          book: RA
          priority: preferred
        - name: "Psalm 103: The Lord is Kind and Merciful"
          composer: Cotter
          book: G
          priority: optional
        - name: "Psalm 103: The Lord is Kind and Merciful"
          composer: Haugen
          book: G
          priority: optional
    offertory:
      list:
        - name: "I Know that My Redeemer Lives"
          book: G
          priority: required
    communion:
      list:
        - name: "Shepherd of Souls"
          book: G
          priority: required
    meditation:
      list:
        - name: "Christ Before Us"
          book: BB
          note: "see note below"
          priority: optional
        - name: "Unless A Grain of Wheat"
          book: G
          note: "see note below"
          priority: optional
    recessional:
      list:
        - name: "We Shall Rise Again"
          book: G
          priority: required
    anthems:
      list:
        - name: "On the Wings of Change"
  b:
    processional:
      list:
        - name: "O God, Our Help in Ages Past"
          book: G
          priority: required
    psalm:
      list:
        - name: "The Lord is my shepherd; there is nothing I shall want."
          book: RA
          priority: optional
        - name: "Psalm 23: My Shepherd is the Lord"
          book: G
          priority: optional
        - name: "Though I walk in the valley of darkness, I fear no evil, for you are with me."
          book: RA
          priority: optional
    offertory:
      list:
        - name: "Dwellers in the Holy City"
          book: G
          priority: optional
        - name: "Come, You Faithful, Raise the Strain"
          book: G
          priority: optional
    communion:
      list:
        - name: "Keep in Mind"
          book: G
          priority: required
    meditation:
      list:
        - name: "Shepherd of Souls"
          book: G
          priority: required
    recessional:
      list:
        - name: "Sing with All the Saints in Glory"
          book: G
          priority: preferred
    anthems:
      list:
        - name: "The Trumpet Shall Sound"
          note: "from Handel's Messiah"
  c:
    processional:
      list:
        - name: "O God, Our Help in Ages Past"
          book: G
          priority: required
    psalm:
      list:
        - name: "The Lord is my light and my salvation."
          book: RA
          priority: optional
        - name: "I believe that I shall see the good things of the Lord in the land of the living."
          book: RA
          priority: optional
    offertory:
      list:
        - name: "O Breathe on Me, O Breath of God"
          book: G
          priority: optional
        - name: "How Firm a Foundation"
          book: G
          priority: optional
    communion:
      list:
        - name: "Shepherd of Souls"
          book: G
          priority: required
    meditation:
      list:
        - name: "I Am the Bread of Life"
          book: G
          priority: required
    recessional:
      list:
        - name: "We Shall Rise Again"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

communion of saints, prayer, resurrection, hope

:::  {.red}
#### **Entrance Antiphon**
:::

> [(1)]{.red} Just as Jesus died and has risen again,  
> so through Jesus God will bring with  
> him those who have fallen asleep;  
> and as in Adam all die, so also in Christ will all be brought to life.  
>  
> [Or:]{.red}  
> 
> [(2)]{.red} Eternal rest grant unto them, O Lord,  
> and let perpetual light shine upon them.  
>  
> [Or:]{.red}  
> 
> [(3)]{.red} God, who raised Jesus from the dead,  
> will give life also to your mortal bodies, through his Spirit that dwells in you.  

:::  {.red}
#### **Communion Antiphon**
:::

> [(1)]{.red} I am the Resurrection and the Life, says the Lord.  
> Whoever believes in me, even though he dies, will live,  
> and everyone who lives and believes in me will not die for ever.  
>  
> [Or:]{.red}  
> 
> [(2)]{.red} Let perpetual light shine upon them, O Lord,  
> with your Saints for ever, for you are merciful.  
>  
> [Or:]{.red}  
> 
> [(3)]{.red} We await a savior, the Lord Jesus Christ,  
> who will change our mortal bodies,  
> to conform with his glorified body.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>


::: {.red}
The following readings are suggestions. A more complete selection is found in the Masses for the Dead in the Weekday Lectionary.

The readings below have been divided into Years A, B, and C, for use when November 2 falls on a Sunday.
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Wisdom 3:1-9]{style="float:right" .small}
:::

The souls of the just are in the hand of God,  
&emsp; and no torment shall touch them.  
They seemed, in the view of the foolish, to be dead;  
&emsp; and their passing away was thought an affliction  
&emsp; and their going forth from us, utter destruction.  
But they are in peace.  
For if before men, indeed, they be punished,  
&emsp; yet is their hope full of immortality;  
chastised a little, they shall be greatly blessed,  
&emsp; because God tried them  
&emsp; and found them worthy of himself.  
As gold in the furnace, he proved them,  
&emsp; and as sacrificial offerings he took them to himself.  
In the time of their visitation they shall shine,  
&emsp; and shall dart about as sparks through stubble;  
they shall judge nations and rule over peoples,  
&emsp; and the Lord shall be their King forever.  
Those who trust in him shall understand truth,  
&emsp; and the faithful shall abide with him in love:  
because grace and mercy are with his holy ones,  
&emsp; and his care is with his elect.  

***

::: {.red}
#### Responsorial Psalm [Psalm 23:1-3a, 3b-4, 5, 6]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is my shepherd; there is nothing I shall want.**  
[Or:]{.red}  
**[℟.]{.red}** **Though I walk in the valley of darkness, I fear no evil, for you are with me.**  

The LORD is my shepherd; I shall not want.  
&emsp; In verdant pastures he gives me repose;  
beside restful waters he leads me;  
&emsp; he refreshes my soul. **[℟.]{.red}**  

He guides me in right paths  
&emsp; for his name’s sake.  
Even though I walk in the dark valley  
&emsp; I fear no evil; for you are at my side  
with your rod and your staff  
&emsp; that give me courage. **[℟.]{.red}**  

You spread the table before me  
&emsp; in the sight of my foes;  
You anoint my head with oil;  
&emsp; my cup overflows. **[℟.]{.red}**  

Only goodness and kindness follow me  
&emsp; all the days of my life;  
and I shall dwell in the house of the LORD  
&emsp; for years to come. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Romans 5:5-11]{style="float:right" .small}
:::

Brothers and sisters:  
Hope does not disappoint,  
because the love of God has been poured out into our hearts  
through the Holy Spirit who has been given to us.  
For Christ, while we were still helpless,  
died at the appointed time for the ungodly.  
Indeed, only with difficulty does one die for a just person,  
though perhaps for a good person  
one might even find courage to die.  
But God proves his love for us  
in that while we were still sinners Christ died for us.  
How much more then, since we are now justified by his Blood,  
will we be saved through him from the wrath.  
Indeed, if, while we were enemies,  
we were reconciled to God through the death of his Son,  
how much more, once reconciled,  
will we be saved by his life.  
Not only that,  
but we also boast of God through our Lord Jesus Christ,  
through whom we have now received reconciliation.  

[Or:]{.red} [Romans 6:3-9]{style="float:right" .small .red}

Brothers and sisters:  
Are you unaware that we who were baptized into Christ Jesus  
were baptized into his death?  
We were indeed buried with him through baptism into death,  
so that, just as Christ was raised from the dead  
by the glory of the Father,  
we too might live in newness of life.  

For if we have grown into union with him through a death like his,  
we shall also be united with him in the resurrection.  
We know that our old self was crucified with him,  
so that our sinful body might be done away with,  
that we might no longer be in slavery to sin.  
For a dead person has been absolved from sin.  
If, then, we have died with Christ,  
we believe that we shall also live with him.  
We know that Christ, raised from the dead, dies no more;  
death no longer has power over him.  

***

::: {.red}
#### Gospel Acclamation [Matthew 25:34]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Come, you who are blessed by my Father;  
inherit the Kingdom prepared for you from the foundation of the world. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 6:37-40]{style="float:right" .small}
:::

Jesus said to the crowds:  
“Everything that the Father gives me will come to me,  
and I will not reject anyone who comes to me,  
because I came down from heaven not to do my own will  
but the will of the one who sent me.  
And this is the will of the one who sent me,  
that I should not lose anything of what he gave me,  
but that I should raise it on the last day.  
For this is the will of my Father,  
that everyone who sees the Son and believes in him  
may have eternal life,  
and I shall raise him on the last day.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.red}
The readings below have been divided into Years A, B, and C, for
use when November 2 falls on a Sunday.  
:::

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Lamentations 3:17-26]{style="float:right" .small}
:::

My soul is deprived of peace;  
I have forgotten what happiness is;  
so I say, “Gone is my glory,  
and all that I had hoped for from the Lord.”  

The thought of my affliction and my homelessness  
is wormwood and gall!  
My soul continually thinks of it  
and is bowed down within me.  

But this I call to mind and therefore I have hope:  
The steadfast love of the Lord never ceases,  
his mercies never come to an end;  
they are new every morning;  
great is your faithfulness.  
“The Lord is my portion,” says my soul,  
“therefore I will hope in him.”  

The Lord is good to those who wait for him,  
to the soul that seeks him.  
It is good that one should wait quietly  
for the salvation of the Lord.  

***

::: {.red}
#### Responsorial Psalm [Psalm 103:8, 10, 13-14, 15-16, 17]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is kind and merciful.**  
[Or:]{.red}  
**[℟.]{.red}** **The salvation of the just comes from the Lord.**  

The Lord is merciful and gracious,  
slow to anger and abounding in steadfast love.  
He does not deal with us according to our sins,  
nor repay us according to our iniquities. **[℟.]{.red}**  

As a father has compassion for his children,  
so the Lord has compassion for those who fear him.  
For he knows how we were made;  
he remembers that we are dust. **[℟.]{.red}**  

As for mortals, their days are like grass;  
they flourish like a flower of the field;  
for the wind passes over it, and it is gone,  
and its place knows it no more. **[℟.]{.red}**  

The steadfast love of the Lord  
is from everlasting to everlasting  
on those who fear him,  
and his righteousness to children’s children,  
to those who keep his covenant  
and remember to do his commandments. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 15:51-57]{style="float:right" .small}
:::

Brothers and sisters,  
listen, I will tell you a mystery!  
We will not all die,  
but we will all be changed,  
in a moment, in the twinkling of an eye, at the last trumpet.  
For the trumpet will sound,  
and the dead will be raised imperishable,  
and we will be changed.  
For this perishable body must put on imperishability,  
and this mortal body must put on immortality.  

When this perishable body puts on imperishability,  
and this mortal body puts on immortality,  
then the saying that is written will be fulfilled:  
“Death has been swallowed up in victory.”  
“Where, O death, is your victory?  
Where, O death, is your sting?”  

The sting of death is sin,  
and the power of sin is the law.  
But thanks be to God,  
who gives us the victory through our Lord Jesus Christ.  

***

::: {.red}
#### Gospel Acclamation [2 Timothy 2:11-12a]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
If we die with Christ, we shall live with him;  
and if we are faithful to the end, we shall reign with him. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 11:25-30]{style="float:right" .small}
:::

At that time Jesus said,  
“I thank you, Father, Lord of heaven and earth,  
because you have hidden these things from the wise and the intelligent  
and have revealed them to infants;  
yes, Father, for such was your gracious will.”  

Then turning to his disciples, Jesus said:  
“All things have been handed over to me by my Father;  
and no one knows the Son except the Father,  
and no one knows the Father except the Son  
and anyone to whom the Son chooses to reveal him.  

“Come to me,  
all you that are weary and are carrying heavy burdens,  
and I will give you rest.  
Take my yoke upon you, and learn from me;  
for I am gentle and humble in heart,  
and you will find rest for your souls.  

For my yoke is easy, and my burden is light.”  

[Or:]{.red} [John 12:23-26]{style="float:right" .small .red}

Jesus said to his disciples,  
“The hour has come for the Son of Man to be glorified.  
Very truly, I tell you,  
unless a grain of wheat falls into the earth and dies,  
it remains just a single grain;  
but if it dies, it bears much fruit.  

“Those who love their life lose it,  
and those who hate their life in this world  
will keep it for eternal life.  

”Whoever serves me must follow me,  
and where I am, there will my servant be also.  
Whoever serves me, the Father will honor.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Isaiah 25:6-9]{style="float:right" .small}
:::

On this mountain the Lord of hosts will make for all peoples  
a feast of rich food, a feast of well-aged wines,  
of rich food filled with marrow,  
of well-aged wines strained clear.  
The Lord God will destroy on this mountain  
the shroud that is cast over all peoples,  
the sheet that is spread over all nations;  
he will swallow up death forever.  

Then the Lord God will wipe away the tears from all faces,  
and the disgrace of his people  
he will take away from all the earth,  
for the Lord has spoken.  

It will be said on that day,  
“Lo, this is our God;  
we have waited for him,  
so that he might save us.  
This is the Lord for whom we have waited;  
let us be glad and rejoice in his salvation.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 23:1-3a, 3b-4, 5, 6]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is my shepherd; there is nothing I shall want.**  
[Or:]{.red}  
**[℟.]{.red}** **Though I walk in the valley of darkness, I fear no evil, for you are with me.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

The Lord is my shepherd, I shall not want.  
He makes me lie down in green pastures;  
he leads me beside still waters;  
he restores my soul. **[℟.]{.red}**  

He leads me in right paths for his name’s sake.  
Even though I walk through the darkest valley, I fear no evil;  
for you are with me;  
your rod and your staff—they comfort me. **[℟.]{.red}**  

You prepare a table before me  
in the presence of my enemies;  
you anoint my head with oil;  
my cup overflows. **[℟.]{.red}**  

Surely goodness and mercy shall follow me  
all the days of my life,  
and I shall dwell in the house of the Lord  
my whole life long. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 15:12-26]{style="float:right" .small}
:::

Beloved,  
if Christ is proclaimed as raised from the dead,  
how can some of you say there is no resurrection of the dead?  
If there is no resurrection of the dead,  
then Christ has not been raised;  
and if Christ has not been raised,  
then our proclamation has been in vain. 
and your faith has been in vain.  

We are even found to be misrepresenting God,  
because we testified of God that he raised Christ—  
whom he did not raise if it is true that the dead are not raised.  
For if the dead are not raised,  
then Christ has not been raised.  

If Christ has not been raised,  
your faith is futile and you are still in your sins.  
Then those also who have died in Christ have perished.  

If for this life only we have hoped in Christ,  
we are of all people most to be pitied.  

But in fact Christ has been raised from the dead,  
the first fruits of those who have died.  
For since death came through a human being,  
the resurrection of the dead has also come through a human being;  
for as all die in Adam,  
so all will be made alive in Christ.  
But each in his own order:  
Christ the first fruits,  
then at his coming, those who belong to Christ.  

Then comes the end,  
when he hands over the kingdom to God the Father,  
after Christ has destroyed every ruler and every authority and power.  
For he must reign until he has put all his enemies under his feet.  
The last enemy to be destroyed is death.  

***

::: {.red}
#### Gospel Acclamation [Matthew 25:34]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Come, you whom my Father has blessed, says the Lord;  
inherit the kingdom prepared for you since the foundation of the world. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 8:27-35]{style="float:right" .small}
:::

Jesus went on with his disciples to the villages of Caesarea Philippi;  
and on the way he asked his disciples,  
“Who do people say that I am?”  
And they answered him,  
“John the Baptist; and others, Elijah;  
and still others, one of the prophets.”  

Jesus asked them,  
“But who do you say that I am?”  

Peter answered him,  
“You are the Messiah.”  
And Jesus sternly ordered them not to tell anyone about him.  

Then he began to teach them  
that the Son of Man must undergo great suffering,  
and be rejected by the elders, the chief priests, and the scribes,  
and be killed,  
and after three days rise again.  

He said all this quite openly.  
And Peter took him aside and began to rebuke him.  
But turning and looking at his disciples,  
Jesus rebuked Peter and said,  
“Get behind me, Satan!  
For you are setting your mind not on divine things  
but on human things.”  

Jesus called the crowd with his disciples, and said to them,  
“If any want to become my followers,  
let them deny themselves and take up their cross and follow me.  
For those who want to save their life will lose it,  
and those who lose their life for my sake,  
and for the sake of the gospel, will save it.”  

[Or:]{.red} [John 1:1-5, 9-14]{style="float:right" .small .red}

In the beginning was the Word,  
and the Word was with God,  
and the Word was God.  
He was in the beginning with God.  
All things came into being through him,  
and without him not one thing came into being.  
What has come into being in him was life,  
and the life was the light of all people.  
The light shines in the darkness,  
and the darkness did not overcome it.  

The true light, which enlightens everyone,  
was coming into the world.  
He was in the world,  
and the world came into being through him;  
yet the world did not know him.  

He came to what was his own,  
and his own people did not accept him.  
But to all who received him,  
who believed in his name,  
he gave power to become children of God,  
who were born, not of blood  
or of the will of the flesh  
or of the will of man,  
but of God.  

And the Word became flesh and lived among us,  
and we have seen his glory,  
the glory as of a father’s only son,  
full of grace and truth.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Ezekiel 37:1, 4-6, 12-14]{style="float:right" .small}
:::

The hand of the Lord came upon me,  
and he brought me out by the spirit of the Lord  
and set me down in the middle of a valley;  
it was full of bones.  

Then he said to me,  
“Prophesy to these bones, and say to them:  
‘O dry bones, hear the word of the Lord.’  

Thus says the Lord God to these bones:  
‘I will cause breath to enter you, and you shall live.  

I will lay sinews on you,  
and will cause flesh to come upon you,  
and cover you with skin, and put breath in you,  
and you shall live;  
and you shall know that I am the Lord.’  

“Therefore prophesy, and say to them,  
‘Thus says the Lord God:  
I am going to open your graves,  
and bring you up from your graves, O my people;  
and I will bring you back to the land of Israel.  

‘And you shall know that I am the Lord,  
when I open your graves,  
and bring you up from your graves, O my people.  

‘I will put my spirit within you, and you shall live,  
and I will place you on your own soil;  
then you shall know that I, the Lord,  
have spoken and will act,’” says the Lord.  

***

::: {.red}
#### Responsorial Psalm [Psalm 27:1, 4, 13-14]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is my light and my salvation.**  
[Or:]{.red}  
**[℟.]{.red}** **I believe that I shall see the good things of the Lord in the land of the living.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

The Lord is my light and my salvation;  
whom shall I fear?  
The Lord is the stronghold of my life;  
of whom shall I be afraid? **[℟.]{.red}**  

One thing I asked of the Lord, that will I seek:  
to live in the house of the Lord all the days of my life,  
to behold the beauty of the Lord,  
and to inquire in his temple. **[℟.]{.red}**  

I believe that I shall see the goodness of the Lord  
in the land of the living.  
Wait for the Lord; be strong,  
and let your heart take courage; wait for the Lord! **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Peter 1:3-9]{style="float:right" .small}
:::

Blessed be the God and Father of our Lord Jesus Christ!  
By his great mercy he has given us a new birth into a living hope  
through the resurrection of Jesus Christ from the dead;  
a birth into an inheritance  
that is imperishable, undefiled, and unfading,  
kept in heaven for you,  
who are being protected by the power of God through faith  
for a salvation ready to be revealed in the last time.  

In this you rejoice,  
even if now for a little while  
you have had to suffer various trials,  
so that the genuineness of your faith—  
being more precious than gold that,  
though perishable, is tested by fire—  
may be found to result in praise and glory and honor  
when Jesus Christ is revealed.  

Although you have not seen him, you love him;  
and even though you do not see him now, you believe in him  
and rejoice with an indescribable and glorious joy,  
or you are receiving the outcome of your faith,  
the salvation of your souls.  

***

::: {.red}
#### Gospel Acclamation [Revelation 1:5-6]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Jesus Christ is the firstborn of the dead;  
glory and kingship be his for ever and ever. Amen. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 7:11-17]{style="float:right" .small}
:::

Jesus went to a town called Nain,  
and his disciples and a large crowd went with him.  
As he approached the gate of the town,  
a man who had died was being carried out.  
He was his mother’s only son,  
and she was a widow;  
and with her was a large crowd from the town.  

When the Lord saw her,  
he had compassion for her and said to her,  
“Do not weep.”  

Then he came forward and touched the pallet,  
and the bearers stood still.  
And Jesus said, “Young man, I say to you, rise!”  
The dead man sat up and began to speak,  
and Jesus gave him to his mother.  

Fear seized all of them;  
and they glorified God, saying,  
“A great prophet has risen among us!”  
and “God has looked favourably on his people!”  
This word about Jesus spread throughout Judea  
and all the surrounding country.  

[Or:]{.red} [John 20:11-18]{style="float:right" .small .red}

Mary Magdalene stood weeping outside the tomb.  
As she wept, she bent over to look into the tomb;  
and she saw two angels in white,  
sitting where the body of Jesus had been lying,  
one at the head and the other at the feet.  
They said to her,  
“Woman, why are you weeping?”  

She said to them,  
“They have taken away my Lord,  
and I do not know where they have laid him.”  
When she had said this,  
she turned around and saw Jesus standing there,  
but she did not know that it was Jesus.  

Jesus said to her,  
“Woman, why are you weeping?  
Whom are you looking for?”  
Supposing him to be the gardener, she said to him,  
“Sir, if you have carried him away,  
tell me where you have laid him,  
and I will take him away.”  

Jesus said to her, “Mary!”  
She turned and said to him in Hebrew,  
“Rabbouni!” (which means Teacher).  

Jesus said to her,  
“Do not hold on to me,  
because I have not yet ascended to the Father.  
But go to my brothers and say to them,  
‘I am ascending to my Father and your Father,  
to my God and your God.’”  

Mary Magdalene went and announced to the disciples,  
“I have seen the Lord,”  
and she told them that he had said these things to her.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* The **Commemoration of All Souls** is not a Holy Day of Obligation.
Accordingly, the parts of the Mass may be recited instead of sung.
Musicians should coordinate with the presider before Mass for special
instructions.
* The **Responsorial Psalm**, if sung, can be taken from Respond &
Acclaim (RA).
* The **Gospel Acclamation** is sung: Chant Mode VI. Verses from the
appropriate year:

  - [Year A:]{.red}  
    “If we die with Christ, we shall *líve* with him;  
     and if we are faithful to the end, *wé* shall reign with him.”
  
  - [Year B:]{.red}  
    “Come, you who are blessed by my *Fá*ther;  
    inherit the Kingdom prepared for you from the  
    foun*dá*tion of the world.”

  - [Year C:]{.red}  
    “Jesus Christ is the firstborn *óf* the dead;  
     glory and kingship be his for ever and ev*ér*. Amen"

* [Year A:]{.red} The **Meditation Hymn** should correspond to the Gospel that is read.
