---
title: "FEAST OF THE DEDICATION OF THE LATERAN BASILICA"
subtitle: "November 9"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "O Holy City, Seen of John"
          book: G
          priority: required
    psalm:
      list:
        - name: "The waters of the river gladden the city of God, the holy dwelling of the Most High."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Christ Is Made the Sure Foundation"
          book: G
          priority: preferred
    communion:
      list:
        - name: "Draw Near"
          book: G
          priority: flexible
    meditation:
      list:
        - name: "Healing River"
          book: G
          priority: optional
        - name: "Father, We Thank You, Who Have Planted"
          book: G
          priority: optional
    recessional:
      list:
        - name: "How Firm a Foundation"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

Church, our ties to Rome, glory, holiness, joy, dwelling-place of God, people of God

:::  {.red}
#### **Entrance Antiphon**
:::

> I saw the holy city, a new Jerusalem,  
> coming down out of heaven from God,  
> prepared like bride adorned for her husband.  
>  
> [Or:]{.red}  
> 
> Behold God's dwelling with the human race.  
> He will dwell with them and they will be his people,  
> and God himself with them will be their God.

:::  {.red}
#### **Communion Antiphon**
:::

> Be built up like living stones,  
> into a spiritual house, a holy priesthood.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Ezekiel 47:1-2, 8-9, 12]{style="float:right" .small}
:::

The angel brought me  
back to the entrance of the temple,  
and I saw water flowing out  
from beneath the threshold of the temple toward the east,  
for the façade of the temple was toward the east;  
the water flowed down from the southern side of the temple,  
south of the altar.  
He led me outside by the north gate,  
and around to the outer gate facing the east,  
where I saw water trickling from the southern side.  
He said to me,  
"This water flows into the eastern district down upon the Arabah,  
and empties into the sea, the salt waters, which it makes fresh.  
Wherever the river flows,  
every sort of living creature that can multiply shall live,  
and there shall be abundant fish,  
for wherever this water comes the sea shall be made fresh.  
Along both banks of the river, fruit trees of every kind shall grow;  
their leaves shall not fade, nor their fruit fail.  
Every month they shall bear fresh fruit,  
for they shall be watered by the flow from the sanctuary.  
Their fruit shall serve for food, and their leaves for medicine."  

***

::: {.red}
#### Responsorial Psalm [Psalm 46:2-3, 5-6, 8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **The waters of the river gladden the city of God, the holy dwelling of the Most High!**  

God is our refuge and our strength,  
an ever-present help in distress.  
Therefore, we fear not, though the earth be shaken  
and mountains plunge into the depths of the sea. **[℟.]{.red}**  

There is a stream whose runlets gladden the city of God,  
the holy dwelling of the Most High.  
God is in its midst; it shall not be disturbed;  
God will help it at the break of dawn. **[℟.]{.red}**  

The LORD of hosts is with us;  
our stronghold is the God of Jacob.  
Come! behold the deeds of the LORD,  
the astounding things he has wrought on earth. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 3:9c-11, 16-17]{style="float:right" .small}
:::

Brothers and sisters:  
You are God's building.  
According to the grace of God given to me,  
like a wise master builder I laid a foundation,  
and another is building upon it.  
But each one must be careful how he builds upon it,  
for no one can lay a foundation other than the one that is there,  
namely, Jesus Christ.  

Do you not know that you are the temple of God,  
and that the Spirit of God dwells in you?  
If anyone destroys God's temple,  
God will destroy that person;  
for the temple of God, which you are, is holy.  

***

::: {.red}
#### Gospel Acclamation [2 Chronicles 7:16]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I have chosen and consecrated this house, says the Lord,  
that my name may be there forever. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 2:13-22]{style="float:right" .small}
:::

Since the Passover of the Jews was near,  
Jesus went up to Jerusalem.  
He found in the temple area those who sold oxen, sheep, and doves,  
as well as the money-changers seated there.  
He made a whip out of cords  
and drove them all out of the temple area, with the sheep and oxen,  
and spilled the coins of the money-changers  
and overturned their tables,  
and to those who sold doves he said,  
"Take these out of here,  
and stop making my Father's house a marketplace."  
His disciples recalled the words of Scripture,  
*Zeal for your house will consume me.*  
At this the Jews answered and said to him,  
"What sign can you show us for doing this?"  
Jesus answered and said to them,  
"Destroy this temple and in three days I will raise it up."  
The Jews said,  
"This temple has been under construction for forty-six years,  
and you will raise it up in three days?"  
But he was speaking about the temple of his Body.  
Therefore, when he was raised from the dead,  
his disciples remembered that he had said this,  
and they came to believe the Scripture  
and the word Jesus had spoken.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
