---
title: "SOLEMNITY OF ALL SAINTS"
subtitle: "November 1"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Ye Watchers and Ye Holy Ones"
          book: G
          priority: required
    psalm:
      list:
        - name: "Lord, this is the people that longs to see your face."
          book: RA
          priority: required
    offertory:
      list:
        - name: "For All the Saints"
          book: G
          priority: required      
    communion:
      list:
        - name: "We Are the Light of the World"
          book: G
          priority: required
    meditation:
      list:
        - name: "For All the Saints Who've Shown Your Love"
          book: G
          priority: optional
        - name: "Worthy is the Lamb"
          book: G
          priority: optional
    recessional:
      list:
        - name: "For the Faithful Who Have Answered"
          book: G
          priority: optional
        - name: "How Firm a Foundation"
          book: G
          priority: optional
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

glory, mystical body, community, holiness, mystery

:::  {.red}
#### **Entrance Antiphon**
:::

> Let us all rejoice in the Lord,  
> as we celebrate the feast day in honor of all the Saints,  
> at whose festival the Angels rejoice. 
> and praise the Son of God.

:::  {.red}
#### **Communion Antiphon**
:::

> Blessed are the clean of heart, for they shall see God.  
> Blessed are the peacemakers,  
> for they shall be called children of God.  
> Blessed are they who are persecuted for the sake of righteousness,  
> for theirs is the Kingdom of Heaven.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Revelation 7:2-4, 9-14]{style="float:right" .small}
:::

I, John, saw another angel come up from the East,  
holding the seal of the living God.  
He cried out in a loud voice to the four angels  
who were given power to damage the land and the sea,  
"Do not damage the land or the sea or the trees  
until we put the seal on the foreheads of the servants of our God."  
I heard the number of those who had been marked with the seal,  
one hundred and forty-four thousand marked  
from every tribe of the children of Israel.  

After this I had a vision of a great multitude,  
which no one could count,  
from every nation, race, people, and tongue.  
They stood before the throne and before the Lamb,  
wearing white robes and holding palm branches in their hands.  
They cried out in a loud voice:  

"Salvation comes from our God, who is seated on the throne,  
and from the Lamb."  

All the angels stood around the throne  
and around the elders and the four living creatures.  
They prostrated themselves before the throne,  
worshiped God, and exclaimed:  

"Amen. Blessing and glory, wisdom and thanksgiving,  
honor, power, and might  
be to our God forever and ever. Amen."  

Then one of the elders spoke up and said to me,  
"Who are these wearing white robes, and where did they come from?"  
I said to him, "My lord, you are the one who knows."  
He said to me,  
"These are the ones who have survived the time of great distress;  
they have washed their robes  
and made them white in the Blood of the Lamb."  

***

::: {.red}
#### Responsorial Psalm [Psalm 24:1bc-2, 3-4ab, 5-6]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, this is the people that longs to see your face.**  

The LORD's are the earth and its fullness;  
the world and those who dwell in it.  
For he founded it upon the seas  
and established it upon the rivers. **[℟.]{.red}**  

Who can ascend the mountain of the LORD?  
or who may stand in his holy place?  
One whose hands are sinless, whose heart is clean,  
who desires not what is vain. **[℟.]{.red}**  

He shall receive a blessing from the LORD,  
a reward from God his savior.  
Such is the race that seeks him,  
that seeks the face of the God of Jacob. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 John 3:1-3]{style="float:right" .small}
:::

Beloved:  
See what love the Father has bestowed on us  
that we may be called the children of God.  
Yet so we are.  
The reason the world does not know us  
is that it did not know him.  
Beloved, we are God's children now;  
what we shall be has not yet been revealed.  
We do know that when it is revealed we shall be like him,  
for we shall see him as he is.  
Everyone who has this hope based on him makes himself pure,  
as he is pure.  

***

::: {.red}
#### Gospel Acclamation [Matthew 11:28]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Come to me, all you who labor and are burdened,  
And I will give you rest, says the Lord. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 5:1-12a]{style="float:right" .small}
:::

When Jesus saw the crowds, he went up the mountain,  
and after he had sat down, his disciples came to him.  
He began to teach them, saying:  

"Blessed are the poor in spirit,  
for theirs is the Kingdom of heaven.  
Blessed are they who mourn,  
for they will be comforted.  
Blessed are the meek,  
for they will inherit the land.  
Blessed are they who hunger and thirst for righteousness,  
for they will be satisfied.  
Blessed are the merciful,  
for they will be shown mercy.  
Blessed are the clean of heart,  
for they will see God.  
Blessed are the peacemakers,  
for they will be called children of God.  
Blessed are they who are persecuted for the sake of righteousness,  
for theirs is the Kingdom of heaven.  
Blessed are you when they insult you and persecute you  
and utter every kind of evil against you falsely because of me.  
Rejoice and be glad,  
for your reward will be great in heaven."  

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
