---
title: "FEAST OF THE EXALTATION OF THE HOLY CROSS"
subtitle: "September 14"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Take Up Your Cross"
          book: G
          priority: preferred
        - name: "Crown Him with Many Crowns"
          book: G
          priority: optional
    psalm:
      list:
        - name: "Do not forget the works of the Lord!"
          book: RA
          priority: required
    offertory:
      list:
        - name: "Only This I Want"
          book: G
          priority: optional
        - name: "All Hail the Power of Jesus' Name!"
          book: G
          priority: optional
    communion:
      list:
        - name: "You, Lord, Are Both Lamb and Shepherd"
          book: G
          priority: preferred
    meditation:
      list:
        - name: "What Wondrous Love"
          book: G
          priority: required
    recessional:
      list:
        - name: "Lift High the Cross"
          book: G
          priority: preferred
        - name: "The Kingdom of God"
          book: G
          priority: optinal
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

cross, Christ's mission, dignity of Christ, God's love

:::  {.red}
#### **Entrance Antiphon**
:::

> We should glory in the Cross of our Lord Jesus Christ,  
> in whom is our salvation, life and resurrection,  
> through whom we are saved and delivered.

:::  {.red}
#### **Communion Antiphon**
:::

> When I am lifted up from the earth,  
> I will draw everyone to myself, says the Lord.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Numbers 21:4B-9]{style="float:right" .small}
:::

With their patience worn out by the journey,  
the people complained against God and Moses,  
“Why have you brought us up from Egypt to die in this desert,  
where there is no food or water?  
We are disgusted with this wretched food!”  

In punishment the LORD sent among the people saraph serpents,  
which bit the people so that many of them died.  
Then the people came to Moses and said,  
“We have sinned in complaining against the LORD and you.  
Pray the LORD to take the serpents from us.”  
So Moses prayed for the people, and the LORD said to Moses,  
“Make a saraph and mount it on a pole,  
and if any who have been bitten look at it, they will live.”  
Moses accordingly made a bronze serpent and mounted it on a pole,  
and whenever anyone who had been bitten by a serpent  
looked at the bronze serpent, he lived.  

***

::: {.red}
#### Responsorial Psalm [Psalm 78:1bc-2, 34-35, 36-37, 38]{style="float:right" .small}
:::

**[℟.]{.red}** **Do not forget the works of the Lord!**  

Hearken, my people, to my teaching;  
incline your ears to the words of my mouth.  
I will open my mouth in a parable,  
I will utter mysteries from of old. **[℟.]{.red}**  

While he slew them they sought him  
and inquired after God again,  
Remembering that God was their rock  
and the Most High God, their redeemer. **[℟.]{.red}**  

But they flattered him with their mouths  
and lied to him with their tongues,  
Though their hearts were not steadfast toward him,  
nor were they faithful to his covenant. **[℟.]{.red}**  

But he, being merciful, forgave their sin  
and destroyed them not;  
Often he turned back his anger  
and let none of his wrath be roused. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Philippians 2:6-11]{style="float:right" .small}
:::

Brothers and sisters:  
Christ Jesus, though he was in the form of God,  
did not regard equality with God something to be grasped.  
Rather, he emptied himself,  
taking the form of a slave,  
coming in human likeness;  
and found human in appearance,  
he humbled himself,  
becoming obedient to death,  
even death on a cross.  
Because of this, God greatly exalted him  
and bestowed on him the name  
that is above every name,  
that at the name of Jesus  
every knee should bend,  
of those in heaven and on earth and under the earth,  
and every tongue confess that  
Jesus Christ is Lord,  
to the glory of God the Father.  

***

::: {.red}
#### Gospel Acclamation
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
We adore you, O Christ, and we bless you,  
because by your Cross you have redeemed the world. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 3:13-17]{style="float:right" .small}
:::

Jesus said to Nicodemus:  
“No one has gone up to heaven  
except the one who has come down from heaven, the Son of Man.  
And just as Moses lifted up the serpent in the desert,  
so must the Son of Man be lifted up,  
so that everyone who believes in him may have eternal life.”  

For God so loved the world that he gave his only Son,  
so that everyone who believes in him might not perish  
but might have eternal life.  
For God did not send his Son into the world to condemn the world,  
but that the world might be saved through him.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Years ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
