---
title: "FRIDAY OF THE PASSION OF THE LORD"
subtitle: "Good Friday"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    psalm:
      list:
        - name: "Father, into your hands I commend my spirit."
          book: RA
          priority: required
    veneration-of-the-cross:
      list:
        - name: "Behold the Wood"
          book: G
          priority: required
    communion:
      list:
        - name: "O Sacred Head, Surrounded"
          book: G
          priority: required
    meditation:
      list:
        - name: "Jesus, Remember Me"
          book: G
          note: "*a capella*"
          priority: required
    anthems:
      list:
        - name: "God So Loved the World"
          composer: "John Stainer"
  b:
    psalm:
      list:
        - name: "Father, into your hands I commend my spirit."
          book: RA
          priority: required
    veneration-of-the-cross:
      list:
        - name: "Hail our Savior's Glorious Body"
          book: G
          priority: required
    communion:
      list:
        - name: "Were You There"
          book: G
          priority: required
    meditation:
      list:
        - name: "Jesus, Remember Me"
          book: G
          note: "*a capella*"
          priority: required
    anthems:
      list:
        - name: "Near the Cross"
        - name: "When Jesus Wept"
  c:
    psalm:
      list:
        - name: "Father, into your hands I commend my spirit."
          book: RA
          priority: required
    offertory:
      list:
        - name: "At the Cross Her Station Keeping"
          book: G
          priority: required
    communion:
      list:
        - name: "What Wondrous Love is This"
          book: G
          priority: required
    meditation:
      list:
        - name: "In Manus Tuas, Pater"
          book: G
          priority: required
    anthems:
      list:
        - name: "Lord, Let Me Walk"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

silence, awe, cross, passion & death, salvation, triumph

:::  {.red}
#### **Entrance Antiphon**
:::

*No Entrance Antiphon*

:::  {.red}
#### **Communion Antiphon**
:::

*No Communion Antiphon*

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Isaiah 52:13—53:12]{style="float:right" .small}
:::

See, my servant shall prosper,  
&emsp; he shall be raised high and greatly exalted.  
Even as many were amazed at him--  
&emsp; so marred was his look beyond human semblance  
&emsp; and his appearance beyond that of the sons of man--  
so shall he startle many nations,  
&emsp; because of him kings shall stand speechless;  
for those who have not been told shall see,  
&emsp; those who have not heard shall ponder it.  

Who would believe what we have heard?  
&emsp; To whom has the arm of the LORD been revealed?  
He grew up like a sapling before him,  
&emsp; like a shoot from the parched earth;  
there was in him no stately bearing to make us look at him,  
&emsp; nor appearance that would attract us to him.  
He was spurned and avoided by people,  
&emsp; a man of suffering, accustomed to infirmity,  
one of those from whom people hide their faces,  
&emsp; spurned, and we held him in no esteem.  

Yet it was our infirmities that he bore,  
&emsp; our sufferings that he endured,  
while we thought of him as stricken,  
&emsp; as one smitten by God and afflicted.  
But he was pierced for our offenses,  
&emsp; crushed for our sins;  
upon him was the chastisement that makes us whole,  
&emsp; by his stripes we were healed.  
We had all gone astray like sheep,  
&emsp; each following his own way;  
but the LORD laid upon him  
&emsp; the guilt of us all.  

Though he was harshly treated, he submitted  
&emsp; and opened not his mouth;  
like a lamb led to the slaughter  
&emsp; or a sheep before the shearers,  
&emsp; he was silent and opened not his mouth.  
Oppressed and condemned, he was taken away,  
&emsp; and who would have thought any more of his destiny?  
When he was cut off from the land of the living,  
&emsp; and smitten for the sin of his people,  
a grave was assigned him among the wicked  
&emsp; and a burial place with evildoers,  
though he had done no wrong  
&emsp; nor spoken any falsehood.  
But the LORD was pleased  
&emsp; to crush him in infirmity.  

If he gives his life as an offering for sin,  
&emsp; he shall see his descendants in a long life,  
&emsp; and the will of the LORD shall be accomplished through him.  

Because of his affliction  
&emsp; he shall see the light in fullness of days;  
through his suffering, my servant shall justify many,  
&emsp; and their guilt he shall bear.  
Therefore I will give him his portion among the great,  
&emsp; and he shall divide the spoils with the mighty,  
because he surrendered himself to death  
&emsp; and was counted among the wicked;  
and he shall take away the sins of many,  
&emsp; and win pardon for their offenses.  

***

::: {.red}
#### Responsorial Psalm [Luke 23:46; Psalm 31:2, 6, 12-13, 15-16, 17, 25]{style="float:right" .small}
:::

**[℟.]{.red}** **Father, into your hands I commend my spirit.**  

In you, O LORD, I take refuge;  
&emsp; let me never be put to shame.  
In your justice rescue me.  
&emsp; Into your hands I commend my spirit;  
you will redeem me, O LORD, O faithful God. **[℟.]{.red}**  

For all my foes I am an object of reproach,  
&emsp; a laughingstock to my neighbors, and a dread to my friends;  
they who see me abroad flee from me.  
&emsp; I am forgotten like the unremembered dead;  
I am like a dish that is broken. **[℟.]{.red}**  

But my trust is in you, O LORD;  
&emsp; I say, “You are my God.  
In your hands is my destiny; rescue me  
&emsp; from the clutches of my enemies and my persecutors.” **[℟.]{.red}**  

Let your face shine upon your servant;  
&emsp; save me in your kindness.  
Take courage and be stouthearted,  
&emsp; all you who hope in the LORD. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Hebrews 4:14-16; 5:7-9]{style="float:right" .small}
:::

Brothers and sisters:  
Since we have a great high priest who has passed through the heavens,  
Jesus, the Son of God,  
let us hold fast to our confession.  
For we do not have a high priest  
who is unable to sympathize with our weaknesses,  
but one who has similarly been tested in every way,  
yet without sin.  
So let us confidently approach the throne of grace  
to receive mercy and to find grace for timely help.  

In the days when Christ was in the flesh,  
he offered prayers and supplications with loud cries and tears  
to the one who was able to save him from death,  
and he was heard because of his reverence.  
Son though he was, he learned obedience from what he suffered;  
and when he was made perfect,  
he became the source of eternal salvation for all who obey him.  

***

::: {.red}
#### Gospel Acclamation [Philippians 2:8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
Christ became obedient to the point of death,  
even death on a cross.  
Because of this, God greatly exalted him  
and bestowed on him the name which is above every other name. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 18:1—19:42]{style="float:right" .small}
:::

[*The passion narratives are proclaimed in full so that all see vividly the love of Christ for each person. In light of this, the crimes during the Passion of Christ cannot be attributed, in either preaching or catechesis, indiscriminately to all Jews of that time, nor to Jews today. The Jewish people should not be referred to as though rejected or cursed, as if this view followed from Scripture. The Church ever keeps in mind that Jesus, his mother Mary, and the apostles all were Jewish. As the Church has always held, Christ freely suffered his passion and death because of the sins of all, that all might be saved.*]{.red}

Jesus went out with his disciples across the Kidron valley  
to where there was a garden,  
into which he and his disciples entered.  
Judas his betrayer also knew the place,  
because Jesus had often met there with his disciples.  
So Judas got a band of soldiers and guards  
from the chief priests and the Pharisees  
and went there with lanterns, torches, and weapons.  
Jesus, knowing everything that was going to happen to him,  
went out and said to them, “Whom are you looking for?”  
They answered him, “Jesus the Nazorean.”  
He said to them, “I AM.”  
Judas his betrayer was also with them.  
When he said to them, “I AM,“  
they turned away and fell to the ground.  
So he again asked them,  
“Whom are you looking for?”  
They said, “Jesus the Nazorean.”  
Jesus answered,  
“I told you that I AM.  
So if you are looking for me, let these men go.”  
This was to fulfill what he had said,  
“I have not lost any of those you gave me.”  
Then Simon Peter, who had a sword, drew it,  
struck the high priest’s slave, and cut off his right ear.  
The slave’s name was Malchus.  
Jesus said to Peter,  
“Put your sword into its scabbard.  
Shall I not drink the cup that the Father gave me?”  

So the band of soldiers, the tribune, and the Jewish guards seized Jesus,  
bound him, and brought him to Annas first.  
He was the father-in-law of Caiaphas,  
who was high priest that year.  
It was Caiaphas who had counseled the Jews  
that it was better that one man should die rather than the people.  

Simon Peter and another disciple followed Jesus.  
Now the other disciple was known to the high priest,  
and he entered the courtyard of the high priest with Jesus.  
But Peter stood at the gate outside.  
So the other disciple, the acquaintance of the high priest,  
went out and spoke to the gatekeeper and brought Peter in.  
Then the maid who was the gatekeeper said to Peter,  
“You are not one of this man’s disciples, are you?”  
He said, “I am not.”  
Now the slaves and the guards were standing around a charcoal fire  
that they had made, because it was cold,  
and were warming themselves.  
Peter was also standing there keeping warm.  

The high priest questioned Jesus  
about his disciples and about his doctrine.  
Jesus answered him,  
“I have spoken publicly to the world.  
I have always taught in a synagogue  
or in the temple area where all the Jews gather,  
and in secret I have said nothing.  Why ask me?  
Ask those who heard me what I said to them.  
They know what I said.”  
When he had said this,  
one of the temple guards standing there struck Jesus and said,  
“Is this the way you answer the high priest?”  
Jesus answered him,  
“If I have spoken wrongly, testify to the wrong;  
but if I have spoken rightly, why do you strike me?”  
Then Annas sent him bound to Caiaphas the high priest.  

Now Simon Peter was standing there keeping warm.  
And they said to him,  
“You are not one of his disciples, are you?”  
He denied it and said,  
“I am not.”  
One of the slaves of the high priest,  
a relative of the one whose ear Peter had cut off, said,  
“Didn’t I see you in the garden with him?”  
Again Peter denied it.  
And immediately the cock crowed.  

Then they brought Jesus from Caiaphas to the praetorium.  
It was morning.  
And they themselves did not enter the praetorium,  
in order not to be defiled so that they could eat the Passover.  
So Pilate came out to them and said,  
“What charge do you bring against this man?”  
They answered and said to him,  
“If he were not a criminal,  
we would not have handed him over to you.”  
At this, Pilate said to them,  
“Take him yourselves, and judge him according to your law.”  
The Jews answered him,  
“We do not have the right to execute anyone,“  
in order that the word of Jesus might be fulfilled  
that he said indicating the kind of death he would die.  
So Pilate went back into the praetorium  
and summoned Jesus and said to him,  
“Are you the King of the Jews?”  
Jesus answered,  
“Do you say this on your own  
or have others told you about me?”  
Pilate answered,  
“I am not a Jew, am I?  
Your own nation and the chief priests handed you over to me.  
What have you done?”  
Jesus answered,  
“My kingdom does not belong to this world.  
If my kingdom did belong to this world,  
my attendants would be fighting  
to keep me from being handed over to the Jews.  
But as it is, my kingdom is not here.”  
So Pilate said to him,  
“Then you are a king?”  
Jesus answered,  
“You say I am a king.  
For this I was born and for this I came into the world,  
to testify to the truth.  
Everyone who belongs to the truth listens to my voice.”  
Pilate said to him, “What is truth?”  

When he had said this,  
he again went out to the Jews and said to them,  
“I find no guilt in him.  
But you have a custom that I release one prisoner to you at Passover.  
Do you want me to release to you the King of the Jews?”  
They cried out again,  
“Not this one but Barabbas!”  
Now Barabbas was a revolutionary.  

Then Pilate took Jesus and had him scourged.  
And the soldiers wove a crown out of thorns and placed it on his head,  
and clothed him in a purple cloak,  
and they came to him and said,  
“Hail, King of the Jews!”  
And they struck him repeatedly.  
Once more Pilate went out and said to them,  
“Look, I am bringing him out to you,  
so that you may know that I find no guilt in him.”  
So Jesus came out,  
wearing the crown of thorns and the purple cloak.  
And he said to them, “Behold, the man!”  
When the chief priests and the guards saw him they cried out,  
“Crucify him, crucify him!”  
Pilate said to them,  
“Take him yourselves and crucify him.  
I find no guilt in him.”  
The Jews answered,  
“We have a law, and according to that law he ought to die,  
because he made himself the Son of God.”  
Now when Pilate heard this statement,  
he became even more afraid,  
and went back into the praetorium and said to Jesus,  
“Where are you from?”  
Jesus did not answer him.  
So Pilate said to him,  
“Do you not speak to me?  
Do you not know that I have power to release you  
and I have power to crucify you?”  
Jesus answered him,  
“You would have no power over me  
if it had not been given to you from above.  
For this reason the one who handed me over to you  
has the greater sin.”  
Consequently, Pilate tried to release him; but the Jews cried out,  
“If you release him, you are not a Friend of Caesar.  
Everyone who makes himself a king opposes Caesar.”  

When Pilate heard these words he brought Jesus out  
and seated him on the judge’s bench  
in the place called Stone Pavement, in Hebrew, Gabbatha.  
It was preparation day for Passover, and it was about noon.  
And he said to the Jews,  
“Behold, your king!”  
They cried out,  
“Take him away, take him away!  Crucify him!”  
Pilate said to them,  
“Shall I crucify your king?”  
The chief priests answered,  
“We have no king but Caesar.”  
Then he handed him over to them to be crucified.  

So they took Jesus, and, carrying the cross himself,  
he went out to what is called the Place of the Skull,  
in Hebrew, Golgotha.  
There they crucified him, and with him two others,  
one on either side, with Jesus in the middle.  
Pilate also had an inscription written and put on the cross.  
It read,  
“Jesus the Nazorean, the King of the Jews.”  
Now many of the Jews read this inscription,  
because the place where Jesus was crucified was near the city;  
and it was written in Hebrew, Latin, and Greek.  
So the chief priests of the Jews said to Pilate,  
 “Do not write ‘The King of the Jews,’  
but that he said, ‘I am the King of the Jews’.”  
Pilate answered,  
“What I have written, I have written.”  

When the soldiers had crucified Jesus,  
they took his clothes and divided them into four shares,  
a share for each soldier.  
They also took his tunic, but the tunic was seamless,  
woven in one piece from the top down.  
So they said to one another,  
“Let’s not tear it, but cast lots for it to see whose it will be,“  
in order that the passage of Scripture might be fulfilled that says:  
&emsp; *They divided my garments among them,*  
&emsp; &emsp; *and for my vesture they cast lots.*  
This is what the soldiers did.  
Standing by the cross of Jesus were his mother  
and his mother’s sister, Mary the wife of Clopas,  
and Mary of Magdala.  
When Jesus saw his mother and the disciple there whom he loved  
he said to his mother, “Woman, behold, your son.”  
Then he said to the disciple,  
“Behold, your mother.”  
And from that hour the disciple took her into his home.  

After this, aware that everything was now finished,  
in order that the Scripture might be fulfilled,  
Jesus said, “I thirst.”  
There was a vessel filled with common wine.  
So they put a sponge soaked in wine on a sprig of hyssop  
and put it up to his mouth.  
When Jesus had taken the wine, he said,  
“It is finished.”  
And bowing his head, he handed over the spirit.  

[*Here all kneel and pause for a short time.*]{.red}  

Now since it was preparation day,  
in order that the bodies might not remain on the cross on the sabbath,  
for the sabbath day of that week was a solemn one,  
the Jews asked Pilate that their legs be broken  
and that they be taken down.  
So the soldiers came and broke the legs of the first  
and then of the other one who was crucified with Jesus.  
But when they came to Jesus and saw that he was already dead,  
they did not break his legs,  
but one soldier thrust his lance into his side,  
and immediately blood and water flowed out.  
An eyewitness has testified, and his testimony is true;  
he knows that he is speaking the truth,  
so that you also may come to believe.  
For this happened so that the Scripture passage might be fulfilled:  
&emsp; *Not a bone of it will be broken.*  
And again another passage says:  
&emsp; *They will look upon him whom they have pierced.*. 

After this, Joseph of Arimathea,  
secretly a disciple of Jesus for fear of the Jews,  
asked Pilate if he could remove the body of Jesus.  
And Pilate permitted it.  
So he came and took his body.  
Nicodemus, the one who had first come to him at night,  
also came bringing a mixture of myrrh and aloes  
weighing about one hundred pounds.  
They took the body of Jesus  
and bound it with burial cloths along with the spices,  
according to the Jewish burial custom.  
Now in the place where he had been crucified there was a garden,  
and in the garden a new tomb, in which no one had yet been buried.  
So they laid Jesus there because of the Jewish preparation day;  
for the tomb was close by.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The Holy Triduum–--Holy Thursday, Good Friday, and the Easter Vigil---
is one single liturgy. Thus, there is no processional or recessional hymn
on Good Friday. All gather and depart in **silence**.
* No prelude or postlude music is permitted. The organ and other musical
instruments may be used only so as to support singing.
* No music rehearsals of any kind, including singer warm-ups, should take
place in the church before this service. Sacred silence is to be diligently
respected by all.
* If given the option, the hymn “Were You There” should be taken from GIA,
either the Gather or Worship hymnal, which usually have more verses than Breaking Bread.
* Choral anthems oﬀered as alternatives or in addition to hymns listed for
the Veneration of the Cross, Communion hymn, or Meditation hymn. Good Friday should be coordinated with Palm Sunday to avoid repeating anthems.