---
title: "HOLY THURSDAY"
subtitle: "Mass of the Lord's Supper"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "As We Gather at Your Table"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "Our blessing-cup is a communion with the Blood of Christ."
          book: RA
          priority: required
    washing-of-feet:
      list:
        - name: "Ubi Caritas"
          composer: Hurd
          book: G
          priority: required
    offertory:
      list:
        - name: "Lord, Who at Your First Eucharist"
          book: G
          priority: required
    communion:
      list:
        - name: "Take and Eat"
          book: G
          priority: required
    meditation:
      list:
        - name: "Prepare a Room for Me"
          book: G
          priority: required
    transfer-of-the-blessed-sacrament:
      list:
        - name: "Pange, Lingua"
          book: G
          priority: required
    anthems:
      list:
        - name: "Ave Verum Corpus"
          composer: Mozart
  b:
    processional:
      list:
        - name: "Come to the Banquet"
          book: G
          priority: required
    psalm:
      list:
        - name: "Our blessing-cup is a communion with the Blood of Christ."
          book: RA
          priority: required
    washing-of-feet:
      list:
        - name: "Jesu, Jesu"
          book: G
          priority: required
    offertory:
      list:
        - name: "Lord, Who at Your First Eucharist"
          book: G
          priority: required
    communion:
      list:
        - name: "Pan de Vida"
          book: G
          note: "English verses"
          priority: required
    meditation:
      list:
        - name: "Ubi Caritas"
          tune: Chant
          book: G
          priority: required
    transfer-of-the-blessed-sacrament:
      list:
        - name: "Pange, Lingua"
          book: G
          priority: required
  c:
    processional:
      list:
        - name: "Come to the Feast"
          book: G
          priority: required
    psalm:
      list:
        - name: "Our blessing-cup is a communion with the Blood of Christ."
          book: RA
          priority: required
    washing-of-feet:
      list:
        - name: "This is My Example"
          book: G
          priority: required
    offertory:
      list:
        - name: "Lord, Who at Your First Eucharist"
          book: G
          priority: required
    communion:
      list:
        - name: "Draw Near"
          book: G
          priority: required
    meditation:
      list:
        - name: "Ubi Caritas"
          tune: Taize
          book: G
          priority: required
    transfer-of-the-blessed-sacrament:
      list:
        - name: "Pange, Lingua"
          book: G
          priority: required
    anthems:
      list:
        - name: "Panis Angelicus"
          composer: "Franck"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

eucharist, glory, salvation, service, humility, love

:::  {.red}
#### **Entrance Antiphon**
:::

> We should glory in the Cross of our Lord Jesus Christ,  
> in whom is our salvation, life and resurrection,  
> through whom we are saved and delivered.

:::  {.red}
#### **Communion Antiphon**
:::

> This is the Body that will be given up for you;  
> this is the Chalice of the new covenant in my Blood, says the Lord;  
> do this, whenever you receive it, in memory of me.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Exodus 12:1-8, 11-14]{style="float:right" .small}
:::

The LORD said to Moses and Aaron in the land of Egypt,  
“This month shall stand at the head of your calendar;  
you shall reckon it the first month of the year.  
Tell the whole community of Israel:  
On the tenth of this month every one of your families  
must procure for itself a lamb, one apiece for each household.  
If a family is too small for a whole lamb,  
it shall join the nearest household in procuring one  
and shall share in the lamb  
in proportion to the number of persons who partake of it.  
The lamb must be a year-old male and without blemish.  
You may take it from either the sheep or the goats.  
You shall keep it until the fourteenth day of this month,  
and then, with the whole assembly of Israel present,  
it shall be slaughtered during the evening twilight.  
They shall take some of its blood  
and apply it to the two doorposts and the lintel  
of every house in which they partake of the lamb.  
That same night they shall eat its roasted flesh  
with unleavened bread and bitter herbs.  

“This is how you are to eat it:  
with your loins girt, sandals on your feet and your staff in hand,  
you shall eat like those who are in flight.  
It is the Passover of the LORD.  
For on this same night I will go through Egypt,  
striking down every firstborn of the land, both man and beast,  
and executing judgment on all the gods of Egypt—I, the LORD!  
But the blood will mark the houses where you are.  
Seeing the blood, I will pass over you;  
thus, when I strike the land of Egypt,  
no destructive blow will come upon you.  

“This day shall be a memorial feast for you,  
which all your generations shall celebrate  
with pilgrimage to the LORD, as a perpetual institution.”

***

::: {.red}
#### Responsorial Psalm [cf. 1 Cor 10:16; Psalm 116:12-13, 15-16bc, 17-18]{style="float:right" .small}
:::

**[℟.]{.red}** **Our blessing-cup is a communion with the Blood of Christ.**  

How shall I make a return to the LORD  
&emsp; for all the good he has done for me?  
The cup of salvation I will take up,  
&emsp; and I will call upon the name of the LORD. **[℟.]{.red}**  

Precious in the eyes of the LORD  
&emsp; is the death of his faithful ones.  
I am your servant, the son of your handmaid;  
&emsp; you have loosed my bonds. **[℟.]{.red}**  

To you will I offer sacrifice of thanksgiving,  
&emsp; and I will call upon the name of the LORD.  
My vows to the LORD I will pay  
&emsp; in the presence of all his people. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 11:23-26]{style="float:right" .small}
:::

Brothers and sisters:  
I received from the Lord what I also handed on to you,  
that the Lord Jesus, on the night he was handed over,  
took bread, and, after he had given thanks,  
broke it and said, “This is my body that is for you.  
Do this in remembrance of me.”  
In the same way also the cup, after supper, saying,  
“This cup is the new covenant in my blood.  
Do this, as often as you drink it, in remembrance of me.”  
For as often as you eat this bread and drink the cup,  
you proclaim the death of the Lord until he comes.  

***

::: {.red}
#### Gospel Acclamation [John 13:34]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
I give you a new commandment, says the Lord:  
love one another as I have loved you. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 13:1-15]{style="float:right" .small}
:::

Before the feast of Passover, Jesus knew that his hour had come  
to pass from this world to the Father.  
He loved his own in the world and he loved them to the end.  
The devil had already induced Judas, son of Simon the Iscariot, to hand him over.  
So, during supper,  
fully aware that the Father had put everything into his power  
and that he had come from God and was returning to God,  
he rose from supper and took off his outer garments.  
He took a towel and tied it around his waist.  
Then he poured water into a basin  
and began to wash the disciples’ feet  
and dry them with the towel around his waist.  
He came to Simon Peter, who said to him,  
“Master, are you going to wash my feet?”  
Jesus answered and said to him,  
“What I am doing, you do not understand now,  
but you will understand later.”  
Peter said to him, “You will never wash my feet.”  
Jesus answered him,  
“Unless I wash you, you will have no inheritance with me.”  
Simon Peter said to him,  
“Master, then not only my feet, but my hands and head as well.”  
Jesus said to him,  
“Whoever has bathed has no need except to have his feet washed,  
&emsp; for he is clean all over;  
so you are clean, but not all.”  
For he knew who would betray him;  
for this reason, he said, “Not all of you are clean.”  

So when he had washed their feet  
and put his garments back on and reclined at table again,  
he said to them, “Do you realize what I have done for you?  
You call me ‘teacher’ and ‘master,’  and rightly so, for indeed I am.  
If I, therefore, the master and teacher, have washed your feet,  
you ought to wash one another’s feet.  
I have given you a model to follow,  
so that as I have done for you, you should also do.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The **Gloria** is sung. While the hymn is being sung, bells are rung. The
organist is encouraged to use the Zimbelstern throughout the entire
piece. Cantors and singers should be prepared to sing strongly and
joyously. When finished, all bells remain silent until the **Gloria** of the Easter Vigil. Likewise, during this same period, the organ and other
musical instruments may be used only so as to support singing.
* During the **Transfer of the Blessed Sacrament** to the Altar of
Repose, verses 1-4 of “Pange Lingua, Gloriosi” are sung, repeating as
necessary. Verses 5-6 (“Tantum Ergo”) are sung at the Altar of Repose.