---
title: "PALM SUNDAY OF THE PASSION OF THE LORD"
subtitle: "Palm Sunday"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "All Glory, Laud, and Honor"
          book: G
          priority: required
    psalm:
      list:
        - name: "My God, my God, why have you abandoned me?"
          book: RA
          priority: required
    offertory:
      list:
        - name: "What Wondrous Love is This"
          book: G
          priority: required
    communion:
      list:
        - name: "Psalm of Hope"
          book: G
          priority: required
    meditation:
      list:
        - name: "Stay Here and Keep Watch"
          book: G
          priority: required
    recessional:
      list:
        - name: "Lift High the Cross"
          book: G
          priority: required
    anthems:
      list:
        - name: "Near the Cross"
        - name: "Lord, Let Me Walk"
  b:
    processional:
      list:
        - name: "All Glory, Laud, and Honor"
          book: G
          priority: required
    psalm:
      list:
        - name: "My God, my God, why have you abandoned me?"
          book: RA
          priority: required
    offertory:
      list:
        - name: "Crown Him With Many Crowns"
          book: G
          priority: optional
        - name: "You, Lord, Are Both Lamb and Shepherd"
          verses: 1-3
          book: G
          priority: optional
    communion:
      list:
        - name: "O Sacred Head, Surrounded"
          book: G
          priority: required
    meditation:
      list:
        - name: "In Manus Tuas, Pater"
          book: G
          priority: required
    recessional:
      list:
        - name: "Lift High the Cross"
          book: G
          priority: required
    anthems:
      list:
        - name: "God So Loved the World"
          composer: "John Stainer"
        - name: "Jesus Walked This Lonesome Valley"
  c:
    processional:
      list:
        - name: "All Glory, Laud, and Honor"
          book: G
          priority: required
    psalm:
      list:
        - name: "My God, my God, why have you abandoned me?"
          book: RA
          priority: required
    offertory:
      list:
        - name: "Palm Sunday Processional"
          book: G
          priority: required
    communion:
      list:
        - name: "Were You There"
          book: G
          priority: required
    meditation:
      list:
        - name: "Jesus, Remember Me"
          book: G
          note:  "*a capella*"
          priority: required
    recessional:
      list:
        - name: "Lift High the Cross"
          book: G
          priority: required
    anthems:
      list:
        - name: "When Jesus Wept"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

triumph/passion, glory/suﬀering

:::  {.red}
#### **Entrance Antiphon**
:::

> Hosanna to the Son of David;  
> blessed is he who comes in the name of the Lord,  
> the King of Israel. Hosanna in the highest.

:::  {.red}
#### **Communion Antiphon**
:::

> Father, if this chalice cannot pass without my drinking it,  
> your will be done.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### At the Procession with Palms - Gospel [Matthew 21:1-11]{style="float:right" .small}
:::

When Jesus and the disciples drew near Jerusalem  
and came to Bethphage on the Mount of Olives,  
Jesus sent two disciples, saying to them,  
"Go into the village opposite you,  
and immediately you will find an ass tethered,  
and a colt with her.  
Untie them and bring them here to me.  
And if anyone should say anything to you, reply,  
'The master has need of them.'  
Then he will send them at once."  
This happened so that what had been spoken through the prophet  
might be fulfilled:  
*Say to daughter Zion,*  
"*Behold, your king comes to you,*  
*meek and riding on an ass,*  
*and on a colt, the foal of a beast of burden.*"  
The disciples went and did as Jesus had ordered them.  
They brought the ass and the colt and laid their cloaks over them,  
and he sat upon them.  
The very large crowd spread their cloaks on the road,  
while others cut branches from the trees  
and strewed them on the road.  
The crowds preceding him and those following  
kept crying out and saying:  
"Hosanna to the Son of David;  
blessed is he who comes in the name of the Lord;  
hosanna in the highest."  
And when he entered Jerusalem  
the whole city was shaken and asked, "Who is this?"  
And the crowds replied,  
"This is Jesus the prophet, from Nazareth in Galilee."  

:::{.red}
#### At the Mass - First Reading [Isaiah 50:4-7]{style="float:right" .small}
:::

The Lord GOD has given me  
&emsp; a well-trained tongue,  
that I might know how to speak to the weary  
&emsp; a word that will rouse them.  
Morning after morning  
&emsp; he opens my ear that I may hear;  
and I have not rebelled,  
&emsp; have not turned back.  
I gave my back to those who beat me,  
&emsp; my cheeks to those who plucked my beard;  
my face I did not shield  
&emsp; from buffets and spitting.  

The Lord GOD is my help,  
&emsp; therefore I am not disgraced;  
I have set my face like flint,  
&emsp; knowing that I shall not be put to shame.  

***

::: {.red}
#### Responsorial Psalm [Psalm 22:8-9, 17-18, 19-20, 23-24]{style="float:right" .small}
:::

**[℟.]{.red}** **My God, my God, why have you abandoned me?**  

All who see me scoff at me;  
&emsp; they mock me with parted lips, they wag their heads:  
“He relied on the LORD; let him deliver him,  
&emsp; let him rescue him, if he loves him.” **[℟.]{.red}**  

Indeed, many dogs surround me,  
&emsp; a pack of evildoers closes in upon me;  
They have pierced my hands and my feet;  
&emsp; I can count all my bones. **[℟.]{.red}**  

They divide my garments among them,  
&emsp; and for my vesture they cast lots.  
But you, O LORD, be not far from me;  
&emsp; O my help, hasten to aid me. **[℟.]{.red}**  

I will proclaim your name to my brethren;  
&emsp; in the midst of the assembly I will praise you:  
“You who fear the LORD, praise him;  
&emsp; all you descendants of Jacob, give glory to him;  
&emsp; revere him, all you descendants of Israel!” **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Philippians 2:6-11]{style="float:right" .small}
:::

Christ Jesus, though he was in the form of God,  
&emsp; did not regard equality with God  
&emsp; something to be grasped.  
Rather, he emptied himself,  
&emsp; taking the form of a slave,  
&emsp; coming in human likeness;  
&emsp; and found human in appearance,  
&emsp; he humbled himself,  
&emsp; becoming obedient to the point of death,  
&emsp; even death on a cross.  
Because of this, God greatly exalted him  
&emsp; and bestowed on him the name  
&emsp; which is above every name,  
&emsp; that at the name of Jesus  
&emsp; every knee should bend,  
&emsp; of those in heaven and on earth and under the earth,  
&emsp; and every tongue confess that  
&emsp; Jesus Christ is Lord,  
&emsp; to the glory of God the Father.  

***

::: {.red}
#### Gospel Acclamation [Philippians 2:8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
Christ became obedient to the point of death,  
even death on a cross.  
Because of this, God greatly exalted him  
and bestowed on him the name which is above every name. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Matthew 26:14—27:66 or 27:11-54]{style="float:right" .small}
:::

One of the Twelve, who was called Judas Iscariot,  
went to the chief priests and said,  
"What are you willing to give me  
if I hand him over to you?"  
They paid him thirty pieces of silver,  
and from that time on he looked for an opportunity  
to hand him over.  

On the first day of the Feast of Unleavened Bread,  
the disciples approached Jesus and said,  
"Where do you want us to prepare  
for you to eat the Passover?"  
He said,  
"Go into the city to a certain man and tell him,  
'The teacher says, "My appointed time draws near;  
in your house I shall celebrate the Passover with my disciples."'"  
The disciples then did as Jesus had ordered,  
and prepared the Passover.  

When it was evening,  
he reclined at table with the Twelve.  
And while they were eating, he said,  
"Amen, I say to you, one of you will betray me."  
Deeply distressed at this,  
they began to say to him one after another,  
"Surely it is not I, Lord?"  
He said in reply,  
"He who has dipped his hand into the dish with me  
is the one who will betray me.  
The Son of Man indeed goes, as it is written of him,  
but woe to that man by whom the Son of Man is betrayed.  
It would be better for that man if he had never been born."  
Then Judas, his betrayer, said in reply,  
"Surely it is not I, Rabbi?"  
He answered, "You have said so."  

While they were eating,  
Jesus took bread, said the blessing,  
broke it, and giving it to his disciples said,  
"Take and eat; this is my body."  
Then he took a cup, gave thanks, and gave it to them, saying,  
"Drink from it, all of you,  
for this is my blood of the covenant,  
which will be shed on behalf of many  
for the forgiveness of sins.  
I tell you, from now on I shall not drink this fruit of the vine  
until the day when I drink it with you new  
in the kingdom of my Father."  
Then, after singing a hymn,  
they went out to the Mount of Olives.  

Then Jesus said to them,  
"This night all of you will have your faith in me shaken,  
for it is written:  
*I will strike the shepherd,*  
*and the sheep of the flock will be dispersed*;  
but after I have been raised up,  
I shall go before you to Galilee."  
Peter said to him in reply,  
"Though all may have their faith in you shaken,  
mine will never be."  
Jesus said to him,  
"Amen, I say to you,  
this very night before the cock crows,  
you will deny me three times."  
Peter said to him,  
"Even though I should have to die with you,  
I will not deny you."  
And all the disciples spoke likewise.  

Then Jesus came with them to a place called Gethsemane,  
and he said to his disciples,  
"Sit here while I go over there and pray."  
He took along Peter and the two sons of Zebedee,  
and began to feel sorrow and distress.  
Then he said to them,  
"My soul is sorrowful even to death.  
Remain here and keep watch with me."  
He advanced a little and fell prostrate in prayer, saying,  
"My Father, if it is possible,  
let this cup pass from me;  
yet, not as I will, but as you will."  
When he returned to his disciples he found them asleep.  
He said to Peter,  
"So you could not keep watch with me for one hour?  
Watch and pray that you may not undergo the test.  
The spirit is willing, but the flesh is weak."  
Withdrawing a second time, he prayed again,  
"My Father, if it is not possible that this cup pass  
without my drinking it, your will be done!"  
Then he returned once more and found them asleep,  
for they could not keep their eyes open.  
He left them and withdrew again and prayed a third time,  
saying the same thing again.  
Then he returned to his disciples and said to them,  
"Are you still sleeping and taking your rest?  
Behold, the hour is at hand  
when the Son of Man is to be handed over to sinners.  
Get up, let us go.  
Look, my betrayer is at hand."  

While he was still speaking,  
Judas, one of the Twelve, arrived,  
accompanied by a large crowd, with swords and clubs,  
who had come from the chief priests and the elders  
of the people.  
His betrayer had arranged a sign with them, saying,  
"The man I shall kiss is the one; arrest him."  
Immediately he went over to Jesus and said,  
"Hail, Rabbi!" and he kissed him.  
Jesus answered him,  
"Friend, do what you have come for."  
Then stepping forward they laid hands on Jesus and arrested him.  
And behold, one of those who accompanied Jesus  
put his hand to his sword, drew it,  
and struck the high priest's servant, cutting off his ear.  
Then Jesus said to him,  
"Put your sword back into its sheath,  
for all who take the sword will perish by the sword.  
Do you think that I cannot call upon my Father  
and he will not provide me at this moment  
with more than twelve legions of angels?  
But then how would the Scriptures be fulfilled  
which say that it must come to pass in this way?"  
At that hour Jesus said to the crowds,  
"Have you come out as against a robber,  
with swords and clubs to seize me?  
Day after day I sat teaching in the temple area,  
yet you did not arrest me.  
But all this has come to pass  
that the writings of the prophets may be fulfilled."  
Then all the disciples left him and fled.  

Those who had arrested Jesus led him away  
to Caiaphas the high priest,  
where the scribes and the elders were assembled.  
Peter was following him at a distance  
as far as the high priest's courtyard,  
and going inside he sat down with the servants  
to see the outcome.  
The chief priests and the entire Sanhedrin  
kept trying to obtain false testimony against Jesus  
in order to put him to death,  
but they found none,  
though many false witnesses came forward.  
Finally two came forward who stated,  
"This man said, 'I can destroy the temple of God  
and within three days rebuild it.'"  
The high priest rose and addressed him,  
"Have you no answer?  
What are these men testifying against you?"  
But Jesus was silent.  
Then the high priest said to him,  
"I order you to tell us under oath before the living God  
whether you are the Christ, the Son of God."  
Jesus said to him in reply,  
"You have said so.  
But I tell you:  
From now on you will see 'the Son of Man  
seated at the right hand of the Power'  
and 'coming on the clouds of heaven.'"  
Then the high priest tore his robes and said,  
"He has blasphemed!  
What further need have we of witnesses?  
You have now heard the blasphemy;  
what is your opinion?"  
They said in reply,  
"He deserves to die!"  
Then they spat in his face and struck him,  
while some slapped him, saying,  
"Prophesy for us, Christ: who is it that struck you?"  

Now Peter was sitting outside in the courtyard.  
One of the maids came over to him and said,  
"You too were with Jesus the Galilean."  
But he denied it in front of everyone, saying,  
"I do not know what you are talking about!"  
As he went out to the gate, another girl saw him  
and said to those who were there,  
"This man was with Jesus the Nazorean."  
Again he denied it with an oath,  
"I do not know the man!"  
A little later the bystanders came over and said to Peter,  
"Surely you too are one of them;  
even your speech gives you away."  
At that he began to curse and to swear,  
"I do not know the man."  
And immediately a cock crowed.  
Then Peter remembered the word that Jesus had spoken:  
"Before the cock crows you will deny me three times."  
He went out and began to weep bitterly.  

When it was morning,  
all the chief priests and the elders of the people. 
took counsel against Jesus to put him to death.  
They bound him, led him away,  
and handed him over to Pilate, the governor.  

Then Judas, his betrayer, seeing that Jesus had been condemned,  
deeply regretted what he had done.  
He returned the thirty pieces of silver. 
to the chief priests and elders, saying,  
"I have sinned in betraying innocent blood."  
They said,  
"What is that to us?  
Look to it yourself."  
Flinging the money into the temple,  
he departed and went off and hanged himself.  
The chief priests gathered up the money, but said,  
"It is not lawful to deposit this in the temple treasury,  
for it is the price of blood."  
After consultation, they used it to buy the potter's field  
as a burial place for foreigners.  
That is why that field even today is called the Field of Blood.  
Then was fulfilled what had been said through Jeremiah  
the prophet,  
*And they took the thirty pieces of silver,*  
*the value of a man with a price on his head,*  
*a price set by some of the Israelites,*  
*and they paid it out for the potter's field*  
*just as the Lord had commanded me.*  

Now Jesus stood before the governor, and he questioned him,  
"Are you the king of the Jews?"  
Jesus said, "You say so."  
And when he was accused by the chief priests and elders,  
he made no answer.  
Then Pilate said to him,  
"Do you not hear how many things they are testifying against you?"  
But he did not answer him one word,  
so that the governor was greatly amazed.  

Now on the occasion of the feast  
the governor was accustomed to release to the crowd  
one prisoner whom they wished.  
And at that time they had a notorious prisoner called Barabbas.  
So when they had assembled, Pilate said to them,  
"Which one do you want me to release to you,  
Barabbas, or Jesus called Christ?"  
For he knew that it was out of envy  
that they had handed him over.  
While he was still seated on the bench,  
his wife sent him a message,  
"Have nothing to do with that righteous man.  
I suffered much in a dream today because of him."  
The chief priests and the elders persuaded the crowds  
to ask for Barabbas but to destroy Jesus.  
The governor said to them in reply,  
"Which of the two do you want me to release to you?"  
They answered, "Barabbas!"  
Pilate said to them,  
"Then what shall I do with Jesus called Christ?"  
They all said,  
"Let him be crucified!"  
But he said,  
"Why? What evil has he done?"  
They only shouted the louder,  
"Let him be crucified!"  
When Pilate saw that he was not succeeding at all,  
but that a riot was breaking out instead,  
he took water and washed his hands in the sight of the crowd,  
saying, "I am innocent of this man's blood.  
Look to it yourselves."  
And the whole people said in reply,  
"His blood be upon us and upon our children."  
Then he released Barabbas to them,  
but after he had Jesus scourged,  
he handed him over to be crucified.  

Then the soldiers of the governor took Jesus inside the praetorium  
and gathered the whole cohort around him.  
They stripped off his clothes  
and threw a scarlet military cloak about him.  
Weaving a crown out of thorns, they placed it on his head,  
and a reed in his right hand.  
And kneeling before him, they mocked him, saying,  
"Hail, King of the Jews!"  
They spat upon him and took the reed  
and kept striking him on the head.  
And when they had mocked him,  
they stripped him of the cloak,  
dressed him in his own clothes,  
and led him off to crucify him.  

As they were going out, they met a Cyrenian named Simon;  
this man they pressed into service  
to carry his cross.  

And when they came to a place called Golgotha  
—which means Place of the Skull —,  
they gave Jesus wine to drink mixed with gall.  
But when he had tasted it, he refused to drink.  
After they had crucified him,  
they divided his garments by casting lots;  
then they sat down and kept watch over him there.  
And they placed over his head the written charge against him:  
This is Jesus, the King of the Jews.  
Two revolutionaries were crucified with him,  
one on his right and the other on his left.  
Those passing by reviled him, shaking their heads and saying,  
"You who would destroy the temple and rebuild it in three days,  
save yourself, if you are the Son of God,  
and come down from the cross!"  
Likewise the chief priests with the scribes and elders mocked him and said,  
"He saved others; he cannot save himself.  
So he is the king of Israel!  
Let him come down from the cross now,  
and we will believe in him.  
He trusted in God;  
let him deliver him now if he wants him.  
For he said, 'I am the Son of God.'"  
The revolutionaries who were crucified with him  
also kept abusing him in the same way.  

From noon onward, darkness came over the whole land  
until three in the afternoon.  
And about three o'clock Jesus cried out in a loud voice,  
*"Eli, Eli, lema sabachthani?"*  
which means, "My God, my God, why have you forsaken me?"  
Some of the bystanders who heard it said,  
"This one is calling for Elijah."  
Immediately one of them ran to get a sponge;  
he soaked it in wine, and putting it on a reed,  
gave it to him to drink.  
But the rest said,  
"Wait, let us see if Elijah comes to save him."  
But Jesus cried out again in a loud voice,  
and gave up his spirit.  

[*Here all kneel and pause for a short time.*]{.red}  

And behold, the veil of the sanctuary  
was torn in two from top to bottom.  
The earth quaked, rocks were split, tombs were opened,  
and the bodies of many saints who had fallen asleep were raised.  
And coming forth from their tombs after his resurrection,  
they entered the holy city and appeared to many.  
The centurion and the men with him who were keeping watch over Jesus  
feared greatly when they saw the earthquake  
and all that was happening, and they said,  
"Truly, this was the Son of God!"  
There were many women there, looking on from a distance,  
who had followed Jesus from Galilee, ministering to him.  
Among them were Mary Magdalene and Mary the mother of James and Joseph,  
and the mother of the sons of Zebedee.  

When it was evening,  
there came a rich man from Arimathea named Joseph,  
who was himself a disciple of Jesus.  
He went to Pilate and asked for the body of Jesus;  
then Pilate ordered it to be handed over.  
Taking the body, Joseph wrapped it in clean linen  
and laid it in his new tomb that he had hewn in the rock.  
Then he rolled a huge stone across the entrance to the tomb
and departed.  
But Mary Magdalene and the other Mary  
remained sitting there, facing the tomb.  

The next day, the one following the day of preparation,  
the chief priests and the Pharisees  
gathered before Pilate and said,  
"Sir, we remember that this impostor while still alive said,  
'After three days I will be raised up.'  
Give orders, then, that the grave be secured until the third day,  
lest his disciples come and steal him and say to the people,  
'He has been raised from the dead.'  
This last imposture would be worse than the first."  
Pilate said to them,  
"The guard is yours;  
go, secure it as best you can."  
So they went and secured the tomb  
by fixing a seal to the stone and setting the guard.   

[Or:]{.red}

Jesus stood before the governor, Pontius Pilate, who questioned him,  
"Are you the king of the Jews?"  
Jesus said, "You say so."  
And when he was accused by the chief priests and elders,  
he made no answer.  
Then Pilate said to him,  
"Do you not hear how many things they are testifying against you?"  
But he did not answer him one word,  
so that the governor was greatly amazed.  

Now on the occasion of the feast  
the governor was accustomed to release to the crowd  
one prisoner whom they wished.  
And at that time they had a notorious prisoner called Barabbas.  
So when they had assembled, Pilate said to them,  
"Which one do you want me to release to you,  
Barabbas, or Jesus called Christ?"  
For he knew that it was out of envy  
that they had handed him over.  
While he was still seated on the bench,  
his wife sent him a message,  
"Have nothing to do with that righteous man.  
I suffered much in a dream today because of him."  
The chief priests and the elders persuaded the crowds  
to ask for Barabbas but to destroy Jesus.  
The governor said to them in reply,  
"Which of the two do you want me to release to you?"  
They answered, "Barabbas!"  
Pilate said to them,  
"Then what shall I do with Jesus called Christ?"  
They all said,  
"Let him be crucified!"  
But he said,  
"Why? What evil has he done?"  
They only shouted the louder,  
"Let him be crucified!"  
When Pilate saw that he was not succeeding at all,  
but that a riot was breaking out instead,  
he took water and washed his hands in the sight of the crowd,  
saying, "I am innocent of this man's blood.  
Look to it yourselves."  
And the whole people said in reply,  
"His blood be upon us and upon our children."  
Then he released Barabbas to them,  
but after he had Jesus scourged,  
he handed him over to be crucified.  

Then the soldiers of the governor took Jesus inside the praetorium  
and gathered the whole cohort around him.  
They stripped off his clothes  
and threw a scarlet military cloak about him.  
Weaving a crown out of thorns, they placed it on his head,  
and a reed in his right hand.  
And kneeling before him, they mocked him, saying,  
"Hail, King of the Jews!"  
They spat upon him and took the reed  
and kept striking him on the head.  
And when they had mocked him,  
they stripped him of the cloak,  
dressed him in his own clothes,  
and led him off to crucify him.  

As they were going out, they met a Cyrenian named Simon;  
this man they pressed into service  
to carry his cross.  

And when they came to a place called Golgotha. 
— which means Place of the Skull —,  
they gave Jesus wine to drink mixed with gall.  
But when he had tasted it, he refused to drink.  
After they had crucified him,  
they divided his garments by casting lots;  
then they sat down and kept watch over him there.  
And they placed over his head the written charge against him:  
This is Jesus, the King of the Jews.  
Two revolutionaries were crucified with him,  
one on his right and the other on his left.  
Those passing by reviled him, shaking their heads and saying,  
"You who would destroy the temple and rebuild it in three days,  
save yourself, if you are the Son of God,  
and come down from the cross!"  
Likewise the chief priests with the scribes and elders mocked him and said,  
"He saved others; he cannot save himself.  
So he is the king of Israel!  
Let him come down from the cross now,  
and we will believe in him.  
He trusted in God;  
let him deliver him now if he wants him.  
For he said, 'I am the Son of God.'"  
The revolutionaries who were crucified with him. 
also kept abusing him in the same way.  

From noon onward, darkness came over the whole land  
until three in the afternoon.  
And about three o'clock Jesus cried out in a loud voice,  
*"Eli, Eli, lema sabachthani?"*  
which means, "My God, my God, why have you forsaken me?"  
Some of the bystanders who heard it said,  
"This one is calling for Elijah."  
Immediately one of them ran to get a sponge;  
he soaked it in wine, and putting it on a reed,  
gave it to him to drink.  
But the rest said,  
'Wait, let us see if Elijah comes to save him."  
But Jesus cried out again in a loud voice,  
and gave up his spirit.  

[*Here all kneel and pause for a short time.*]{.red}  

And behold, the veil of the sanctuary  
was torn in two from top to bottom.  
The earth quaked, rocks were split, tombs were opened,  
and the bodies of many saints who had fallen asleep were raised.  
And coming forth from their tombs after his resurrection,  
they entered the holy city and appeared to many.  
The centurion and the men with him who were keeping watch over Jesus  
feared greatly when they saw the earthquake  
and all that was happening, and they said,  
"Truly, this was the Son of God!"  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### At the Procession with Palms - Gospel [Mark 11:1-10]{style="float:right" .small}
:::

When Jesus and his disciples drew near to Jerusalem,  
to Bethphage and Bethany at the Mount of Olives,  
he sent two of his disciples and said to them,  
“Go into the village opposite you,  
and immediately on entering it,  
you will find a colt tethered on which no one has ever sat.  
Untie it and bring it here.  
If anyone should say to you,  
‘Why are you doing this?’ reply,  
‘The Master has need of it  
and will send it back here at once.’”  
So they went off  
and found a colt tethered at a gate outside on the street,  
and they untied it.  
Some of the bystanders said to them,  
“What are you doing, untying the colt?”  
They answered them just as Jesus had told them to,  
and they permitted them to do it.  
So they brought the colt to Jesus  
and put their cloaks over it.  
And he sat on it.  
Many people spread their cloaks on the road,  
and others spread leafy branches  
that they had cut from the fields.  
Those preceding him as well as those following kept crying out:  
&emsp; “Hosanna!  
&emsp; &emsp; Blessed is he who comes in the name of the Lord!  
&emsp; &emsp; Blessed is the kingdom of our father David that is to come!  
&emsp; Hosanna in the highest!”  

[Or:]{.red} [John 12:12-16]{style="float:right" .small .red}

When the great crowd that had come to the feast heard  
that Jesus was coming to Jerusalem,  
they took palm branches and went out to meet him, and cried out:  
&emsp; “Hosanna!  
&emsp; “Blessed is he who comes in the name of the Lord,  
&emsp; &emsp; the king of Israel.”  
Jesus found an ass and sat upon it, as is written:  
&emsp; Fear no more, O daughter Zion;  
&emsp; see, your king comes, seated upon an ass’s colt.  
His disciples did not understand this at first,  
but when Jesus had been glorified  
they remembered that these things were written about him  
and that they had done this for him.  

:::{.red}
#### At the Mass - First Reading [Isaiah 50:4-7]{style="float:right" .small}
:::

The Lord GOD has given me  
&emsp; a well-trained tongue,  
that I might know how to speak to the weary  
&emsp; a word that will rouse them.  
Morning after morning  
&emsp; he opens my ear that I may hear;  
and I have not rebelled,  
&emsp; have not turned back.  
I gave my back to those who beat me,  
&emsp; my cheeks to those who plucked my beard;  
my face I did not shield  
&emsp; from buffets and spitting.  

The Lord GOD is my help,  
&emsp; therefore I am not disgraced;  
I have set my face like flint,  
&emsp; knowing that I shall not be put to shame.  

***

::: {.red}
#### Responsorial Psalm [Psalm 22:8-9, 17-18, 19-20, 23-24]{style="float:right" .small}
:::

**[℟.]{.red}** **My God, my God, why have you abandoned me?**  

All who see me scoff at me;  
&emsp; they mock me with parted lips, they wag their heads:  
“He relied on the LORD; let him deliver him,  
&emsp; let him rescue him, if he loves him.” **[℟.]{.red}**  

Indeed, many dogs surround me,  
&emsp; a pack of evildoers closes in upon me;  
They have pierced my hands and my feet;  
&emsp; I can count all my bones. **[℟.]{.red}**  

They divide my garments among them,  
&emsp; and for my vesture they cast lots.  
But you, O LORD, be not far from me;  
&emsp; O my help, hasten to aid me. **[℟.]{.red}**  

I will proclaim your name to my brethren;  
&emsp; in the midst of the assembly I will praise you:  
“You who fear the LORD, praise him;  
&emsp; all you descendants of Jacob, give glory to him;  
&emsp; revere him, all you descendants of Israel!” **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Philippians 2:6-11]{style="float:right" .small}
:::

Christ Jesus, though he was in the form of God,  
&emsp; did not regard equality with God  
&emsp; something to be grasped.  
Rather, he emptied himself,  
&emsp; taking the form of a slave,  
&emsp; coming in human likeness;  
&emsp; and found human in appearance,  
&emsp; he humbled himself,  
&emsp; becoming obedient to the point of death,  
&emsp; even death on a cross.  
Because of this, God greatly exalted him  
&emsp; and bestowed on him the name  
&emsp; which is above every name,  
&emsp; that at the name of Jesus  
&emsp; every knee should bend,  
&emsp; of those in heaven and on earth and under the earth,  
&emsp; and every tongue confess that  
&emsp; Jesus Christ is Lord,  
&emsp; to the glory of God the Father.  

***

::: {.red}
#### Gospel Acclamation [Philippians 2:8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
Christ became obedient to the point of death,  
even death on a cross.  
Because of this, God greatly exalted him  
and bestowed on him the name which is above every name. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Mark 14:1—15:47 or 15:1-39]{style="float:right" .small}
:::

The Passover and the Feast of Unleavened Bread  
were to take place in two days’ time.  
So the chief priests and the scribes were seeking a way  
to arrest him by treachery and put him to death.  
They said, “Not during the festival,  
for fear that there may be a riot among the people.”  

When he was in Bethany reclining at table  
in the house of Simon the leper,  
a woman came with an alabaster jar of perfumed oil,  
costly genuine spikenard.  
She broke the alabaster jar and poured it on his head.  
There were some who were indignant.  
“Why has there been this waste of perfumed oil?  
It could have been sold for more than three hundred days’ wages  
and the money given to the poor.”  
They were infuriated with her.  
Jesus said, “Let her alone.  
Why do you make trouble for her?  
She has done a good thing for me.  
The poor you will always have with you,  
and whenever you wish you can do good to them,  
but you will not always have me.  
She has done what she could.  
She has anticipated anointing my body for burial.  
Amen, I say to you,  
wherever the gospel is proclaimed to the whole world, 
what she has done will be told in memory of her.”  

Then Judas Iscariot, one of the Twelve,  
went off to the chief priests to hand him over to them.  
When they heard him they were pleased and promised to pay him money.  
Then he looked for an opportunity to hand him over.  

On the first day of the Feast of Unleavened Bread,  
when they sacrificed the Passover lamb,  
his disciples said to him,  
“Where do you want us to go  
and prepare for you to eat the Passover?”  
He sent two of his disciples and said to them,  
“Go into the city and a man will meet you,  
carrying a jar of water.  
Follow him.  
Wherever he enters, say to the master of the house,  
‘The Teacher says, “Where is my guest room  
where I may eat the Passover with my disciples?”’  
Then he will show you a large upper room furnished and ready.  
Make the preparations for us there.”  
The disciples then went off, entered the city,  
and found it just as he had told them;  
and they prepared the Passover.  

When it was evening, he came with the Twelve.  
And as they reclined at table and were eating, Jesus said,  
“Amen, I say to you, one of you will betray me,  
one who is eating with me.”  
They began to be distressed and to say to him, one by one,  
“Surely it is not I?”  
He said to them,  
“One of the Twelve, the one who dips with me into the dish.  
For the Son of Man indeed goes, as it is written of him,  
but woe to that man by whom the Son of Man is betrayed.  
It would be better for that man if he had never been born.”  

While they were eating,  
he took bread, said the blessing,  
broke it, and gave it to them, and said,  
“Take it; this is my body.”  
Then he took a cup, gave thanks, and gave it to them,  
and they all drank from it.  
He said to them,  
“This is my blood of the covenant,  
which will be shed for many.  
Amen, I say to you,  
I shall not drink again the fruit of the vine  
until the day when I drink it new in the kingdom of God.”  
Then, after singing a hymn,  
they went out to the Mount of Olives.  

Then Jesus said to them,  
“All of you will have your faith shaken, for it is written:  
&emsp; *I will strike the shepherd,*  
&emsp; &emsp; *and the sheep will be dispersed.*  
But after I have been raised up,  
I shall go before you to Galilee.”  
Peter said to him,  
“Even though all should have their faith shaken,  
mine will not be.”  
Then Jesus said to him,  
"Amen, I say to you,  
this very night before the cock crows twice  
you will deny me three times.”  
But he vehemently replied,  
“Even though I should have to die with you,  
I will not deny you.”  
And they all spoke similarly.  

Then they came to a place named Gethsemane,  
and he said to his disciples,  
“Sit here while I pray.”  
He took with him Peter, James, and John,  
and began to be troubled and distressed.  
Then he said to them, “My soul is sorrowful even to death.  
Remain here and keep watch.”  
He advanced a little and fell to the ground and prayed  
that if it were possible the hour might pass by him;  
he said, “Abba, Father, all things are possible to you.  
Take this cup away from me,  
but not what I will but what you will.”  
When he returned he found them asleep.  
He said to Peter, “Simon, are you asleep?  
Could you not keep watch for one hour?  
Watch and pray that you may not undergo the test.  
The spirit is willing but the flesh is weak.”  
Withdrawing again, he prayed, saying the same thing.  
Then he returned once more and found them asleep,  
for they could not keep their eyes open  
and did not know what to answer him.  
He returned a third time and said to them,  
“Are you still sleeping and taking your rest?  
It is enough. The hour has come.  
Behold, the Son of Man is to be handed over to sinners.  
Get up, let us go.  
See, my betrayer is at hand.”  

Then, while he was still speaking,  
Judas, one of the Twelve, arrived,  
accompanied by a crowd with swords and clubs  
who had come from the chief priests,  
the scribes, and the elders.  
His betrayer had arranged a signal with them, saying,  
“The man I shall kiss is the one;  
arrest him and lead him away securely.”  
He came and immediately went over to him and said,  
“Rabbi.”  And he kissed him.  
At this they laid hands on him and arrested him.  
One of the bystanders drew his sword,  
struck the high priest’s servant, and cut off his ear.  
Jesus said to them in reply,  
“Have you come out as against a robber,  
with swords and clubs, to seize me?  
Day after day I was with you teaching in the temple area,  
yet you did not arrest me;  
but that the Scriptures may be fulfilled.”  
And they all left him and fled.  
Now a young man followed him  
wearing nothing but a linen cloth about his body.  
They seized him,  
but he left the cloth behind and ran off naked.  

They led Jesus away to the high priest,  
and all the chief priests and the elders and the scribes came together.  
Peter followed him at a distance into the high priest’s courtyard  
and was seated with the guards, warming himself at the fire.  
The chief priests and the entire Sanhedrin  
kept trying to obtain testimony against Jesus  
in order to put him to death, but they found none.  
Many gave false witness against him,  
but their testimony did not agree.  
Some took the stand and testified falsely against him,  
alleging, “We heard him say,  
‘I will destroy this temple made with hands  
and within three days I will build another  
not made with hands.’”  
Even so their testimony did not agree.  
The high priest rose before the assembly and questioned Jesus,  
saying, “Have you no answer?  
What are these men testifying against you?”  
But he was silent and answered nothing.  
Again the high priest asked him and said to him,  
“Are you the Christ, the son of the Blessed One?”  
Then Jesus answered, “I am;  
and ‘you will see the Son of Man  
seated at the right hand of the Power  
and coming with the clouds of heaven.’”  
At that the high priest tore his garments and said,  
“What further need have we of witnesses?  
You have heard the blasphemy.  
What do you think?”  
They all condemned him as deserving to die.  
Some began to spit on him.  
They blindfolded him and struck him and said to him, “Prophesy!”  
And the guards greeted him with blows.  

While Peter was below in the courtyard,  
one of the high priest’s maids came along.  
Seeing Peter warming himself,  
she looked intently at him and said,  
“You too were with the Nazarene, Jesus.”  
But he denied it saying,  
“I neither know nor understand what you are talking about.”  
So he went out into the outer court.  
Then the cock crowed.  
The maid saw him and began again to say to the bystanders,  
“This man is one of them.”  
Once again he denied it.  
A little later the bystanders said to Peter once more,  
“Surely you are one of them; for you too are a Galilean.”  
He began to curse and to swear,  
“I do not know this man about whom you are talking.”  
And immediately a cock crowed a second time.  
Then Peter remembered the word that Jesus had said to him,  
“Before the cock crows twice you will deny me three times.”  
He broke down and wept.  

As soon as morning came,  
the chief priests with the elders and the scribes,  
that is, the whole Sanhedrin held a council.  
They bound Jesus, led him away, and handed him over to Pilate.  
Pilate questioned him,  
“Are you the king of the Jews?”  
He said to him in reply, “You say so.”  
The chief priests accused him of many things.  
Again Pilate questioned him,  
“Have you no answer?  
See how many things they accuse you of.”  
Jesus gave him no further answer, so that Pilate was amazed.  

Now on the occasion of the feast he used to release to them  
one prisoner whom they requested.  
A man called Barabbas was then in prison  
along with the rebels who had committed murder in a rebellion.  
The crowd came forward and began to ask him  
to do for them as he was accustomed.  
Pilate answered,  
“Do you want me to release to you the king of the Jews?”  
For he knew that it was out of envy  
that the chief priests had handed him over.  
But the chief priests stirred up the crowd  
to have him release Barabbas for them instead.  
Pilate again said to them in reply,  
“Then what do you want me to do  
with the man you call the king of the Jews?”  
They shouted again, “Crucify him.”  
Pilate said to them, “Why?  What evil has he done?”  
They only shouted the louder, “Crucify him.”  
So Pilate, wishing to satisfy the crowd,  
released Barabbas to them and, after he had Jesus scourged,  
handed him over to be crucified.  

The soldiers led him away inside the palace,  
that is, the praetorium, and assembled the whole cohort.  
They clothed him in purple and,  
weaving a crown of thorns, placed it on him.  
They began to salute him with, "Hail, King of the Jews!”  
and kept striking his head with a reed and spitting upon him.  
They knelt before him in homage.  
And when they had mocked him,  
they stripped him of the purple cloak,  
dressed him in his own clothes,  
and led him out to crucify him.  

They pressed into service a passer-by, Simon,  
a Cyrenian, who was coming in from the country,  
the father of Alexander and Rufus,  
to carry his cross.  

They brought him to the place of Golgotha  
— which is translated Place of the Skull —,  
They gave him wine drugged with myrrh,  
but he did not take it.  
Then they crucified him and divided his garments  
by casting lots for them to see what each should take.  
It was nine o’clock in the morning when they crucified him.  
The inscription of the charge against him read,  
“The King of the Jews.”  
With him they crucified two revolutionaries,  
one on his right and one on his left.  
Those passing by reviled him,  
shaking their heads and saying,  
“Aha!  You who would destroy the temple  
and rebuild it in three days,  
save yourself by coming down from the cross.”  
Likewise the chief priests, with the scribes,  
mocked him among themselves and said,  
“He saved others; he cannot save himself.  
Let the Christ, the King of Israel,  
come down now from the cross  
that we may see and believe.”  
Those who were crucified with him also kept abusing him.  

At noon darkness came over the whole land  
until three in the afternoon.  
And at three o’clock Jesus cried out in a loud voice,  
*“Eloi, Eloi, lema sabachthani?”*  
which is translated,  
“My God, my God, why have you forsaken me?”  
Some of the bystanders who heard it said,  
“Look, he is calling Elijah.”  
One of them ran, soaked a sponge with wine, put it on a reed  
and gave it to him to drink saying,  
“Wait, let us see if Elijah comes to take him down.”  
Jesus gave a loud cry and breathed his last.  

[*Here all kneel and pause for a short time.*]{.red}  

The veil of the sanctuary was torn in two from top to bottom.  
When the centurion who stood facing him  
saw how he  breathed his last he said,  
“Truly this man was the Son of God!”  
There were also women looking on from a distance.  
Among them were Mary Magdalene,  
Mary the mother of the younger James and of Joses, and Salome.  
These women had followed him when he was in Galilee  
and ministered to him.  
There were also many other women  
who had come up with him to Jerusalem.  

When it was already evening,  
since it was the day of preparation,  
the day before the sabbath, Joseph of Arimathea,  
a distinguished member of the council,  
who was himself awaiting the kingdom of God,  
came and courageously went to Pilate  
and asked for the body of Jesus.  
Pilate was amazed that he was already dead.  
He summoned the centurion  
and asked him if Jesus had already died.  
And when he learned of it from the centurion,  
he gave the body to Joseph.  
Having bought a linen cloth, he took him down,  
wrapped him in the linen cloth,  
and laid him in a tomb that had been hewn out of the rock.  
Then he rolled a stone against the entrance to the tomb.  
Mary Magdalene and Mary the mother of Joses  
watched where he was laid.  

[Or:]{.red}  

As soon as morning came,  
the chief priests with the elders and the scribes,  
that is, the whole Sanhedrin held a council.  
They bound Jesus, led him away, and handed him over to Pilate.  
Pilate questioned him,  
“Are you the king of the Jews?”  
He said to him in reply, “You say so.”  
The chief priests accused him of many things.  
Again Pilate questioned him,  
“Have you no answer?  
See how many things they accuse you of.”  
Jesus gave him no further answer, so that Pilate was amazed.  

Now on the occasion of the feast he used to release to them  
one prisoner whom they requested.  
A man called Barabbas was then in prison  
along with the rebels who had committed murder in a rebellion.  
The crowd came forward and began to ask him  
to do for them as he was accustomed.  
Pilate answered,  
“Do you want me to release to you the king of the Jews?”  
For he knew that it was out of envy  
that the chief priests had handed him over.  
But the chief priests stirred up the crowd  
to have him release Barabbas for them instead.  
Pilate again said to them in reply,  
“Then what do you want me to do  
with the man you call the king of the Jews?”  
They shouted again, “Crucify him.”  
Pilate said to them, “Why?  What evil has he done?”  
They only shouted the louder, “Crucify him.”  
So Pilate, wishing to satisfy the crowd,  
released Barabbas to them and, after he had Jesus scourged,  
handed him over to be crucified.  

The soldiers led him away inside the palace,  
that is, the praetorium, and assembled the whole cohort.  
They clothed him in purple and,  
weaving a crown of thorns, placed it on him.  
They began to salute him with, “Hail, King of the Jews!”  
and kept striking his head with a reed and spitting upon him.  
They knelt before him in homage.  
And when they had mocked him,  
they stripped him of the purple cloak,  
dressed him in his own clothes,  
and led him out to crucify him.  

They pressed into service a passer-by, Simon,  
a Cyrenian, who was coming in from the country,  
the father of Alexander and Rufus,  
to carry his cross.  

They brought him to the place of Golgotha  
—which is translated Place of the Skull.  
They gave him wine drugged with myrrh,  
but he did not take it.  
Then they crucified him and divided his garments  
by casting lots for them to see what each should take.  
It was nine o’clock in the morning when they crucified him.  
The inscription of the charge against him read,  
“The King of the Jews.”  
With him they crucified two revolutionaries,  
one on his right and one on his left.  
Those passing by reviled him,  
shaking their heads and saying,  
“Aha!  You who would destroy the temple  
and rebuild it in three days,  
save yourself by coming down from the cross.”  
Likewise the chief priests, with the scribes,  
mocked him among themselves and said,  
“He saved others; he cannot save himself.  
Let the Christ, the King of Israel,  
come down now from the cross  
that we may see and believe.”  
Those who were crucified with him also kept abusing him.  

At noon darkness came over the whole land  
until three in the afternoon.  
And at three o’clock Jesus cried out in a loud voice,  
*“Eloi, Eloi, lema sabachthani?”*  
which is translated,  
“My God, my God, why have you forsaken me?”  
Some of the bystanders who heard it said,  
“Look, he is calling Elijah.”  
One of them ran, soaked a sponge with wine, put it on a reed  
and gave it to him to drink saying,  
“Wait, let us see if Elijah comes to take him down.”  
Jesus gave a loud cry and breathed his last.  

[*Here all kneel and pause for a short time.*]{.red}  

The veil of the sanctuary was torn in two from top to bottom.  
When the centurion who stood facing him  
saw how he breathed his last he said,  
“Truly this man was the Son of God!”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### At the Procession with Palms - Gospel [Luke 19:28-40]{style="float:right" .small}
:::

Jesus proceeded on his journey up to Jerusalem.  
As he drew near to Bethphage and Bethany  
at the place called the Mount of Olives,  
he sent two of his disciples.  
He said, “Go into the village opposite you,  
and as you enter it you will find a colt tethered  
on which no one has ever sat.  
Untie it and bring it here.  
And if anyone should ask you,  
‘Why are you untying it?’  
you will answer,  
‘The Master has need of it.’”  
So those who had been sent went off  
and found everything just as he had told them.  
And as they were untying the colt, its owners said to them,  
“Why are you untying this colt?”  
They answered,  
“The Master has need of it.”  
So they brought it to Jesus,  
threw their cloaks over the colt,  
and helped Jesus to mount.  
As he rode along,  
the people were spreading their cloaks on the road;  
and now as he was approaching the slope of the Mount of Olives,  
the whole multitude of his disciples  
began to praise God aloud with joy  
for all the mighty deeds they had seen.  
They proclaimed:  
&emsp; “Blessed is the king who comes  
&emsp; &emsp; in the name of the Lord.  
&emsp; Peace in heaven  
&emsp; &emsp; and glory in the highest.”  
Some of the Pharisees in the crowd said to him,  
“Teacher, rebuke your disciples.”  
He said in reply,  
“I tell you, if they keep silent,  
the stones will cry out!”  

:::{.red}
#### At the Mass - First Reading [Isaiah 50:4-7]{style="float:right" .small}
:::

The Lord GOD has given me  
&emsp; a well-trained tongue,  
that I might know how to speak to the weary  
&emsp; a word that will rouse them.  
Morning after morning  
&emsp; he opens my ear that I may hear;  
and I have not rebelled,  
&emsp; have not turned back.  
I gave my back to those who beat me,  
&emsp; my cheeks to those who plucked my beard;  
my face I did not shield  
&emsp; from buffets and spitting.  

The Lord GOD is my help,  
&emsp; therefore I am not disgraced;  
I have set my face like flint,  
&emsp; knowing that I shall not be put to shame.  

***

::: {.red}
#### Responsorial Psalm [Psalm 22:8-9, 17-18, 19-20, 23-24]{style="float:right" .small}
:::

**[℟.]{.red}** **My God, my God, why have you abandoned me?**  

All who see me scoff at me;  
&emsp; they mock me with parted lips, they wag their heads:  
“He relied on the LORD; let him deliver him,  
&emsp; let him rescue him, if he loves him.” **[℟.]{.red}**  

Indeed, many dogs surround me,  
&emsp; a pack of evildoers closes in upon me;  
They have pierced my hands and my feet;  
&emsp; I can count all my bones. **[℟.]{.red}**  

They divide my garments among them,  
&emsp; and for my vesture they cast lots.  
But you, O LORD, be not far from me;  
&emsp; O my help, hasten to aid me. **[℟.]{.red}**  

I will proclaim your name to my brethren;  
&emsp; in the midst of the assembly I will praise you:  
“You who fear the LORD, praise him;  
&emsp; all you descendants of Jacob, give glory to him;  
&emsp; revere him, all you descendants of Israel!” **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Philippians 2:6-11]{style="float:right" .small}
:::

Christ Jesus, though he was in the form of God,  
&emsp; did not regard equality with God  
&emsp; something to be grasped.  
Rather, he emptied himself,  
&emsp; taking the form of a slave,  
&emsp; coming in human likeness;  
&emsp; and found human in appearance,  
&emsp; he humbled himself,  
&emsp; becoming obedient to the point of death,  
&emsp; even death on a cross.  
Because of this, God greatly exalted him  
&emsp; and bestowed on him the name  
&emsp; which is above every name,  
&emsp; that at the name of Jesus  
&emsp; every knee should bend,  
&emsp; of those in heaven and on earth and under the earth,  
&emsp; and every tongue confess that  
&emsp; Jesus Christ is Lord,  
&emsp; to the glory of God the Father.  

***

::: {.red}
#### Gospel Acclamation [Philippians 2:8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
Christ became obedient to the point of death,  
even death on a cross.  
Because of this, God greatly exalted him  
and bestowed on him the name which is above every name. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Luke 22:14—23:56 or 23:1-49]{style="float:right" .small}
:::

When the hour came,  
Jesus took his place at table with the apostles.  
He said to them,  
“I have eagerly desired to eat this Passover with you before I suffer,  
for, I tell you, I shall not eat it again  
until there is fulfillment in the kingdom of God.”  
Then he took a cup, gave thanks, and said,  
“Take this and share it among yourselves;  
for I tell you that from this time on  
I shall not drink of the fruit of the vine  
until the kingdom of God comes.”  
Then he took the bread, said the blessing,  
broke it, and gave it to them, saying,  
“This is my body, which will be given for you;  
do this in memory of me.”  
And likewise the cup after they had eaten, saying,  
“This cup is the new covenant in my blood,  
which will be shed for you.  

“And yet behold, the hand of the one who is to betray me  
is with me on the table;  
for the Son of Man indeed goes as it has been determined;  
but woe to that man by whom he is betrayed.”  
And they began to debate among themselves  
who among them would do such a deed.

Then an argument broke out among them  
about which of them should be regarded as the greatest.  
He said to them,  
“The kings of the Gentiles lord it over them  
and those in authority over them are addressed as ‘Benefactors’;  
but among you it shall not be so.  
Rather, let the greatest among you be as the youngest,  
and the leader as the servant.  
For who is greater:  
the one seated at table or the one who serves?  
Is it not the one seated at table?  
I am among you as the one who serves.  
It is you who have stood by me in my trials;  
and I confer a kingdom on you,  
just as my Father has conferred one on me,  
that you may eat and drink at my table in my kingdom;  
and you will sit on thrones  
judging the twelve tribes of Israel.  

“Simon, Simon, behold Satan has demanded  
to sift all of you like wheat,  
but I have prayed that your own faith may not fail;  
and once you have turned back,  
you must strengthen your brothers.”  
He said to him,  
“Lord, I am prepared to go to prison and to die with you.”  
But he replied,  
“I tell you, Peter, before the cock crows this day,  
you will deny three times that you know me.”  

He said to them,  
“When I sent you forth without a money bag or a sack or sandals,  
were you in need of anything?”  
“No, nothing, “ they replied.  
He said to them,  
“But now one who has a money bag should take it,  
and likewise a sack,  
and one who does not have a sword  
should sell his cloak and buy one.  
For I tell you that this Scripture must be fulfilled in me,  
namely, *He was counted among the wicked*;  
and indeed what is written about me is coming to fulfillment.”  
Then they said,  
“Lord, look, there are two swords here.”  
But he replied, “It is enough!”  

Then going out, he went, as was his custom, to the Mount of Olives,  
and the disciples followed him.  
When he arrived at the place he said to them,  
“Pray that you may not undergo the test.”  
After withdrawing about a stone’s throw from them and kneeling,  
he prayed, saying, “Father, if you are willing,  
take this cup away from me;  
still, not my will but yours be done.”  
And to strengthen him an angel from heaven appeared to him.  
He was in such agony and he prayed so fervently  
that his sweat became like drops of blood  
falling on the ground.  
When he rose from prayer and returned to his disciples,  
he found them sleeping from grief.  
He said to them, “Why are you sleeping?  
Get up and pray that you may not undergo the test.”  

While he was still speaking, a crowd approached  
and in front was one of the Twelve, a man named Judas.  
He went up to Jesus to kiss him.  
Jesus said to him,  
“Judas, are you betraying the Son of Man with a kiss?”  
His disciples realized what was about to happen, and they asked,  
“Lord, shall we strike with a sword?”  
And one of them struck the high priest’s servant  
and cut off his right ear.  
But Jesus said in reply,  
“Stop, no more of this!”  
Then he touched the servant’s ear and healed him.  
And Jesus said to the chief priests and temple guards  
and elders who had come for him,  
“Have you come out as against a robber, with swords and clubs?  
Day after day I was with you in the temple area,  
and you did not seize me;  
but this is your hour, the time for the power of darkness.”  

After arresting him they led him away  
and took him into the house of the high priest;  
Peter was following at a distance.  
They lit a fire in the middle of the courtyard and sat around it,  
and Peter sat down with them.  
When a maid saw him seated in the light,  
she looked intently at him and said,  
“This man too was with him.”  
But he denied it saying,  
“Woman, I do not know him.”  
A short while later someone else saw him and said,  
“You too are one of them”;  
but Peter answered, “My friend, I am not.”  
About an hour later, still another insisted,  
“Assuredly, this man too was with him,  
for he also is a Galilean.”  
But Peter said,  
“My friend, I do not know what you are talking about.”  
Just as he was saying this, the cock crowed,  
and the Lord turned and looked at Peter;  
and Peter remembered the word of the Lord,  
how he had said to him,  
“Before the cock crows today, you will deny me three times.”  
He went out and began to weep bitterly.  
The men who held Jesus in custody were ridiculing and beating him.  
They blindfolded him and questioned him, saying,  
“Prophesy!  Who is it that struck you?”  
And they reviled him in saying many other things against him.  

When day came the council of elders of the people met,  
both chief priests and scribes,  
and they brought him before their Sanhedrin.  
They said, “If you are the Christ, tell us,“  
but he replied to them, “If I tell you, you will not believe,  
and if I question, you will not respond.  
But from this time on the Son of Man will be seated  
at the right hand of the power of God.”  
They all asked, “Are you then the Son of God?”  
He replied to them, “You say that I am.”  
Then they said, “What further need have we for testimony?  
We have heard it from his own mouth.”  

Then the whole assembly of them arose and brought him before Pilate.  
They brought charges against him, saying,  
“We found this man misleading our people;  
he opposes the payment of taxes to Caesar  
and maintains that he is the Christ, a king.”  
Pilate asked him, “Are you the king of the Jews?”  
He said to him in reply, “You say so.”  
Pilate then addressed the chief priests and the crowds,  
“I find this man not guilty.”  
But they were adamant and said,  
“He is inciting the people with his teaching throughout all Judea,  
from Galilee where he began even to here.”  

On hearing this Pilate asked if the man was a Galilean;  
and upon learning that he was under Herod’s jurisdiction,  
he sent him to Herod who was in Jerusalem at that time.  
Herod was very glad to see Jesus;  
he had been wanting to see him for a long time,  
for he had heard about him  
and had been hoping to see him perform some sign.  
He questioned him at length,  
but he gave him no answer.  
The chief priests and scribes, meanwhile,  
stood by accusing him harshly.  
Herod and his soldiers treated him contemptuously and mocked him,  
and after clothing him in resplendent garb,  
he sent him back to Pilate.  
Herod and Pilate became friends that very day,  
even though they had been enemies formerly.  
Pilate then summoned the chief priests, the rulers, and the people  
and said to them, “You brought this man to me  
and accused him of inciting the people to revolt.  
I have conducted my investigation in your presence  
and have not found this man guilty  
of the charges you have brought against him,  
nor did Herod, for he sent him back to us.  
So no capital crime has been committed by him.  
Therefore I shall have him flogged and then release him.”  

But all together they shouted out,  
“Away with this man!  
Release Barabbas to us.”  
— Now Barabbas had been imprisoned for a rebellion  
that had taken place in the city and for murder. —  
Again Pilate addressed them, still wishing to release Jesus,  
but they continued their shouting,  
“Crucify him!  Crucify him!”  
Pilate addressed them a third time,  
“What evil has this man done?  
I found him guilty of no capital crime.  
Therefore I shall have him flogged and then release him.”  
With loud shouts, however,  
they persisted in calling for his crucifixion,  
and their voices prevailed.  
The verdict of Pilate was that their demand should be granted.  
So he released the man who had been imprisoned  
for rebellion and murder, for whom they asked,  
and he handed Jesus over to them to deal with as they wished.  

As they led him away  
they took hold of a certain Simon, a Cyrenian,  
who was coming in from the country;  
and after laying the cross on him,  
they made him carry it behind Jesus.  
A large crowd of people followed Jesus,  
including many women who mourned and lamented him.  
Jesus turned to them and said,  
“Daughters of Jerusalem, do not weep for me;  
weep instead for yourselves and for your children  
for indeed, the days are coming when people will say,  
‘Blessed are the barren,  
the wombs that never bore  
and the breasts that never nursed.’  
At that time people will say to the mountains,  
‘Fall upon us!’  
and to the hills, ‘Cover us!’  
for if these things are done when the wood is green  
what will happen when it is dry?”  
Now two others, both criminals,  
were led away with him to be executed.  

When they came to the place called the Skull,  
they crucified him and the criminals there,  
one on his right, the other on his left.  
Then Jesus said,  
“Father, forgive them, they know not what they do.”  
They divided his garments by casting lots.  
The people stood by and watched;  
the rulers, meanwhile, sneered at him and said,  
“He saved others, let him save himself  
if he is the chosen one, the Christ of God.”  
Even the soldiers jeered at him.  
As they approached to offer him wine they called out,  
“If you are King of the Jews, save yourself.”  
Above him there was an inscription that read,  
“This is the King of the Jews.”  

Now one of the criminals hanging there reviled Jesus, saying,  
“Are you not the Christ?  
Save yourself and us.”  
The other, however, rebuking him, said in reply,  
“Have you no fear of God,  
for you are subject to the same condemnation?  
And indeed, we have been condemned justly,  
for the sentence we received corresponds to our crimes,  
but this man has done nothing criminal.”  
Then he said,  
“Jesus, remember me when you come into your kingdom.”  
He replied to him,  
“Amen, I say to you,  
today you will be with me in Paradise.”  

It was now about noon and darkness came over the whole land  
until three in the afternoon  
because of an eclipse of the sun.  
Then the veil of the temple was torn down the middle.  
Jesus cried out in a loud voice,  
“Father, into your hands I commend my spirit”;  
and when he had said this he breathed his last.  

[*Here all kneel and pause for a short time.*]{.red}  

The centurion who witnessed what had happened glorified God and said,  
“This man was innocent beyond doubt.”  
When all the people who had gathered for this spectacle saw what had happened,  
they returned home beating their breasts;  
but all his acquaintances stood at a distance,  
including the women who had followed him from Galilee  
and saw these events.  
Now there was a virtuous and righteous man named Joseph who,  
though he was a member of the council,  
had not consented to their plan of action.  
He came from the Jewish town of Arimathea  
and was awaiting the kingdom of God.  
He went to Pilate and asked for the body of Jesus.  
After he had taken the body down,  
he wrapped it in a linen cloth  
and laid him in a rock-hewn tomb  
in which no one had yet been buried.  
It was the day of preparation,  
and the sabbath was about to begin.  
The women who had come from Galilee with him followed behind,  
and when they had seen the tomb  
and the way in which his body was laid in it,  
they returned and prepared spices and perfumed oils.  
Then they rested on the sabbath according to the commandment.  

[Or:]{.red}  

The elders of the people, chief priests and scribes,  
arose and brought Jesus before Pilate.  
They brought charges against him, saying,  
“We found this man misleading our people;  
he opposes the payment of taxes to Caesar  
and maintains that he is the Christ, a king.”  
Pilate asked him, “Are you the king of the Jews?”  
He said to him in reply, “You say so.”  
Pilate then addressed the chief priests and the crowds,  
“I find this man not guilty.”  
But they were adamant and said,  
“He is inciting the people with his teaching throughout all Judea,  
from Galilee where he began even to here.”  

On hearing this Pilate asked if the man was a Galilean;  
and upon learning that he was under Herod’s jurisdiction,  
he sent him to Herod who was in Jerusalem at that time.  
Herod was very glad to see Jesus;  
he had been wanting to see him for a long time,  
for he had heard about him  
and had been hoping to see him perform some sign.  
He questioned him at length,  
but he gave him no answer.  
The chief priests and scribes, meanwhile,  
stood by accusing him harshly.  
Herod and his soldiers treated him contemptuously and mocked him,  
and after clothing him in resplendent garb,  
he sent him back to Pilate.  
Herod and Pilate became friends that very day,  
even though they had been enemies formerly.  
Pilate then summoned the chief priests, the rulers, and the people. 
and said to them, “You brought this man to me  
and accused him of inciting the people to revolt.  
I have conducted my investigation in your presence  
and have not found this man guilty  
of the charges you have brought against him,  
nor did Herod, for he sent him back to us.  
So no capital crime has been committed by him.  
Therefore I shall have him flogged and then release him.”  

But all together they shouted out,  
“Away with this man!  
Release Barabbas to us.”  
— Now Barabbas had been imprisoned for a rebellion  
that had taken place in the city and for murder. —  
Again Pilate addressed them, still wishing to release Jesus,  
but they continued their shouting,  
“Crucify him! Crucify him!”  
Pilate addressed them a third time,  
“What evil has this man done?  
I found him guilty of no capital crime.  
Therefore I shall have him flogged and then release him.”  
With loud shouts, however,  
they persisted in calling for his crucifixion,  
and their voices prevailed.  
The verdict of Pilate was that their demand should be granted.  
So he released the man who had been imprisoned  
for rebellion and murder, for whom they asked,  
and he handed Jesus over to them to deal with as they wished.  

As they led him away  
they took hold of a certain Simon, a Cyrenian,  
who was coming in from the country;  
and after laying the cross on him,  
they made him carry it behind Jesus.  
A large crowd of people followed Jesus,  
including many women who mourned and lamented him.  
Jesus turned to them and said,  
“Daughters of Jerusalem, do not weep for me;  
weep instead for yourselves and for your children  
for indeed, the days are coming when people will say,  
‘Blessed are the barren,  
the wombs that never bore  
and the breasts that never nursed.’  
At that time people will say to the mountains,  
‘Fall upon us!’  
and to the hills, ‘Cover us!’  
for if these things are done when the wood is green  
what will happen when it is dry?”  
Now two others, both criminals,  
were led away with him to be executed.  

When they came to the place called the Skull,  
they crucified him and the criminals there,  
one on his right, the other on his left.  
Then Jesus said,  
“Father, forgive them, they know not what they do.”  
They divided his garments by casting lots.  
The people stood by and watched;  
the rulers, meanwhile, sneered at him and said,  
“He saved others, let him save himself  
if he is the chosen one, the Christ of God.”  
Even the soldiers jeered at him.  
As they approached to offer him wine they called out,  
“If you are King of the Jews, save yourself.”  
Above him there was an inscription that read,  
“This is the King of the Jews.”  

Now one of the criminals hanging there reviled Jesus, saying,  
“Are you not the Christ?  
Save yourself and us.”  
The other, however, rebuking him, said in reply,  
“Have you no fear of God,  
for you are subject to the same condemnation?  
And indeed, we have been condemned justly,  
for the sentence we received corresponds to our crimes,  
but this man has done nothing criminal.”  
Then he said,  
“Jesus, remember me when you come into your kingdom.”  
He replied to him,  
“Amen, I say to you,  
today you will be with me in Paradise.”  

It was now about noon and darkness came over the whole land  
until three in the afternoon  
because of an eclipse of the sun.  
Then the veil of the temple was torn down the middle.  
Jesus cried out in a loud voice,  
 “Father, into your hands I commend my spirit”;  
and when he had said this he breathed his last.  

[*Here all kneel and pause for a short time.*]{.red}  

The centurion who witnessed what had happened glorified God and said,  
“This man was innocent beyond doubt.”  
When all the people who had gathered for this spectacle  
saw what had happened,  
they returned home beating their breasts;  
but all his acquaintances stood at a distance,  
including the women who had followed him from Galilee. 
and saw these events.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The **Gloria** is omitted during Lent.
* The Palm Sunday liturgy begins at the rear of the church. The
**Processional Hymn** is not sung until after the first Gospel reading and
the priest concludes with “*...let us go forth in peace.*”
* If given the option, the hymn “Were You There” should be taken from GIA,
either the Gather or Worship hymnal, which usually have more
verses than Breaking Bread.
* Choral anthems oﬀered are alternatives for the **Meditation hymn**.
Palm Sunday should be coordinated with Good Friday to avoid repeating
anthems.