---
title: "SOLEMNITY OF THE ASCENSION OF THE LORD"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Hail the Day That Sees Him Rise"
          book: G
          priority: required
    psalm:
      list:
        - name: "God mounts his throne to shouts of joy: a blare of trumpets for the Lord."
          book: RA
          priority: required
    offertory:
      list:
        - name: "A Hymn of Glory Let Us Sing!"
          book: G
          priority: required
    communion:
      list:
        - name: "We Remember"
          book: G
          priority: required
    meditation:
      list:
        - name: "Be Joyful, Mary"
          book: G
          priority: required
    recessional:
      list:
        - name: "Lord, You Give the Great Commission"
          book: G
          priority: required
  b:
    processional:
      list:
        - name: "Hail the Day That Sees Him Rise"
          book: G
          priority: required
    psalm:
      list:
        - name: "God mounts his throne to shouts of joy: a blare of trumpets for the Lord."
          book: RA
          priority: required
    offertory:
      list:
        - name: "A Hymn of Glory Let Us Sing!"
          book: G
          priority: required
    communion:
      list:
        - name: "The Church of Christ"
          book: G
          priority: required
    meditation:
      list:
        - name: "Be Joyful, Mary"
          book: G
          priority: required
    recessional:
      list:
        - name: "Go to the World!"
          book: G
          priority: required
  c:
    processional:
      list:
        - name: "Hail the Day That Sees Him Rise"
          book: G
          priority: required
    psalm:
      list:
        - name: "God mounts his throne to shouts of joy: a blare of trumpets for the Lord."
          book: RA
          priority: required
    offertory:
      list:
        - name: "A Hymn of Glory Let Us Sing!"
          book: G
          priority: required
    communion:
      list:
        - name: "Let Us Be Bread"
          book: G
          priority: required
    meditation:
      list:
        - name: "Be Joyful, Mary"
          book: G
          priority: required
    recessional:
      list:
        - name: "Sing a New Church"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

glory, majesty, fulfillment, promise of Holy Spirit, baptism & mission

:::  {.red}
#### **Entrance Antiphon**
:::

> Men of Galilee, why gaze in wonder at the heavens?  
> This Jesus whom you saw ascending into heaven  
> will return as you saw him go, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> Behold, I am with you always,  
> even to the end of the age, alleluia.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Acts 1:1-11]{style="float:right" .small}
:::

In the first book, Theophilus,  
I dealt with all that Jesus did and taught  
until the day he was taken up,  
after giving instructions through the Holy Spirit  
to the apostles whom he had chosen.  
He presented himself alive to them  
by many proofs after he had suffered,  
appearing to them during forty days  
and speaking about the kingdom of God.  
While meeting with them,  
he enjoined them not to depart from Jerusalem,  
but to wait for “the promise of the Father  
about which you have heard me speak;  
for John baptized with water,  
but in a few days you will be baptized with the Holy Spirit.”  

When they had gathered together they asked him,  
“Lord, are you at this time going to restore the kingdom to Israel?”  
He answered them, “It is not for you to know the times or seasons  
that the Father has established by his own authority.  
But you will receive power when the Holy Spirit comes upon you,  
and you will be my witnesses in Jerusalem,  
throughout Judea and Samaria,  
and to the ends of the earth.”  
When he had said this, as they were looking on,  
he was lifted up, and a cloud took him from their sight.  
While they were looking intently at the sky as he was going,  
suddenly two men dressed in white garments stood beside them.  
They said, “Men of Galilee,  
why are you standing there looking at the sky?  
This Jesus who has been taken up from you into heaven  
will return in the same way as you have seen him going into heaven.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 47:2-3, 6-7, 8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **God mounts his throne to shouts of joy: a blare of trumpets for the Lord.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

All you peoples, clap your hands,  
&emsp; shout to God with cries of gladness,  
For the LORD, the Most High, the awesome,  
&emsp; is the great king over all the earth. **[℟.]{.red}**  

God mounts his throne amid shouts of joy;  
&emsp; the LORD, amid trumpet blasts.  
Sing praise to God, sing praise;  
&emsp; sing praise to our king, sing praise. **[℟.]{.red}**  

For king of all the earth is God;  
&emsp; sing hymns of praise.  
God reigns over the nations,  
&emsp; God sits upon his holy throne. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Ephesians 1:17-23]{style="float:right" .small}
:::

Brothers and sisters:  
May the God of our Lord Jesus Christ, the Father of glory,  
give you a Spirit of wisdom and revelation  
resulting in knowledge of him.  
May the eyes of your hearts be enlightened,  
that you may know what is the hope that belongs to his call,  
what are the riches of glory  
in his inheritance among the holy ones,  
and what is the surpassing greatness of his power  
for us who believe,  
in accord with the exercise of his great might,  
which he worked in Christ,  
raising him from the dead  
and seating him at his right hand in the heavens,  
far above every principality, authority, power, and dominion,  
and every name that is named  
not only in this age but also in the one to come.  
And he put all things beneath his feet  
and gave him as head over all things to the church,  
which is his body,  
the fullness of the one who fills all things in every way.  

[Or:]{.red} [Ephesians 4:1-13 or 4:1-7, 11-13]{style="float:right" .small .red}  

Brothers and sisters,  
I, a prisoner for the Lord,  
urge you to live in a manner worthy of the call you have received,  
with all humility and gentleness, with patience,  
bearing with one another through love,  
striving to preserve the unity of the spirit  
through the bond of peace:  
one body and one Spirit,  
as you were also called to the one hope of your call;  
one Lord, one faith, one baptism;  
one God and Father of all,  
who is over all and through all and in all.  

But grace was given to each of us  
according to the measure of Christ’s gift.  
Therefore, it says:  
&emsp; *He ascended on high and took prisoners captive;*  
&emsp; *he gave gifts to men.*  
What does “he ascended” mean except that he also descended  
into the lower regions of the earth?  
The one who descended is also the one who ascended  
far above all the heavens,  
that he might fill all things.  

And he gave some as apostles, others as prophets,  
others as evangelists, others as pastors and teachers,  
to equip the holy ones for the work of ministry,  
for building up the body of Christ,  
until we all attain to the unity of faith  
and knowledge of the Son of God, to mature manhood,  
to the extent of the full stature of Christ.  

[Or:]{.red}

Brothers and sisters,  
I, a prisoner for the Lord,  
urge you to live in a manner worthy of the calling  
you have received,  
with all humility and gentleness, with patience,  
bearing with one another through love,  
striving to preserve the unity of the Spirit  
through the bond of peace:  
one body and one Spirit,  
as you were also called to the one hope of your calling;  
one Lord, one faith, one baptism;  
one God and Father of all,  
who is over all and through all and in all.  

But grace was given to each of us  
according to the measure of Christ’s gift.  

And he gave some as apostles, others as prophets,  
others as evangelists, others as pastors and teachers,  
to equip the holy ones for the work of ministry,  
for building up the body of Christ,  
until we all attain to the unity of faith  
and knowledge of the Son of God, to mature manhood,  
to the extent of the full stature of Christ.  

***

::: {.red}
#### Gospel Acclamation [Matthew 28:19a, 20b]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Go and teach all nations, says the Lord;  
I am with you always, until the end of the world. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Mark 16:15-20]{style="float:right" .small}
:::

Jesus said to his disciples:  
“Go into the whole world  
and proclaim the gospel to every creature.  
Whoever believes and is baptized will be saved;  
whoever does not believe will be condemned.  
These signs will accompany those who believe:  
in my name they will drive out demons,  
they will speak new languages.  
They will pick up serpents with their hands,  
and if they drink any deadly thing, it will not harm them.  
They will lay hands on the sick, and they will recover.”  

So then the Lord Jesus, after he spoke to them,  
was taken up into heaven  
and took his seat at the right hand of God.  
But they went forth and preached everywhere,  
while the Lord worked with them  
and confirmed the word through accompanying signs.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```

```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* In most United States dioceses, the Solemnity of the Ascension is transferred to---and replaces-–-the Seventh Sunday of Easter. In this scenario, the Solemnity of the Ascension takes priority and the hymns for the Solemnity are used. The Seventh Sunday of Easter is then skipped; the following weekend is Pentecost Sunday.