---
title: "SECOND SUNDAY OF EASTER"
subtitle: "Sunday of Divine Mercy"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "The Strife is O'er"
          book: G
          priority: optional
        - name: "There's a Wideness in God's Mercy"
          book: G
          priority: optional
    psalm:
      list:
        - name: "Give thanks to the Lord for he is good, his love is everlasting."
          book: RA
          priority: required
    offertory:
      list:
        - name: "We Remember"
          book: G
          priority: required
    communion:
      list:
        - name: "O Sons and Daughters"
          book: G
          priority: required
    meditation:
      list:
        - name: "We Walk By Faith"
          book: G
          priority: required
    recessional:
      list:
        - name: "Sing to the Mountains"
          book: G
          priority: required
    anthems:
      list:
        - name: "Peace, Be Not Anxious"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

mercy, baptism, faith, community, praise, rejoicing

:::  {.red}
#### **Entrance Antiphon**
:::

> Like newborn infants, you must long for the pure, spiritual milk,  
> that in him you may grow to salvation, alleluia.  
>  
> [Or:]{.red}  
>  
> Receive the joy of your glory, giving thanks to God,  
> who has called you into the heavenly kingdom, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> Bring your hand and feel the place of the nails,  
> and do not be unbelieving but believing, alleluia.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Acts 2:42-47]{style="float:right" .small}
:::

They devoted themselves  
to the teaching of the apostles and to the communal life,  
to the breaking of bread and to the prayers.  
Awe came upon everyone,  
and many wonders and signs were done through the apostles.  
All who believed were together and had all things in common;  
they would sell their property and possessions  
and divide them among all according to each one’s need.  
Every day they devoted themselves  
to meeting together in the temple area  
and to breaking bread in their homes.  
They ate their meals with exultation and sincerity of heart,  
praising God and enjoying favor with all the people.  
And every day the Lord added to their number those who were being saved.  

***

::: {.red}
#### Responsorial Psalm [Psalm 118:2-4, 13-15, 22-24]{style="float:right" .small}
:::

**[℟.]{.red}** **Give thanks to the LORD for he is good, his love is everlasting.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Let the house of Israel say,  
“His mercy endures forever.”  
Let the house of Aaron say,  
“His mercy endures forever.”  
Let those who fear the LORD say,  
“His mercy endures forever.” **[℟.]{.red}**  

I was hard pressed and was falling,  
but the LORD helped me.  
My strength and my courage is the LORD,  
and he has been my savior.  
The joyful shout of victory  
in the tents of the just. **[℟.]{.red}**  

The stone which the builders rejected  
has become the cornerstone.  
By the LORD has this been done;  
it is wonderful in our eyes.  
This is the day the LORD has made;  
let us be glad and rejoice in it. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Peter 1:3-9]{style="float:right" .small}
:::

Blessed be the God and Father of our Lord Jesus Christ,  
who in his great mercy gave us a new birth to a living hope  
through the resurrection of Jesus Christ from the dead,  
to an inheritance that is imperishable, undefiled, and unfading,  
kept in heaven for you  
who by the power of God are safeguarded through faith,  
to a salvation that is ready to be revealed in the final time.  
In this you rejoice, although now for a little while  
you may have to suffer through various trials,  
so that the genuineness of your faith,  
more precious than gold that is perishable even though tested by fire,  
may prove to be for praise, glory, and honor  
at the revelation of Jesus Christ.  
Although you have not seen him you love him;  
even though you do not see him now yet believe in him,  
you rejoice with an indescribable and glorious joy,  
as you attain the goal of your faith, the salvation of your souls.

***

::: {.red}
#### Gospel Acclamation [John 20:29]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
You believe in me, Thomas, because you have seen me, says the Lord;  
blessed are they who have not seen me, but still believe! **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 20:19-31]{style="float:right" .small}
:::

On the evening of that first day of the week,  
when the doors were locked, where the disciples were,  
for fear of the Jews,  
Jesus came and stood in their midst  
and said to them, “Peace be with you.”  
When he had said this, he showed them his hands and his side.  
The disciples rejoiced when they saw the Lord.  
Jesus said to them again, “Peace be with you.  
As the Father has sent me, so I send you.”  
And when he had said this, he breathed on them and said to them,  
“Receive the Holy Spirit.  
Whose sins you forgive are forgiven them,  
and whose sins you retain are retained.”  

Thomas, called Didymus, one of the Twelve,  
was not with them when Jesus came.  
So the other disciples said to him, “We have seen the Lord.”  
But he said to them,  
“Unless I see the mark of the nails in his hands  
and put my finger into the nailmarks  
and put my hand into his side, I will not believe.”  

Now a week later his disciples were again inside  
and Thomas was with them.  
Jesus came, although the doors were locked,  
and stood in their midst and said, “Peace be with you.”  
Then he said to Thomas, “Put your finger here and see my hands,  
and bring your hand and put it into my side,  
and do not be unbelieving, but believe.”  
Thomas answered and said to him, “My Lord and my God!”  
Jesus said to him, “Have you come to believe because you have seen me?  
Blessed are those who have not seen and have believed.”  

Now, Jesus did many other signs in the presence of his disciples  
that are not written in this book.  
But these are written that you may come to believe  
that Jesus is the Christ, the Son of God,  
and that through this belief you may have life in his name.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Acts 4:32-35]{style="float:right" .small}
:::

The community of believers was of one heart and mind,  
and no one claimed that any of his possessions was his own,  
but they had everything in common.  
With great power the apostles bore witness  
to the resurrection of the Lord Jesus,  
and great favor was accorded them all.  
There was no needy person among them,  
for those who owned property or houses would sell them,  
bring the proceeds of the sale,  
and put them at the feet of the apostles,  
and they were distributed to each according to need.  

***

::: {.red}
#### Responsorial Psalm [Psalm 118:2-4, 13-15, 22-24]{style="float:right" .small}
:::

**[℟.]{.red}** **Give thanks to the LORD for he is good, his love is everlasting.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Let the house of Israel say,  
“His mercy endures forever.”  
Let the house of Aaron say,  
“His mercy endures forever.”  
Let those who fear the LORD say,  
“His mercy endures forever.” **[℟.]{.red}**  

I was hard pressed and was falling,  
but the LORD helped me.  
My strength and my courage is the LORD,  
and he has been my savior.  
The joyful shout of victory  
in the tents of the just. **[℟.]{.red}**  

The stone which the builders rejected  
has become the cornerstone.  
By the LORD has this been done;  
it is wonderful in our eyes.  
This is the day the LORD has made;  
let us be glad and rejoice in it. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 John 5:1-6]{style="float:right" .small}
:::

Beloved:  
Everyone who believes that Jesus is the Christ is begotten by God,  
and everyone who loves the Father  
loves also the one begotten by him.  
In this way we know that we love the children of God  
when we love God and obey his commandments.  
For the love of God is this,  
that we keep his commandments.  
And his commandments are not burdensome,  
for whoever is begotten by God conquers the world.  
And the victory that conquers the world is our faith.  
Who indeed is the victor over the world  
but the one who believes that Jesus is the Son of God?  

This is the one who came through water and blood, Jesus Christ,  
not by water alone, but by water and blood.  
The Spirit is the one that testifies,  
and the Spirit is truth.  

***

::: {.red}
#### Gospel Acclamation [Jn 20:29]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
You believe in me, Thomas, because you have seen me, says the Lord;  
Blessed are those who have not seen me, but still believe! **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 20:19-31]{style="float:right" .small}
:::

On the evening of that first day of the week,  
when the doors were locked, where the disciples were,  
for fear of the Jews,  
Jesus came and stood in their midst  
and said to them, "Peace be with you."  
When he had said this, he showed them his hands and his side.  
The disciples rejoiced when they saw the Lord.  
Jesus said to them again, "Peace be with you.  
As the Father has sent me, so I send you."  
And when he had said this, he breathed on them and said to them,  
"Receive the Holy Spirit.  
Whose sins you forgive are forgiven them,  
and whose sins you retain are retained."  

Thomas, called Didymus, one of the Twelve,  
was not with them when Jesus came.  
So the other disciples said to him, "We have seen the Lord."  
But he said to them,  
"Unless I see the mark of the nails in his hands  
and put my finger into the nailmarks  
and put my hand into his side, I will not believe."  

Now a week later his disciples were again inside  
and Thomas was with them.  
Jesus came, although the doors were locked,  
and stood in their midst and said, "Peace be with you."  
Then he said to Thomas, "Put your finger here and see my hands,  
and bring your hand and put it into my side,  
and do not be unbelieving, but believe."  
Thomas answered and said to him, "My Lord and my God!"  
Jesus said to him, "Have you come to believe because you have seen me?  
Blessed are those who have not seen and have believed."  

Now Jesus did many other signs in the presence of his disciples  
that are not written in this book.  
But these are written that you may come to believe  
that Jesus is the Christ, the Son of God,  
and that through this belief you may have life in his name.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Acts 5:12-16]{style="float:right" .small}
:::

Many signs and wonders were done among the people  
at the hands of the apostles.  
They were all together in Solomon’s portico.  
None of the others dared to join them, but the people esteemed them.  
Yet more than ever, believers in the Lord,  
great numbers of men and women, were added to them.  
Thus they even carried the sick out into the streets  
and laid them on cots and mats. 
so that when Peter came by,  
at least his shadow might fall on one or another of them.  
A large number of people from the towns  
in the vicinity of Jerusalem also gathered,  
bringing the sick and those disturbed by unclean spirits,  
and they were all cured.  

***

::: {.red}
#### Responsorial Psalm [Psalm 118:2-4, 13-15, 22-24]{style="float:right" .small}
:::

**[℟.]{.red}** **Give thanks to the LORD for he is good, his love is everlasting.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Let the house of Israel say,  
“His mercy endures forever.”  
Let the house of Aaron say,  
“His mercy endures forever.”  
Let those who fear the LORD say,  
“His mercy endures forever.” **[℟.]{.red}**  

I was hard pressed and was falling,  
but the LORD helped me.  
My strength and my courage is the LORD,  
and he has been my savior.  
The joyful shout of victory  
in the tents of the just. **[℟.]{.red}**  

The stone which the builders rejected  
has become the cornerstone.  
By the LORD has this been done;  
it is wonderful in our eyes.  
This is the day the LORD has made;  
let us be glad and rejoice in it. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Revelation 1:9-11a, 12-13, 17-19]{style="float:right" .small}
:::

I, John, your brother, who share with you  
the distress, the kingdom, and the endurance we have in Jesus,  
found myself on the island called Patmos  
because I proclaimed God’s word and gave testimony to Jesus.  
I was caught up in spirit on the Lord’s day  
and heard behind me a voice as loud as a trumpet, which said,  
“Write on a scroll what you see.”  
Then I turned to see whose voice it was that spoke to me,  
and when I turned, I saw seven gold lampstands  
and in the midst of the lampstands one like a son of man,  
wearing an ankle-length robe, with a gold sash around his chest.  

When I caught sight of him, I fell down at his feet as though dead.  
He touched me with his right hand and said, “Do not be afraid.  
I am the first and the last, the one who lives.  
Once I was dead, but now I am alive forever and ever.  
I hold the keys to death and the netherworld.  
Write down, therefore, what you have seen,  
and what is happening, and what will happen afterwards.”  

***

::: {.red}
#### Gospel Acclamation [John 20:29]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
You believe in me, Thomas, because you have seen me, says the Lord;  
blessed are those who have not seen me, but still believe! **[℟.]{.red}** 

***

::: {.red}
#### Gospel [Jn 20:19-31]{style="float:right" .small}
:::

On the evening of that first day of the week,  
when the doors were locked, where the disciples were,  
for fear of the Jews,  
Jesus came and stood in their midst  
and said to them, “Peace be with you.”  
When he had said this, he showed them his hands and his side.  
The disciples rejoiced when they saw the Lord.  
Jesus said to them again, “Peace be with you.  
As the Father has sent me, so I send you.”  
And when he had said this, he breathed on them and said to them,  
“Receive the Holy Spirit.  
Whose sins you forgive are forgiven them,  
and whose sins you retain are retained.”  

Thomas, called Didymus, one of the Twelve,  
was not with them when Jesus came.  
So the other disciples said to him, “We have seen the Lord.”  
But he said to them,  
“Unless I see the mark of the nails in his hands  
and put my finger into the nailmarks  
and put my hand into his side, I will not believe.”  

Now a week later his disciples were again inside  
and Thomas was with them.  
Jesus came, although the doors were locked,  
and stood in their midst and said, “Peace be with you.”  
Then he said to Thomas, “Put your finger here and see my hands,  
and bring your hand and put it into my side,  
and do not be unbelieving, but believe.”  
Thomas answered and said to him, “My Lord and my God!”  
Jesus said to him, “Have you come to believe because you have seen me?  
Blessed are those who have not seen and have believed.”  

Now Jesus did many other signs in the presence of his disciples  
that are not written in this book.  
But these are written that you may come to believe  
that Jesus is the Christ, the Son of God,  
and that through this belief you may have life in his name.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The Second Sunday of Easter is also **Divine Mercy Sunday**.
* If the **dismissal of the people** is chanted by the presider, the cantor
must promptly-–-without pause or hesitation-–-lead the chanted response
found in [Appendix F](../appendices/F-easter-dismissal.qmd).