---
title: "SIXTH SUNDAY OF EASTER"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "That Easter Day with Joy Was Bright"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "Let all the earth cry out to God with joy."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Now the Green Blade Rises"
          book: G
          priority: preferred
    communion:
      list:
        - name: "Come Down, O Love Divine"
          book: G
          priority: required
    meditation:
      list:
        - name: "Holy Spirit, Come to Us"
          book: G
          priority: required
    recessional:
      list:
        - name: "O Spirit All-Embracing"
          book: G
          priority: required
  b:
    processional:
      list:
        - name: "That Easter Day with Joy Was Bright"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "The Lord has revealed to the nations his saving power."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Come Down, O Love Divine"
          book: G
          priority: required
    communion:
      list:
        - name: "No Greater Love"
          book: G
          priority: required
    meditation:
      list:
        - name: "Holy Spirit, Come to Us"
          book: G
          priority: optional
    recessional:
      list:
        - name: "O Spirit All-Embracing"
          book: G
          priority: required
  c:
    processional:
      list:
        - name: "That Easter Day with Joy Was Bright"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "O God, let all the nations praise you."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Come Down, O Love Divine"
          book: G
          priority: required
    communion:
      list:
        - name: "Unless a Grain of Wheat"
          book: G
          priority: required
    meditation:
      list:
        - name: "O Radiant Light"
          book: G
          priority: preferred
    recessional:
      list:
        - name: "O Spirit All-Embracing"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

initiation, Holy Spirit, truth, community, love

:::  {.red}
#### **Entrance Antiphon**
:::

> Proclaim a joyful sound and let it be heard;  
> proclaim to the ends of the earth:  
> The Lord has freed his people, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> If you love me, keep my commandments, says the Lord,  
> and I will ask the Father and he will send you another Paraclete,  
> to abide with you for ever, alleluia.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Acts 8:5-8, 14-17]{style="float:right" .small}
:::

Philip went down to the city of Samaria  
and proclaimed the Christ to them.  
With one accord, the crowds paid attention to what was said by Philip  
when they heard it and saw the signs he was doing.  
For unclean spirits, crying out in a loud voice,  
came out of many possessed people,  
and many paralyzed or crippled people were cured.  
There was great joy in that city.  

Now when the apostles in Jerusalem  
heard that Samaria had accepted the word of God,  
they sent them Peter and John,  
who went down and prayed for them,  
that they might receive the Holy Spirit,  
for it had not yet fallen upon any of them;  
they had only been baptized in the name of the Lord Jesus.  
Then they laid hands on them  
and they received the Holy Spirit.  

***

::: {.red}
#### Responsorial Psalm [Psalm 66:1-3, 4-5, 6-7, 16, 20]{style="float:right" .small}
:::

**[℟.]{.red}** **Let all the earth cry out to God with joy.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Shout joyfully to God, all the earth,  
sing praise to the glory of his name;  
proclaim his glorious praise.  
Say to God, “How tremendous are your deeds!” **[℟.]{.red}**  

“Let all on earth worship and sing praise to you,  
sing praise to your name!”  
Come and see the works of God,  
his tremendous deeds among the children of Adam. **[℟.]{.red}**  

He has changed the sea into dry land;  
through the river they passed on foot;  
therefore let us rejoice in him.  
He rules by his might forever. **[℟.]{.red}**  

Hear now, all you who fear God, while I declare  
what he has done for me.  
Blessed be God who refused me not  
my prayer or his kindness! **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Peter 3:15-18]{style="float:right" .small}
:::

Beloved:  
Sanctify Christ as Lord in your hearts.  
Always be ready to give an explanation  
to anyone who asks you for a reason for your hope,  
but do it with gentleness and reverence,  
keeping your conscience clear,  
so that, when you are maligned,  
those who defame your good conduct in Christ  
may themselves be put to shame.  
For it is better to suffer for doing good,  
if that be the will of God, than for doing evil.  

For Christ also suffered for sins once,  
the righteous for the sake of the unrighteous,  
that he might lead you to God.  
Put to death in the flesh,  
he was brought to life in the Spirit.  

***

::: {.red}
#### Gospel Acclamation [John 14:23]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Whoever loves me will keep my word, says the Lord,  
and my Father will love him and we will come to him. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 14:15-21]{style="float:right" .small}
:::

Jesus said to his disciples:  
“If you love me, you will keep my commandments.  
And I will ask the Father,  
and he will give you another Advocate to be with you always,  
the Spirit of truth, whom the world cannot accept,  
because it neither sees nor knows him.  
But you know him, because he remains with you,  
and will be in you.  
I will not leave you orphans; I will come to you.  
In a little while the world will no longer see me,  
but you will see me, because I live and you will live.  
On that day you will realize that I am in my Father  
and you are in me and I in you.  
Whoever has my commandments and observes them  
is the one who loves me.  
And whoever loves me will be loved by my Father,  
and I will love him and reveal myself to him.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Acts 10:25-26, 34-35, 44-48]{style="float:right" .small}
:::

When Peter entered, Cornelius met him  
and, falling at his feet, paid him homage.  
Peter, however, raised him up, saying,  
"Get up. I myself am also a human being."  

Then Peter proceeded to speak and said,  
"In truth, I see that God shows no partiality.  
Rather, in every nation whoever fears him and acts uprightly  
is acceptable to him."  

While Peter was still speaking these things,  
the Holy Spirit fell upon all who were listening to the word.  
The circumcised believers who had accompanied Peter  
were astounded that the gift of the Holy Spirit  
should have been poured out on the Gentiles also,  
for they could hear them speaking in tongues and glorifying God.  
Then Peter responded,  
"Can anyone withhold the water for baptizing these people,  
who have received the Holy Spirit even as we have?"  
He ordered them to be baptized in the name of Jesus Christ.  

***

::: {.red}
#### Responsorial Psalm [Psalm 98:1, 2-3, 3-4]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord has revealed to the nations his saving power.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Sing to the LORD a new song,  
for he has done wondrous deeds;  
His right hand has won victory for him,  
his holy arm. **[℟.]{.red}**  

The LORD has made his salvation known:  
in the sight of the nations he has revealed his justice.  
He has remembered his kindness and his faithfulness  
toward the house of Israel. **[℟.]{.red}**  

All the ends of the earth have seen  
the salvation by our God.  
Sing joyfully to the LORD, all you lands;  
break into song; sing praise. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 John 4:7-10]{style="float:right" .small}
:::

Beloved, let us love one another,  
because love is of God;  
everyone who loves is begotten by God and knows God.  
Whoever is without love does not know God, for God is love.  
In this way the love of God was revealed to us:  
God sent his only Son into the world  
so that we might have life through him.  
In this is love:  
not that we have loved God, but that he loved us  
and sent his Son as expiation for our sins.  

***

::: {.red}
#### Gospel Acclamation [John 14:23]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Whoever loves me will keep my word, says the Lord,  
and my Father will love him and we will come to him. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 15:9-17]{style="float:right" .small}
:::

Jesus said to his disciples:  
"As the Father loves me, so I also love you.  
Remain in my love.  
If you keep my commandments, you will remain in my love,  
just as I have kept my Father's commandments  
and remain in his love.  

"I have told you this so that my joy may be in you  
and your joy might be complete.  
This is my commandment: love one another as I love you.  
No one has greater love than this,  
to lay down one's life for one's friends.  
You are my friends if you do what I command you.  
I no longer call you slaves,  
because a slave does not know what his master is doing.  
I have called you friends,  
because I have told you everything I have heard from my Father.  
It was not you who chose me, but I who chose you  
and appointed you to go and bear fruit that will remain,  
so that whatever you ask the Father in my name he may give you.  
This I command you: love one another."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Acts 15:1-2, 22-29]{style="float:right" .small}
:::

Some who had come down from Judea were instructing the brothers,  
“Unless you are circumcised according to the Mosaic practice,  
you cannot be saved.”  
Because there arose no little dissension and debate  
by Paul and Barnabas with them,  
it was decided that Paul, Barnabas, and some of the others  
should go up to Jerusalem to the apostles and elders  
about this question.  

The apostles and elders, in agreement with the whole church,  
decided to choose representatives  
and to send them to Antioch with Paul and Barnabas.  
The ones chosen were Judas, who was called Barsabbas,  
and Silas, leaders among the brothers.  
This is the letter delivered by them:  

“The apostles and the elders, your brothers,  
to the brothers in Antioch, Syria, and Cilicia  
of Gentile origin: greetings.  
Since we have heard that some of our number  
who went out without any mandate from us  
have upset you with their teachings  
and disturbed your peace of mind,  
we have with one accord decided to choose representatives  
and to send them to you along with our beloved Barnabas and Paul,  
who have dedicated their lives to the name of our Lord Jesus Christ.  
So we are sending Judas and Silas  
who will also convey this same message by word of mouth:  
‘It is the decision of the Holy Spirit and of us  
not to place on you any burden beyond these necessities,  
namely, to abstain from meat sacrificed to idols,  
from blood, from meats of strangled animals,  
and from unlawful marriage.  
If you keep free of these,  
you will be doing what is right. Farewell.’”  

***

::: {.red}
#### Responsorial Psalm [Psalm 67:2-3, 5, 6, 8]{style="float:right" .small}
:::

**[℟.]{.red}** **O God, let all the nations praise you!**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

May God have pity on us and bless us;  
&emsp; may he let his face shine upon us.  
So may your way be known upon earth;  
&emsp; among all nations, your salvation. **[℟.]{.red}**  

May the nations be glad and exult  
&emsp; because you rule the peoples in equity;  
&emsp; the nations on the earth you guide. **[℟.]{.red}**  

May the peoples praise you, O God;  
&emsp; may all the peoples praise you!  
May God bless us,  
&emsp; and may all the ends of the earth fear him! **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Revelation 21:10-14, 22-23]{style="float:right" .small}
:::

The angel took me in spirit to a great, high mountain  
and showed me the holy city Jerusalem  
coming down out of heaven from God.  
It gleamed with the splendor of God.  
Its radiance was like that of a precious stone,  
like jasper, clear as crystal.  
It had a massive, high wall,  
with twelve gates where twelve angels were stationed  
and on which names were inscribed,  
the names of the twelve tribes of the Israelites.  
There were three gates facing east,  
three north, three south, and three west.  
The wall of the city had twelve courses of stones as its foundation,  
on which were inscribed the twelve names  
of the twelve apostles of the Lamb.  

I saw no temple in the city  
for its temple is the Lord God almighty and the Lamb.  
The city had no need of sun or moon to shine on it,  
for the glory of God gave it light,  
and its lamp was the Lamb.  

***

::: {.red}
#### Gospel Acclamation [John 14:23]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Whoever loves me will keep my word, says the Lord,  
and my Father will love him and we will come to him. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [John 14:23-29]{style="float:right" .small}
:::

Jesus said to his disciples:  
“Whoever loves me will keep my word,  
and my Father will love him,  
and we will come to him and make our dwelling with him.  
Whoever does not love me does not keep my words;  
yet the word you hear is not mine  
but that of the Father who sent me.  

“I have told you this while I am with you.  
The Advocate, the Holy Spirit,  
whom the Father will send in my name,  
will teach you everything  
and remind you of all that I told you.  
Peace I leave with you; my peace I give to you.  
Not as the world gives do I give it to you.  
Do not let your hearts be troubled or afraid.  
You heard me tell you,  
‘I am going away and I will come back to you.’  
If you loved me,  
you would rejoice that I am going to the Father;  
for the Father is greater than I.  
And now I have told you this before it happens,  
so that when it happens you may believe.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```
