---
title: "EASTER SUNDAY"
subtitle: "The Resurrection of the Lord"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Jesus Christ is Risen Today"
          book: G
          priority: required
    psalm:
      list:
        - name: "This is the day the Lord has made. Let us rejoice and be glad."
          book: RA
          priority: optional
        - name: "Psalm 118: This is the Day"
          book: G
          priority: optional
    sequence:
      list:
        - name: "Christ, the Lord, Is Risen Today"
          tune: "VICTIMAE PASCHALI"
          book: Handout
          priority: optional
        - name: Handout
          book: Handout
          priority: optional
    offertory:
      list:
        - name: "This is the Feast of Victory"
          book: G
          priority: required
    communion:
      list:
        - name: "Worthy Is the Lamb (Manalo)"
          book: Handout
          priority: required
    meditation:
      list:
        - name: "Be Joyful, Mary"
          book: G
          priority: required
    recessional:
      list:
        - name: "The Strife is O'er"
          book: G
          priority: required
  a:
    anthems:
      list:
        - name: "Proclaim the Message"
  b:
    anthems:
      list:
        - name: "Thine Be the Glory"
  c:
    anthems:
      list:
        - name: "Hallelujah Chorus"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

solemnity, glory, joy, resurrection, life, hope, baptism

:::  {.red}
#### **Entrance Antiphon**
:::

> I have risen, and I am with you still, alleluia.  
> You have laid your hand upon me, alleluia.  
> Too wonderful for me, this knowledge, alleluia, alleluia.  
>  
> [Or:]{.red}  
>  
> The Lord is truly risen, alleluia.  
> To him be glory and power 
> for all the ages of eternity, alleluia, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> Christ our Passover has been sacrificed, alleluia;  
> therefore let us keep the feast with the unleavened bread  
> of purity and truth, alleluia, alleluia.  

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Acts 10:34a, 37-43]{style="float:right" .small}
:::

Peter proceeded to speak and said:  
“You know what has happened all over Judea,  
beginning in Galilee after the baptism  
that John preached,  
how God anointed Jesus of Nazareth  
with the Holy Spirit and power.  
He went about doing good  
and healing all those oppressed by the devil,  
for God was with him.  
We are witnesses of all that he did  
both in the country of the Jews and in Jerusalem.  
They put him to death by hanging him on a tree.  
This man God raised on the third day and granted that he be visible,  
not to all the people, but to us,  
the witnesses chosen by God in advance,  
who ate and drank with him after he rose from the dead.  
He commissioned us to preach to the people  
and testify that he is the one appointed by God  
as judge of the living and the dead.  
To him all the prophets bear witness,  
that everyone who believes in him  
will receive forgiveness of sins through his name.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 118:1-2, 16-17, 22-23]{style="float:right" .small}
:::

**[℟.]{.red}** **This is the day the Lord has made; let us rejoice and be glad.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Give thanks to the LORD, for he is good,
for his mercy endures forever.
Let the house of Israel say,
“His mercy endures forever.” **[℟.]{.red}**  

“The right hand of the LORD has struck with power;  
the right hand of the LORD is exalted.  
I shall not die, but live,  
and declare the works of the LORD.” **[℟.]{.red}**  

The stone which the builders rejected  
has become the cornerstone.  
By the LORD has this been done;  
it is wonderful in our eyes. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Colossians 3:1-4]{style="float:right" .small}
:::

Brothers and sisters:  
If then you were raised with Christ, seek what is above,  
where Christ is seated at the right hand of God.  
Think of what is above, not of what is on earth.  
For you have died, and your life is hidden with Christ in God.  
When Christ your life appears,  
then you too will appear with him in glory.  

[Or:]{.red} [1 Corinthians 5:6b-8]{style="float:right" .small}

Brothers and sisters:  
Do you not know that a little yeast leavens all the dough?  
Clear out the old yeast,  
so that you may become a fresh batch of dough,  
inasmuch as you are unleavened.  
For our paschal lamb, Christ, has been sacrificed.  
Therefore, let us celebrate the feast,  
not with the old yeast, the yeast of malice and wickedness,  
but with the unleavened bread of sincerity and truth.  

***

::: {.red}
#### Sequence: [*Victimæ paschali laudes*]{style="float:right" .small}
:::

Christians, to the Paschal Victim  
Offer your thankful praises!  
A Lamb the sheep redeems;  
Christ, who only is sinless,  
Reconciles sinners to the Father.  
Death and life have contended in that combat stupendous:  
The Prince of life, who died, reigns immortal.  
Speak, Mary, declaring  
What you saw, wayfaring.  
“The tomb of Christ, who is living,  
The glory of Jesus’ resurrection;  
bright angels attesting,  
The shroud and napkin resting.  
Yes, Christ my hope is arisen;  
to Galilee he goes before you.”  
Christ indeed from death is risen, our new life obtaining.  
Have mercy, victor King, ever reigning!  
Amen. Alleluia.  

***

::: {.red}
#### Gospel Acclamation [cf. 1 Corinthians 5:7]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Christ, our paschal lamb, has been sacrificed;  
let us then feast with joy in the Lord. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 20:1-9]{style="float:right" .small}
:::

On the first day of the week,  
Mary of Magdala came to the tomb early in the morning,  
while it was still dark,  
and saw the stone removed from the tomb.  
So she ran and went to Simon Peter  
and to the other disciple whom Jesus loved, and told them,  
“They have taken the Lord from the tomb,  
and we don’t know where they put him.”  
So Peter and the other disciple went out and came to the tomb.  
They both ran, but the other disciple ran faster than Peter  
and arrived at the tomb first;  
he bent down and saw the burial cloths there, but did not go in.  
When Simon Peter arrived after him,  
he went into the tomb and saw the burial cloths there,  
and the cloth that had covered his head,  
not with the burial cloths but rolled up in a separate place.  
Then the other disciple also went in,  
the one who had arrived at the tomb first,  
and he saw and believed.  
For they did not yet understand the Scripture  
that he had to rise from the dead.  

[Or, Year A:]{.red} [Matthew 28:1-10]{style="float:right" .small .red}

After the sabbath, as the first day of the week was dawning,  
Mary Magdalene and the other Mary came to see the tomb.  
And behold, there was a great earthquake;  
for an angel of the Lord descended from heaven,  
approached, rolled back the stone, and sat upon it.  
His appearance was like lightning  
and his clothing was white as snow.  
The guards were shaken with fear of him  
and became like dead men.  
Then the angel said to the women in reply,  
“Do not be afraid!  
I know that you are seeking Jesus the crucified.  
He is not here, for he has been raised just as he said.  
Come and see the place where he lay.  
Then go quickly and tell his disciples,  
‘He has been raised from the dead,  
and he is going before you to Galilee;  
there you will see him.’  
Behold, I have told you.”  
Then they went away quickly from the tomb,  
fearful yet overjoyed,  
and ran to announce this to his disciples.  
And behold, Jesus met them on their way and greeted them.  
They approached, embraced his feet, and did him homage.  
Then Jesus said to them, “Do not be afraid.  
Go tell my brothers to go to Galilee,  
and there they will see me.”  

[Or, Year B:]{.red} [Mark 16:1-7]{style="float:right" .small .red}

When the sabbath was over,  
Mary Magdalene, Mary, the mother of James, and Salome  
bought spices so that they might go and anoint him.  
Very early when the sun had risen,  
on the first day of the week, they came to the tomb.  
They were saying to one another,  
“Who will roll back the stone for us  
from the entrance to the tomb?”  
When they looked up,  
they saw that the stone had been rolled back;  
it was very large.  
On entering the tomb they saw a young man  
sitting on the right side, clothed in a white robe,  
and they were utterly amazed.  
He said to them, “Do not be amazed!  
You seek Jesus of Nazareth, the crucified.  
He has been raised; he is not here.  
Behold the place where they laid him.  
But go and tell his disciples and Peter,   
‘He is going before you to Galilee;  
there you will see him, as he told you.’”  

[Or, Year C:]{.red} [Luke 24:1-12]{style="float:right" .small .red}

At daybreak on the first day of the week  
the women who had come from Galilee with Jesus  
took the spices they had prepared  
and went to the tomb.  
They found the stone rolled away from the tomb;  
but when they entered,  
they did not find the body of the Lord Jesus.  
While they were puzzling over this, behold,  
two men in dazzling garments appeared to them.  
They were terrified and bowed their faces to the ground.  
They said to them,  
“Why do you seek the living one among the dead?  
He is not here, but he has been raised.  
Remember what he said to you while he was still in Galilee,  
that the Son of Man must be handed over to sinners  
and be crucified, and rise on the third day.”  
And they remembered his words.  
Then they returned from the tomb  
and announced all these things to the eleven  
and to all the others.  
The women were Mary Magdalene, Joanna, and Mary the mother of James;  
the others who accompanied them also told this to the apostles,  
but their story seemed like nonsense  
and they did not believe them.  
But Peter got up and ran to the tomb,  
bent down, and saw the burial cloths alone;  
then he went home amazed at what had happened.  

[Or at afternoon or evening Mass:]{.red} [Luke 24:13-35]{style="float:right" .small .red}

That very day, the first day of the week,  
two of Jesus' disciples were going  
to a village seven miles from Jerusalem called Emmaus,  
and they were conversing about all the things that had occurred.  
And it happened that while they were conversing and debating,  
Jesus himself drew near and walked with them,  
but their eyes were prevented from recognizing him.  
He asked them,  
"What are you discussing as you walk along?"  
They stopped, looking downcast.  
One of them, named Cleopas, said to him in reply,  
"Are you the only visitor to Jerusalem  
who does not know of the things  
that have taken place there in these days?"  
And he replied to them, "What sort of things?"  
They said to him,  
"The things that happened to Jesus the Nazarene,  
who was a prophet mighty in deed and word  
before God and all the people,  
how our chief priests and rulers both handed him over  
to a sentence of death and crucified him.  
But we were hoping that he would be the one to redeem Israel;  
and besides all this,  
it is now the third day since this took place.  
Some women from our group, however, have astounded us:  
they were at the tomb early in the morning  
and did not find his body;  
they came back and reported  
that they had indeed seen a vision of angels  
who announced that he was alive.  
Then some of those with us went to the tomb  
and found things just as the women had described,  
but him they did not see."  
And he said to them, "Oh, how foolish you are!  
How slow of heart to believe all that the prophets spoke!  
Was it not necessary that the Christ should suffer these things  
and enter into his glory?"  
Then beginning with Moses and all the prophets,  
he interpreted to them what referred to him  
in all the Scriptures.  
As they approached the village to which they were going,  
he gave the impression that he was going on farther.  
But they urged him, "Stay with us,  
for it is nearly evening and the day is almost over."  
So he went in to stay with them.  
And it happened that, while he was with them at table,  
he took bread, said the blessing,  
broke it, and gave it to them.  
With that their eyes were opened and they recognized him,  
but he vanished from their sight.  
Then they said to each other,  
"Were not our hearts burning within us  
while he spoke to us on the way and opened the Scriptures to us?"  
So they set out at once and returned to Jerusalem  
where they found gathered together  
the eleven and those with them who were saying,  
"The Lord has truly been raised and has appeared to Simon!"  
Then the two recounted  
what had taken place on the way  
and how he was made known to them in the breaking of bread.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* If available, the Festival Alleluia (GIA) is used for the **Gospel Acclamation** with the **Easter** verse found in [Appendix B](../appendices/B-festival-alleluia.qmd).
* The **Sequence** is sung by the cantor only (*i.e.*, no choir) immediately after the Second Reading. If the hymn "Christ, the Lord, is Risen Today" is used, the entire hymn is to be sung. Note that it is the version set to the tune <span style="font-variant:small-caps">victimae paschali</span>. Accompaniment should be soft and reverent, like Meditation hymns.
* If the **dismissal of the people** is chanted by the presider, the cantor must promptly – without pause or hesitation – lead the chanted response found in [Appendix F](../appendices/F-easter-dismissal.qmd).