---
title: "FIFTH SUNDAY OF EASTER"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Sing a New Song"
          composer: Schutte
          book: G
          priority: required
    psalm:
      list:
        - name: "Lord, let your mercy be on us, as we place our trust in you."
          book: RA
          priority: required
    offertory:
      list:
        - name: "I Sing a Maid"
          book: G
          note: "all verses"
          priority: optional
        - name: "I Know That My Redeemer Lives"
          tune: DUKE STREET
          book: G
          priority: optional
    communion:
      list:
        - name: "Take and Eat"
          book: G
          priority: optional
        - name: "I Receive the Living God"
          book: G
          priority: optional
    meditation:
      list:
        - name: "Dwelling Place"
          book: G
          priority: required
    recessional:
      list:
        - name: "The Church's One Foundation"
          book: G
          priority: required
  b:
    processional:
      list:
        - name: "Sing a New Song"
          composer: Schutte
          book: G
          priority: required
    psalm:
      list:
        - name: "I will praise you, Lord, in the assembly of the people."
          book: RA
          priority: required
    offertory:
      list:
        - name: "I Know That My Redeemer Lives"
          tune: DUKE STREET
          book: G
          priority: preferred
    communion:
      list:
        - name: "Unless a Grain of Wheat"
          book: G
          priority: preferred
    meditation:
      list:
        - name: "I Sing a Maid"
          book: G
          note: "all verses"
          priority: required
    recessional:
      list:
        - name: "Joyful, Joyful, We Adore You"
          book: G
          priority: preferred
  c:
    processional:
      list:
        - name: "Sing a New Song"
          composer: Schutte
          book: G
          priority: required
    psalm:
      list:
        - name: "I will praise your name for ever, my king and my God."
          book: RA
          priority: required
    offertory:
      list:
        - name: "I Know That My Redeemer Lives"
          tune: "DUKE STREET"
          book: G
          priority: preferred
    communion:
      list:
        - name: "Bread of Life from Heaven"
          book: G
          priority: preferred
    meditation:
      list:
        - name: "Jerusalem, My Happy Home"
          book: G
          priority: required
    recessional:
      list:
        - name: "Joyful, Joyful, We Adore You"
          book: G
          priority: preferred
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} ministry, service, diaconate, chosen people, faith in action  
[Year B:]{.red} ministry, service, diaconate, chosen people, faith in action   
[Year C:]{.red} love, remain in Christ, Church, discipleship

:::  {.red}
#### **Entrance Antiphon**
:::

> O sing a new song to the Lord.  
> for he has worked wonders;  
> in the sight of the nations  
> he has shown his deliverance, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> Father, I wish that where I am,  
> those you gave me may also be with me,  
> that they may see the glory that you gave me, alleluia.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Acts 6:1-7]{style="float:right" .small}
:::

As the number of disciples continued to grow,  
the Hellenists complained against the Hebrews  
because their widows  
were being neglected in the daily distribution.  
So the Twelve called together the community of the disciples and said,  
"It is not right for us to neglect the word of God to serve at table.  
Brothers, select from among you seven reputable men,  
filled with the Spirit and wisdom,  
whom we shall appoint to this task,  
whereas we shall devote ourselves to prayer  
and to the ministry of the word."  
The proposal was acceptable to the whole community,  
so they chose Stephen, a man filled with faith and the Holy Spirit,  
also Philip, Prochorus, Nicanor, Timon, Parmenas,  
and Nicholas of Antioch, a convert to Judaism.  
They presented these men to the apostles  
who prayed and laid hands on them.  
The word of God continued to spread,  
and the number of the disciples in Jerusalem increased greatly;  
even a large group of priests were becoming obedient to the faith.  

***

::: {.red}
#### Responsorial Psalm [Psalm 33:1-2, 4-5, 18-19]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, let your mercy be on us, as we place our trust in you.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Exult, you just, in the LORD;  
praise from the upright is fitting.  
Give thanks to the LORD on the harp;  
with the ten-stringed lyre chant his praises. **[℟.]{.red}**  

Upright is the word of the LORD,  
and all his works are trustworthy.  
He loves justice and right;  
of the kindness of the LORD the earth is full. **[℟.]{.red}**  

See, the eyes of the LORD are upon those who fear him,  
upon those who hope for his kindness,  
To deliver them from death  
and preserve them in spite of famine. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Peter 2:4-9]{style="float:right" .small}
:::

Beloved:  
Come to him, a living stone, rejected by human beings  
but chosen and precious in the sight of God,  
and, like living stones,  
let yourselves be built into a spiritual house  
to be a holy priesthood to offer spiritual sacrifices  
acceptable to God through Jesus Christ.  
For it says in Scripture:  
*Behold, I am laying a stone in Zion,*  
*a cornerstone, chosen and precious,*  
and whoever believes in it shall not be put to shame.  
Therefore, its value is for you who have faith, but for those without faith:  
*The stone that the builders rejected*  
*has become the cornerstone*, and  
*A stone that will make people stumble,*  
*and a rock that will make them fall.*  
They stumble by disobeying the word, as is their destiny.  

You are "a chosen race, a royal priesthood,  
a holy nation, a people of his own,  
so that you may announce the praises" of him  
who called you out of darkness into his wonderful light.  

***

::: {.red}
#### Gospel Acclamation [John 14:6]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I am the way, the truth and the life, says the Lord;  
no one comes to the Father, except through me. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 14:1-12]{style="float:right" .small}
:::

Jesus said to his disciples:  
"Do not let your hearts be troubled.  
You have faith in God; have faith also in me.  
In my Father's house there are many dwelling places.  
If there were not,  
would I have told you that I am going to prepare a place for you?  
And if I go and prepare a place for you,  
I will come back again and take you to myself,  
so that where I am you also may be.  
Where I am going you know the way."  
Thomas said to him,  
"Master, we do not know where you are going;  
how can we know the way?"  
Jesus said to him, I am the way and the truth and the life.  
No one comes to the Father except through me.  
If you know me, then you will also know my Father.  
From now on you do know him and have seen him."  
Philip said to him,  
"Master, show us the Father, and that will be enough for us."  
Jesus said to him, "Have I been with you for so long a time  
and you still do not know me, Philip?  
Whoever has seen me has seen the Father.  
How can you say, 'Show us the Father'?  
Do you not believe that I am in the Father and the Father is in me?  
The words that I speak to you I do not speak on my own.  
The Father who dwells in me is doing his works.  
Believe me that I am in the Father and the Father is in me,  
or else, believe because of the works themselves.  
Amen, amen, I say to you,  
whoever believes in me will do the works that I do,  
and will do greater ones than these,  
because I am going to the Father."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Acts 9:26-31]{style="float:right" .small}
:::

When Saul arrived in Jerusalem he tried to join the disciples,  
but they were all afraid of him,  
not believing that he was a disciple.  
Then Barnabas took charge of him and brought him to the apostles,  
and he reported to them how he had seen the Lord,  
and that he had spoken to him,  
and how in Damascus he had spoken out boldly in the name of Jesus.  
He moved about freely with them in Jerusalem,  
and spoke out boldly in the name of the Lord.  
He also spoke and debated with the Hellenists,  
but they tried to kill him.  
And when the brothers learned of this,  
they took him down to Caesarea  
and sent him on his way to Tarsus.  

The church throughout all Judea, Galilee, and Samaria was at peace.  
It was being built up and walked in the fear of the Lord,  
and with the consolation of the Holy Spirit it grew in numbers.  

***

::: {.red}
#### Responsorial Psalm [Psalm 22:26-27, 28, 30, 31-32]{style="float:right" .small}
:::

**[℟.]{.red}** **I will praise you, Lord, in the assembly of your people.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

I will fulfill my vows before those who fear the LORD.  
The lowly shall eat their fill;  
they who seek the LORD shall praise him:  
"May your hearts live forever!" **[℟.]{.red}**  

All the ends of the earth  
shall remember and turn to the LORD;  
all the families of the nations  
shall bow down before him. **[℟.]{.red}**  

To him alone shall bow down  
all who sleep in the earth;  
before him shall bend  
all who go down into the dust. **[℟.]{.red}**  

And to him my soul shall live;  
my descendants shall serve him.  
Let the coming generation be told of the LORD  
that they may proclaim to a people yet to be born  
the justice he has shown. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 John 3:18-24]{style="float:right" .small}
:::

Children, let us love not in word or speech  
but in deed and truth.  
Now this is how we shall know that we belong to the truth  
and reassure our hearts before him  
in whatever our hearts condemn,  
for God is greater than our hearts and knows everything.  
Beloved, if our hearts do not condemn us,  
we have confidence in God  
and receive from him whatever we ask,  
because we keep his commandments and do what pleases him.  
And his commandment is this:  
we should believe in the name of his Son, Jesus Christ,  
and love one another just as he commanded us.  
Those who keep his commandments remain in him, and he in them,  
and the way we know that he remains in us  
is from the Spirit he gave us.  

***

::: {.red}
#### Gospel Acclamation [John 15:4a, 5b]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Remain in me as I remain in you, says the Lord.  
Whoever remains in me will bear much fruit. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 15:1-8]{style="float:right" .small}
:::

Jesus said to his disciples:  
"I am the true vine, and my Father is the vine grower.  
He takes away every branch in me that does not bear fruit,  
and every one that does he prunes so that it bears more fruit.  
You are already pruned because of the word that I spoke to you.  
Remain in me, as I remain in you.  
Just as a branch cannot bear fruit on its own  
unless it remains on the vine,  
so neither can you unless you remain in me.  
I am the vine, you are the branches.  
Whoever remains in me and I in him will bear much fruit,  
because without me you can do nothing.  
Anyone who does not remain in me  
will be thrown out like a branch and wither;  
people will gather them and throw them into a fire  
and they will be burned.  
If you remain in me and my words remain in you,  
ask for whatever you want and it will be done for you.  
By this is my Father glorified,  
that you bear much fruit and become my disciples."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Acts 14:21-27]{style="float:right" .small}
:::

After Paul and Barnabas had proclaimed the good news
to that city  
and made a considerable number of disciples,  
they returned to Lystra and to Iconium and to Antioch.  
They strengthened the spirits of the disciples  
and exhorted them to persevere in the faith, saying,  
“It is necessary for us to undergo many hardships  
to enter the kingdom of God.”  
They appointed elders for them in each church and,  
with prayer and fasting, commended them to the Lord  
in whom they had put their faith.  
Then they traveled through Pisidia and reached Pamphylia.  
After proclaiming the word at Perga they went down to Attalia.  
From there they sailed to Antioch,  
where they had been commended to the grace of God  
for the work they had now accomplished.  
And when they arrived, they called the church together  
and reported what God had done with them  
and how he had opened the door of faith to the Gentiles.  

***

::: {.red}
#### Responsorial Psalm [Psalm 145:8-9, 10-11, 12-13]{style="float:right" .small}
:::

**[℟.]{.red}** **I will praise your name for ever, my king and my God.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

The LORD is gracious and merciful,  
&emsp; slow to anger and of great kindness.  
The LORD is good to all  
&emsp; and compassionate toward all his works. **[℟.]{.red}**  

Let all your works give you thanks, O LORD,  
&emsp; and let your faithful ones bless you.  
Let them discourse of the glory of your kingdom  
&emsp; and speak of your might. **[℟.]{.red}**  

Let them make known your might to the children of Adam,  
&emsp; and the glorious splendor of your kingdom.  
Your kingdom is a kingdom for all ages,  
&emsp; and your dominion endures through all generations. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Revelation 21:1-5a]{style="float:right" .small}
:::

Then I, John, saw a new heaven and a new earth.  
The former heaven and the former earth had passed away,  
and the sea was no more.  
I also saw the holy city, a new Jerusalem,  
coming down out of heaven from God,  
prepared as a bride adorned for her husband.  
I heard a loud voice from the throne saying,  
“Behold, God’s dwelling is with the human race.  
He will dwell with them and they will be his people  
and God himself will always be with them as their God.  
He will wipe every tear from their eyes,  
and there shall be no more death or mourning, wailing or pain,  
for the old order has passed away.”  

The One who sat on the throne said,  
“Behold, I make all things new.”  

***

::: {.red}
#### Gospel Acclamation [John 13:34]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I give you a new commandment, says the Lord:  
love one another as I have loved you. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [John 13:31-33a, 34-35]{style="float:right" .small}
:::

When Judas had left them, Jesus said,  
“Now is the Son of Man glorified, and God is glorified in him.  
If God is glorified in him,  
God will also glorify him in himself,  
and God will glorify him at once.  
My children, I will be with you only a little while longer.  
I give you a new commandment: love one another.  
As I have loved you, so you also should love one another.  
This is how all will know that you are my disciples,  
if you have love for one another.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```
