---
title: "FOURTH SUNDAY OF EASTER"
subtitle: "Good Shepherd Sunday"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Sing With All the Saints in Glory"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "The Lord is my shepherd; there is nothing I shall want."
          book: RA
          priority: preferred
        - name: "Psalm 23: My Shepherd is the Lord"
          book: G
          priority: optional
    offertory:
      list:
        - name: "The King of Love My Shepherd Is"
          book: G
          priority: required
    communion:
      list:
        - name: "Easter Alleluia"
          book: G
          priority: required
    meditation:
      list:
        - name: "Jubiláte, Sérvite"
          book: G
          priority: preferred
    recessional:
      list:
        - name: "The Strife is O'er"
          book: G
          priority: preferred
  b:
    processional:
      list:
        - name: "Sing with All the Saints in Glory"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "The stone rejected by the builders has become the cornerstone."
          book: RA
          priority: required
    offertory:
      list:
        - name: "You, Lord, Are Both Lamb and Shepherd"
          book: G
          priority: required
    communion:
      list:
        - name: "Easter Alleluia"
          book: G
          priority: required
    meditation:
      list:
        - name: "Heart of a Shepherd"
          book: G
          priority: required
    recessional:
      list:
        - name: "The Church's One Foundation"
          book: G
          priority: required
  c:
    processional:
      list:
        - name: "At the Lamb's High Feast We Sing"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "We are his people, the sheep of his flock."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Psalm 23: Shepherd Me, O God"
          book: G
          priority: required
    communion:
      list:
        - name: "Easter Alleluia"
          book: G
          priority: required
    meditation:
      list:
        - name: "Shepherd of My Heart"
          book: G
          priority: preferred
    recessional:
      list:
        - name: "Sing With All the Saints in Glory"
          book: G
          priority: preferred
  abc:
    anthems:
      list:
        - name: "He Shall Feed His Flock"
          note: "Handel's Messiah"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

Good Shepherd, trust, safety, suﬀering, discernment

:::  {.red}
#### **Entrance Antiphon**
:::

> The merciful love of the Lord fills the earth;  
> by the word of the Lord the heavens were made, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> The Good Shepherd has risen,  
> who laid down his life for his sheep  
> and willingly died for his flock, alleluia.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Acts 2:14a, 36-41]{style="float:right" .small}
:::

Then Peter stood up with the Eleven,  
raised his voice, and proclaimed:  
"Let the whole house of Israel know for certain  
that God has made both Lord and Christ,  
this Jesus whom you crucified."  

Now when they heard this, they were cut to the heart,  
and they asked Peter and the other apostles,  
"What are we to do, my brothers?"  
Peter said to them,  
"Repent and be baptized, every one of you,  
in the name of Jesus Christ for the forgiveness of your sins;  
and you will receive the gift of the Holy Spirit.  
For the promise is made to you and to your children  
and to all those far off,  
whomever the Lord our God will call."  
He testified with many other arguments, and was exhorting them,  
"Save yourselves from this corrupt generation."  
Those who accepted his message were baptized,  
and about three thousand persons were added that day.  

***

::: {.red}
#### Responsorial Psalm [Psalm 23: 1-3a, 3b4, 5, 6]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is my shepherd; there is nothing I shall want.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

The LORD is my shepherd; I shall not want.  
In verdant pastures he gives me repose;  
beside restful waters he leads me;  
he refreshes my soul. **[℟.]{.red}**  

He guides me in right paths  
for his name's sake.  
Even though I walk in the dark valley  
I fear no evil; for you are at my side.  
With your rod and your staff  
that give me courage. **[℟.]{.red}**  

You spread the table before me  
in the sight of my foes;  
you anoint my head with oil;  
my cup overflows. **[℟.]{.red}**  

Only goodness and kindness follow me  
all the days of my life;  
and I shall dwell in the house of the LORD  
for years to come. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Peter 2:20b-25]{style="float:right" .small}
:::

Beloved:  
If you are patient when you suffer for doing what is good,  
this is a grace before God.  
For to this you have been called,  
because Christ also suffered for you,  
leaving you an example that you should follow in his footsteps.  
*He committed no sin, and no deceit was found in his mouth.*  

When he was insulted, he returned no insult;  
when he suffered, he did not threaten;  
instead, he handed himself over to the one who judges justly.  
He himself bore our sins in his body upon the cross,  
so that, free from sin, we might live for righteousness.  
By his wounds you have been healed.  
For you had gone astray like sheep,  
but you have now returned to the shepherd and guardian of your souls.  

***

::: {.red}
#### Gospel Acclamation [John 10:14]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I am the good shepherd, says the Lord;  
I know my sheep, and mine know me. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 10:1-10]{style="float:right" .small}
:::

Jesus said:  
"Amen, amen, I say to you,  
whoever does not enter a sheepfold through the gate  
but climbs over elsewhere is a thief and a robber.  
But whoever enters through the gate is the shepherd of the sheep.  
The gatekeeper opens it for him, and the sheep hear his voice,  
as the shepherd calls his own sheep by name and leads them out.  
When he has driven out all his own,  
he walks ahead of them, and the sheep follow him,  
because they recognize his voice.  
But they will not follow a stranger;  
they will run away from him,  
because they do not recognize the voice of strangers."  
Although Jesus used this figure of speech,  
the Pharisees did not realize what he was trying to tell them.  

So Jesus said again, "Amen, amen, I say to you,  
I am the gate for the sheep.  
All who came before me are thieves and robbers,  
but the sheep did not listen to them.  
I am the gate.  
Whoever enters through me will be saved,  
and will come in and go out and find pasture.  
A thief comes only to steal and slaughter and destroy;  
I came so that they might have life and have it more abundantly."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Acts 4:8-12]{style="float:right" .small}
:::

Peter, filled with the Holy Spirit, said:  
"Leaders of the people and elders:  
If we are being examined today  
about a good deed done to a cripple,  
namely, by what means he was saved,  
then all of you and all the people of Israel should know  
that it was in the name of Jesus Christ the Nazorean  
whom you crucified, whom God raised from the dead;  
in his name this man stands before you healed.  
*He is the stone rejected by you, the builders,*  
*which has become the cornerstone.*  
There is no salvation through anyone else,  
nor is there any other name under heaven  
given to the human race by which we are to be saved."  

***

::: {.red}
#### Responsorial Psalm [Psalm 118:1, 8-9, 21-23, 26, 28, 29]{style="float:right" .small}
:::

**[℟.]{.red}** **The stone rejected by the builders has become the cornerstone.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Give thanks to the LORD, for he is good,  
for his mercy endures forever.  
It is better to take refuge in the LORD  
than to trust in man.  
It is better to take refuge in the LORD  
than to trust in princes. **[℟.]{.red}**  

I will give thanks to you, for you have answered me  
and have been my savior.  
The stone which the builders rejected  
has become the cornerstone.  
By the LORD has this been done;  
it is wonderful in our eyes. **[℟.]{.red}**  

Blessed is he who comes in the name of the LORD;  
we bless you from the house of the LORD.  
I will give thanks to you, for you have answered me  
and have been my savior.  
Give thanks to the LORD, for he is good;  
for his kindness endures forever. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 John 3:1-2]{style="float:right" .small}
:::

Beloved:  
See what love the Father has bestowed on us  
that we may be called the children of God.  
Yet so we are.  
The reason the world does not know us  
is that it did not know him.  
Beloved, we are God's children now;  
what we shall be has not yet been revealed.  
We do know that when it is revealed we shall be like him,  
for we shall see him as he is.  

***

::: {.red}
#### Gospel Acclamation [John 10:14]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I am the good shepherd, says the Lord;  
I know my sheep, and mine know me. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 10:11-18]{style="float:right" .small}
:::

Jesus said:  
"I am the good shepherd.  
A good shepherd lays down his life for the sheep.  
A hired man, who is not a shepherd  
and whose sheep are not his own,  
sees a wolf coming and leaves the sheep and runs away,  
and the wolf catches and scatters them.  
This is because he works for pay and has no concern for the sheep.  
I am the good shepherd,  
and I know mine and mine know me,  
just as the Father knows me and I know the Father;  
and I will lay down my life for the sheep.  
I have other sheep that do not belong to this fold.  
These also I must lead, and they will hear my voice,  
and there will be one flock, one shepherd.  
This is why the Father loves me,  
because I lay down my life in order to take it up again.  
No one takes it from me, but I lay it down on my own.  
I have power to lay it down, and power to take it up again.  
This command I have received from my Father."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Acts 13:14, 43-52]{style="float:right" .small}
:::

Paul and Barnabas continued on from Perga  
and reached Antioch in Pisidia.  
On the sabbath they entered the synagogue and took their seats.  
Many Jews and worshipers who were converts to Judaism  
followed Paul and Barnabas, who spoke to them  
and urged them to remain faithful to the grace of God.  

On the following sabbath almost the whole city gathered  
to hear the word of the Lord.  
When the Jews saw the crowds, they were filled with jealousy  
and with violent abuse contradicted what Paul said.  
Both Paul and Barnabas spoke out boldly and said,  
“It was necessary that the word of God be spoken to you first,  
but since you reject it  
and condemn yourselves as unworthy of eternal life,  
we now turn to the Gentiles.  
*For so the Lord has commanded us,*  
*I have made you a light to the Gentiles,*  
*that you may be an instrument of salvation*  
*to the ends of the earth.”*  

The Gentiles were delighted when they heard this  
and glorified the word of the Lord.  
All who were destined for eternal life came to believe,  
and the word of the Lord continued to spread  
through the whole region.  
The Jews, however, incited the women of prominence who were worshipers  
and the leading men of the city,  
stirred up a persecution against Paul and Barnabas,  
and expelled them from their territory.  
So they shook the dust from their feet in protest against them,  
and went to Iconium.  
The disciples were filled with joy and the Holy Spirit.  

***

::: {.red}
#### Responsorial Psalm [Psalm 100:1-2, 3, 5]{style="float:right" .small}
:::

**[℟.]{.red}** **We are his people, the sheep of his flock.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Sing joyfully to the LORD, all you lands;  
&emsp; serve the LORD with gladness;  
&emsp; come before him with joyful song. **[℟.]{.red}**  

Know that the LORD is God;  
&emsp; he made us, his we are;  
&emsp; his people, the flock he tends. **[℟.]{.red}**  

The LORD is good:  
&emsp; his kindness endures forever,  
&emsp; and his faithfulness, to all generations. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Revelation 7:9, 14b-17]{style="float:right" .small}
:::

I, John, had a vision of a great multitude,  
which no one could count,  
from every nation, race, people, and tongue.  
They stood before the throne and before the Lamb,  
wearing white robes and holding palm branches in their hands.  

Then one of the elders said to me,  
“These are the ones who have survived the time of great distress;  
they have washed their robes  
and made them white in the blood of the Lamb.  

&emsp; “For this reason they stand before God’s throne  
&emsp; &emsp; and worship him day and night in his temple.  
&emsp; The one who sits on the throne will shelter them.  
&emsp; They will not hunger or thirst anymore,  
&emsp; &emsp; nor will the sun or any heat strike them.  
&emsp; For the Lamb who is in the center of the throne  
&emsp; &emsp; will shepherd them  
&emsp; &emsp; and lead them to springs of life-giving water,  
&emsp; &emsp; and God will wipe away every tear from their eyes.”  

***

::: {.red}
#### Gospel Acclamation [John 10:14]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
I am the good shepherd, says the Lord;  
I know my sheep, and mine know me. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [John 10:27-30]{style="float:right" .small}
:::

Jesus said:  
“My sheep hear my voice;  
I know them, and they follow me.  
I give them eternal life, and they shall never perish.  
No one can take them out of my hand.  
My Father, who has given them to me, is greater than all,  
and no one can take them out of the Father’s hand.  
The Father and I are one.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The Fourth Sunday of Easter is also **Good Shepherd Sunday**.
