---
title: "VIGIL OF PENTECOST"
subtitle: "Simple Form"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Come, Holy Ghost"
          book: G
          priority: required
    psalm:
      list:
        - name: "Lord, send out your Spirit, and renew the face of the earth."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Rain Down"
          book: G
          priority: optional
        - name: "O Breathe on Me, O Breath of God"
          book: G
          priority: optional
    communion:
      list:
        - name: "Come to the Water"
          composer: Foley
          book: G
          priority: optional
        - name: "Peace Is Flowing Like a River"
          book: G
          priority: optional
    meditation:
      list:
        - name: "Jesus, Your Spirit in Us"
          book: G
          priority: required
    recessional:
      list:
        - name: "Sing a New Church"
          book: G
          priority: optional
        - name: "O Spirit All-Embracing"
          book: G
          priority: optional
    anthems:
      list:
        - name: "O How Amiable"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

light, language, the Spirit's imminence, renewal

:::  {.red}
#### **Entrance Antiphon**
:::

> The love of God has been poured into our hearts  
> through the Spirit of God dwelling within us, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> On the last day of the festival, Jesus stood and cried out:  
> If anyone is thirsty, let him come to me and drink, alleluia.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Genesis 11:1-9]{style="float:right" .small}
:::

The whole world spoke the same language, using the same words.  
While the people were migrating in the east,  
they came upon a valley in the land of Shinar and settled there.  
They said to one another,  
"Come, let us mold bricks and harden them with fire."  
They used bricks for stone, and bitumen for mortar.  
Then they said, "Come, let us build ourselves a city  
and a tower with its top in the sky,  
and so make a name for ourselves;  
otherwise we shall be scattered all over the earth."  

The LORD came down to see the city and the tower  
that the people had built.  
Then the LORD said: "If now, while they are one people,  
all speaking the same language,  
they have started to do this,  
nothing will later stop them from doing whatever they presume to do.  
Let us then go down there and confuse their language,  
so that one will not understand what another says."  
Thus the LORD scattered them from there all over the earth,  
and they stopped building the city.  
That is why it was called Babel,  
because there the LORD confused the speech of all the world.  
It was from that place that he scattered them all over the earth.  

[Or:]{.red} [Exodus 19:3-8a, 16-20b]{style="float:right" .small .red}  

Moses went up the mountain to God.  
Then the LORD called to him and said,  
"Thus shall you say to the house of Jacob;  
tell the Israelites:  
You have seen for yourselves how I treated the Egyptians  
and how I bore you up on eagle wings  
and brought you here to myself.  
Therefore, if you hearken to my voice and keep my covenant,  
you shall be my special possession,  
dearer to me than all other people,  
though all the earth is mine.  
You shall be to me a kingdom of priests, a holy nation.  
That is what you must tell the Israelites."  
So Moses went and summoned the elders of the people.  
When he set before them  
all that the LORD had ordered him to tell them,  
the people all answered together,  
"Everything the LORD has said, we will do."  

On the morning of the third day  
there were peals of thunder and lightning,  
and a heavy cloud over the mountain,  
and a very loud trumpet blast,  
so that all the people in the camp trembled.  
But Moses led the people out of the camp to meet God,  
and they stationed themselves at the foot of the mountain.  
Mount Sinai was all wrapped in smoke,  
for the LORD came down upon it in fire.  
The smoke rose from it as though from a furnace,  
and the whole mountain trembled violently.  
The trumpet blast grew louder and louder, while Moses was speaking,  
and God answering him with thunder.  

When the LORD came down to the top of Mount Sinai,  
he summoned Moses to the top of the mountain.  

[Or:]{.red} [Ezekiel 37:1-14]{style="float:right" .small .red}  

The hand of the LORD came upon me,  
and he led me out in the spirit of the LORD  
and set me in the center of the plain,  
which was now filled with bones.  
He made me walk among the bones in every direction  
so that I saw how many they were on the surface of the plain.  
How dry they were!  
He asked me:  
Son of man, can these bones come to life?  
I answered, "Lord GOD, you alone know that."  
Then he said to me:  
Prophesy over these bones, and say to them:  
Dry bones, hear the word of the LORD!  
Thus says the Lord GOD to these bones:  
See! I will bring spirit into you, that you may come to life.  
I will put sinews upon you, make flesh grow over you,  
cover you with skin, and put spirit in you  
so that you may come to life and know that I am the LORD.  
I, Ezekiel, prophesied as I had been told,  
and even as I was prophesying I heard a noise;  
it was a rattling as the bones came together, bone joining bone.  
I saw the sinews and the flesh come upon them,  
and the skin cover them, but there was no spirit in them.  
Then the LORD said to me:  
Prophesy to the spirit, prophesy, son of man,  
and say to the spirit: Thus says the Lord GOD:  
From the four winds come, O spirit,  
and breathe into these slain that they may come to life.  
I prophesied as he told me, and the spirit came into them;  
they came alive and stood upright, a vast army.  
Then he said to me:  
Son of man, these bones are the whole house of Israel.  
They have been saying,  
"Our bones are dried up,  
our hope is lost, and we are cut off."  
Therefore, prophesy and say to them: Thus says the Lord GOD:  
O my people, I will open your graves  
and have you rise from them,  
and bring you back to the land of Israel.  
Then you shall know that I am the LORD,  
when I open your graves and have you rise from them,  
O my people!  
I will put my spirit in you that you may live,  
and I will settle you upon your land;  
thus you shall know that I am the LORD.  
I have promised, and I will do it, says the LORD.  

[Or:]{.red} [Joel 3:1-5]{style="float:right" .small .red}

Thus says the LORD:  
I will pour out my spirit upon all flesh.  
Your sons and daughters shall prophesy,  
your old men shall dream dreams,  
your young men shall see visions;  
even upon the servants and the handmaids,  
in those days, I will pour out my spirit.  
And I will work wonders in the heavens and on the earth,  
blood, fire, and columns of smoke;  
the sun will be turned to darkness,  
and the moon to blood,  
at the coming of the day of the LORD,  
the great and terrible day.  
Then everyone shall be rescued  
who calls on the name of the LORD;  
for on Mount Zion there shall be a remnant,  
as the LORD has said,  
and in Jerusalem survivors  
whom the LORD shall call.  

***

::: {.red}
#### Responsorial Psalm [Psalm 104:1-2, 24, 35, 27-28, 29-30]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, send out your Spirit, and renew the face of the earth.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Bless the LORD, O my soul!  
O LORD, my God, you are great indeed!  
You are clothed with majesty and glory,  
robed in light as with a cloak. **[℟.]{.red}**  

How manifold are your works, O LORD!  
In wisdom you have wrought them all—  
the earth is full of your creatures;  
bless the LORD, O my soul! Alleluia. **[℟.]{.red}**  

Creatures all look to you  
to give them food in due time.  
When you give it to them, they gather it;  
when you open your hand, they are filled with good things. **[℟.]{.red}**  

If you take away their breath, they perish  
and return to their dust.  
When you send forth your spirit, they are created,  
and you renew the face of the earth. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Romans 8:22-27]{style="float:right" .small}
:::

Brothers and sisters:  
We know that all creation is groaning in labor pains even until now;  
and not only that, but we ourselves,  
who have the firstfruits of the Spirit,  
we also groan within ourselves  
as we wait for adoption, the redemption of our bodies.  
For in hope we were saved.  
Now hope that sees is not hope.  
For who hopes for what one sees?  
But if we hope for what we do not see, we wait with endurance.  

In the same way, the Spirit too comes to the aid of our weakness;  
for we do not know how to pray as we ought,  
but the Spirit himself intercedes with inexpressible groanings.  
And the one who searches hearts  
knows what is the intention of the Spirit,  
because he intercedes for the holy ones  
according to God's will.  

***

::: {.red}
#### Gospel Acclamation
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Come, Holy Spirit, fill the hearts of your faithful  
and kindle in them the fire of your love. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 7:37-39]{style="float:right" .small}
:::

Jesus stood up and exclaimed,  
"Let anyone who thirsts come to me and drink.  
As Scripture says:  
*Rivers of living water will flow from within him who believes in me.*"  

He said this in reference to the Spirit  
that those who came to believe in him were to receive.  
There was, of course, no Spirit yet,  
because Jesus had not yet been glorified.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* An optional [**Extended Vigil**](pentecost-vigil-extended.qmd) may be celebrated. The music minister should be sure to consult with the presider before the liturgy to know which form is being used.
* The presider may opt to use the same readings as Pentecost Sunday.
In this case, the music selections are taken from [Pentecost Sunday](pentecost.qmd), not from this list. The music minister must coordinate this with the presider before the start of the liturgy.
* If available, the Festival Alleluia (GIA), with the **Pentecost** verse found in [Appendix B](../appendices/B-festival-alleluia.qmd), is sung for the **Gospel Acclamation**.
* If the **dismissal of the people** is chanted by the presider, the cantor must promptly – without pause or hesitation – lead the chanted response found in [Appendix F](../easter/pentecost-vigil.qmd).
