---
title: "PENTECOST SUNDAY"
subtitle: "Mass During the Day"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Come, Holy Ghost"
          book: G
          priority: required
    psalm:
      list:
        - name: "Lord, send out your Spirit, and renew the face of the earth."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for Pentecost Sunday"
          note: "psalmody version"
          book: "[Appx G](../appendices/G-pentecost-sequence.qmd)"
          priority: required
    offertory:
      list:
        - name: "O Breathe On Me, O Breath of God"
          book: G
          priority: required
    communion:
      list:
        - name: "We Are Many Parts"
          book: G
          priority: required
    meditation:
      list:
        - name: "Diverse in Culture, Nation, Race"
          book: G
          priority: required
    recessional:
      list:
        - name: "Go to the World!"
          book: G
          priority: required
  b:
    processional:
      list:
        - name: "Come, Holy Ghost"
          book: G
          priority: required
    psalm:
      list:
        - name: "Lord, send out your Spirit, and renew the face of the earth."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for Pentecost Sunday"
          note: "psalmody version"
          book: "[Appx G](../appendices/G-pentecost-sequence.qmd)"
          priority: required
    offertory:
      list:
        - name: "O Spirit All-Embracing"
          book: G
          priority: required
    communion:
      list:
        - name: "Come Down, O Love Divine"
          book: G
          priority: required
    meditation:
      list:
        - name: "Dona Nobis Pacem"
          book: G
          priority: required
    recessional:
      list:
        - name: "Lord, You Give the Great Commission"
          book: G
          priority: required
  c:
    processional:
      list:
        - name: "Come, Holy Ghost"
          book: G
          priority: required
    psalm:
      list:
        - name: "Lord, send out your Spirit, and renew the face of the earth."
          book: RA
          priority: required
    sequence:
      list:
        - name: "Sequence for Pentecost Sunday"
          note: "psalmody version"
          book: "[Appx G](../appendices/G-pentecost-sequence.qmd)"
          priority: required
    offertory:
      list:
        - name: "God, Whose Purpose is to Kindle"
          book: G
          priority: required
    communion:
      list:
        - name: "One Bread, One Body"
          book: G
          priority: required
    meditation:
      list:
        - name: "Peace, Be Not Anxious"
          book: G
          priority: required
    recessional:
      list:
        - name: "O Spirit All-Embracing"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

Holy Spirit, language, ministry, Church, peace

:::  {.red}
#### **Entrance Antiphon**
:::

> The Spirit of the Lord has filled the whole world  
> and that which contains all things  
> understands what is said, alleluia.  
>  
> [Or:]{.red}  
>  
> The love of God has been poured into our hearts  
> through the Spirit of God dwelling within us, alleluia.

:::  {.red}
#### **Communion Antiphon**
:::

> They were all filled with the Holy Spirit  
> and spoke of the marvels of God, alleluia.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Acts 2:1-11]{style="float:right" .small}
:::

When the time for Pentecost was fulfilled,  
they were all in one place together.  
And suddenly there came from the sky  
a noise like a strong driving wind,  
and it filled the entire house in which they were.  
Then there appeared to them tongues as of fire,  
which parted and came to rest on each one of them.  
And they were all filled with the Holy Spirit  
and began to speak in different tongues,  
as the Spirit enabled them to proclaim.  

Now there were devout Jews from every nation under heaven  
staying in Jerusalem.  
At this sound, they gathered in a large crowd,  
but they were confused  
because each one heard them speaking in his own language.  
They were astounded, and in amazement they asked,  
"Are not all these people who are speaking Galileans?  
Then how does each of us hear them in his native language?  
We are Parthians, Medes, and Elamites,  
inhabitants of Mesopotamia, Judea and Cappadocia,  
Pontus and Asia, Phrygia and Pamphylia,  
Egypt and the districts of Libya near Cyrene,  
as well as travelers from Rome,  
both Jews and converts to Judaism, Cretans and Arabs,  
yet we hear them speaking in our own tongues  
of the mighty acts of God."  

***

::: {.red}
#### Responsorial Psalm [Psalm 104:1, 24, 29-30, 31, 34 ]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, send out your Spirit, and renew the face of the earth.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Bless the LORD, O my soul!  
O LORD, my God, you are great indeed!  
How manifold are your works, O LORD!  
the earth is full of your creatures; **[℟.]{.red}**  

May the glory of the LORD endure forever;  
may the LORD be glad in his works!  
Pleasing to him be my theme;  
I will be glad in the LORD. **[℟.]{.red}**  

If you take away their breath, they perish  
and return to their dust.  
When you send forth your spirit, they are created,  
and you renew the face of the earth. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Corinthians 12:3b-7, 12-13]{style="float:right" .small}
:::

Brothers and sisters:  
No one can say, "Jesus is Lord," except by the Holy Spirit.  

There are different kinds of spiritual gifts but the same Spirit;  
there are different forms of service but the same Lord;  
there are different workings but the same God  
who produces all of them in everyone.  
To each individual the manifestation of the Spirit  
is given for some benefit.  

As a body is one though it has many parts,  
and all the parts of the body, though many, are one body,  
so also Christ.  
For in one Spirit we were all baptized into one body,  
whether Jews or Greeks, slaves or free persons,  
and we were all given to drink of one Spirit.  

[Or:]{.red} [Galatians 5:16-25]{style="float:right" .small .red}

Brothers and sisters, live by the Spirit  
and you will certainly not gratify the desire of the flesh.  
For the flesh has desires against the Spirit,  
and the Spirit against the flesh;  
these are opposed to each other,  
so that you may not do what you want.  
But if you are guided by the Spirit, you are not under the law.  
Now the works of the flesh are obvious:  
immorality, impurity, lust, idolatry,  
sorcery, hatreds, rivalry, jealousy,  
outbursts of fury, acts of selfishness,  
dissensions, factions, occasions of envy,  
drinking bouts, orgies, and the like.  
I warn you, as I warned you before,  
that those who do such things will not inherit the kingdom of God.  
In contrast, the fruit of the Spirit is love, joy, peace,  
patience, kindness, generosity,  
faithfulness, gentleness, self-control.  
Against such there is no law.  
Now those who belong to Christ Jesus have crucified their flesh  
with its passions and desires.  
If we live in the Spirit, let us also follow the Spirit.  

[Or:]{.red} [Romans 8:8-17]{style="float:right" .small .red}

Brothers and sisters:  
Those who are in the flesh cannot please God.  
But you are not in the flesh;  
on the contrary, you are in the spirit,  
if only the Spirit of God dwells in you.  
Whoever does not have the Spirit of Christ does not belong to him.  
But if Christ is in you,  
although the body is dead because of sin,  
the spirit is alive because of righteousness.  
If the Spirit of the one who raised Jesus from the dead dwells in you,  
the one who raised Christ from the dead  
will give life to your mortal bodies also,  
through his Spirit that dwells in you.  
Consequently, brothers and sisters,  
we are not debtors to the flesh,  
to live according to the flesh.  
For if you live according to the flesh, you will die,  
but if by the Spirit you put to death the deeds of the body,  
you will live.  

For those who are led by the Spirit of God are sons of God.  
For you did not receive a spirit of slavery to fall back into fear,  
but you received a Spirit of adoption,  
through whom we cry, “Abba, Father!”  
The Spirit himself bears witness with our spirit  
that we are children of God,  
and if children, then heirs,  
heirs of God and joint heirs with Christ,  
if only we suffer with him  
so that we may also be glorified with him.  

***

::: {.red}
#### Sequence [*Veni, Sancte Spiritus*]{style="float:right" .small}
:::

Come, Holy Spirit, come!  
And from your celestial home  
Shed a ray of light divine!  

Come, Father of the poor!  
Come, source of all our store!  
Come, within our bosoms shine.  

You, of comforters the best;  
You, the soul's most welcome guest;  
Sweet refreshment here below;  

In our labor, rest most sweet;  
Grateful coolness in the heat;  
Solace in the midst of woe.  

O most blessed Light divine,  
Shine within these hearts of yours,  
And our inmost being fill!  

Where you are not, we have naught,  
Nothing good in deed or thought,  
Nothing free from taint of ill.  

Heal our wounds, our strength renew;  
On our dryness pour your dew;  
Wash the stains of guilt away:  

Bend the stubborn heart and will;  
Melt the frozen, warm the chill;  
Guide the steps that go astray.  

On the faithful, who adore  
And confess you, evermore  
In your sevenfold gift descend;  

Give them virtue's sure reward;  
Give them your salvation, Lord;  
Give them joys that never end. Amen.  
Alleluia.  

***

::: {.red}
#### Gospel Acclamation
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Come, Holy Spirit, fill the hearts of your faithful  
and kindle in them the fire of your love. **[℟.]{.red}**

***

::: {.red}
#### Gospel [John 20:19-23]{style="float:right" .small}
:::

On the evening of that first day of the week,  
when the doors were locked, where the disciples were,  
for fear of the Jews,  
Jesus came and stood in their midst  
and said to them, "Peace be with you."  
When he had said this, he showed them his hands and his side.  
The disciples rejoiced when they saw the Lord.  
Jesus said to them again, "Peace be with you.  
As the Father has sent me, so I send you."  
And when he had said this, he breathed on them and said to them,  
"Receive the Holy Spirit.  
Whose sins you forgive are forgiven them,  
and whose sins you retain are retained."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The **Sequence** is sung by the cantor only (*i.e.*, no choir) immediately after the Second Reading on Sunday morning only, *not* at the Saturday Vigil Mass. Accompaniment should be soft and reverent, like Meditation hymns.
* If available, the Festival Alleluia (GIA), with the **Pentecost**
verse found in [Appendix B](../appendices/B-festival-alleluia.qmd), is sung for the **Gospel Acclamation** immediately after the Sequence.
* If the **dismissal of the people** is chanted by the presider, the cantor must promptly-–without pause or hesitation--lead the chanted response found in [Appendix F](../easter/pentecost.qmd).