---
title: "ASH WEDNESDAY"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  abc:
    processional:
      list:
        - name: "Again We Keep This Solemn Fast"
          book: G
          priority: required
    psalm:
      list:
        - name: "Be merciful, O Lord, for we have sinned."
          book: RA
          priority: required
    distribution-of-ashes:
      list:
        - name: "Ashes"
          book: G
          priority: required
          year: A
        - name: "Merciful God (*Ash Wednesday*)"
          book: G
          priority: required
          year: B
        - name: "Remember You Are Dust"
          book: G
          priority: required
          year: C
    offertory:
      list:
        - name: "Hosea"
          book: G
          priority: required
    communion:
      list:
        - name: "Return to God"
          book: G
          priority: required
    meditation:
      list:
        - name: "God Is Forgiveness"
          book: G
          priority: required
          note: "*if/as needed*"
    recessional:
      list:
        - name: "Change Our Hearts"
          book: G
          priority: required
    anthems:
      list:
        - name: "This Is Our Accepted Time"
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

repentance, simplicity, sober reflection

:::  {.red}
#### **Entrance Antiphon**
:::

> You are merciful to all, O Lord  
> and despise nothing that you have made.  
> You overlook people's sins, to bring them to repentance,  
> and you spare them, for you are the Lord our God.

:::  {.red}
#### **Communion Antiphon**
:::

> He who ponders the law of the Lord day and night
will yield fruit in due season.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Years A, B, C
:::

::: {.red}
#### First Reading [Joel 2:12-18]{style="float:right" .small}
:::

Even now, says the LORD,  
return to me with your whole heart,  
with fasting, and weeping, and mourning;  
Rend your hearts, not your garments,  
and return to the LORD, your God.  
For gracious and merciful is he,  
slow to anger, rich in kindness,  
and relenting in punishment.  
Perhaps he will again relent  
and leave behind him a blessing,  
Offerings and libations  
for the LORD, your God.  

Blow the trumpet in Zion!  
proclaim a fast,  
call an assembly;  
Gather the people,  
notify the congregation;  
Assemble the elders,  
gather the children  
and the infants at the breast;  
Let the bridegroom quit his room  
and the bride her chamber.  
Between the porch and the altar  
let the priests, the ministers of the LORD, weep,  
And say, "Spare, O LORD, your people,  
and make not your heritage a reproach,  
with the nations ruling over them!  
Why should they say among the peoples,  
'Where is their God?'"  

Then the LORD was stirred to concern for his land  
and took pity on his people.

***

::: {.red}
#### Responsorial Psalm [Psalm 51:3-4, 5-6ab, 12-13, 14, 17]{style="float:right" .small}
:::

**[℟.]{.red}** **Be merciful, O Lord, for we have sinned.**  

Have mercy on me, O God, in your goodness;  
in the greatness of your compassion wipe out my offense.  
Thoroughly wash me from my guilt  
and of my sin cleanse me. **[℟.]{.red}**  

For I acknowledge my offense,  
and my sin is before me always:  
"Against you only have I sinned,  
and done what is evil in your sight." **[℟.]{.red}**  

A clean heart create for me, O God,  
and a steadfast spirit renew within me.  
Cast me not out from your presence,  
and your Holy Spirit take not from me. **[℟.]{.red}**  

Give me back the joy of your salvation,  
and a willing spirit sustain in me.  
O Lord, open my lips,  
and my mouth shall proclaim your praise. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [2 Corinthians 5:20—6:2]{style="float:right" .small}
:::

Brothers and sisters:  
We are ambassadors for Christ,  
as if God were appealing through us.  
We implore you on behalf of Christ,  
be reconciled to God.  
For our sake he made him to be sin who did not know sin,  
so that we might become the righteousness of God in him.  

Working together, then,  
we appeal to you not to receive the grace of God in vain.  
For he says:  

*In an acceptable time I heard you,*  
*and on the day of salvation I helped you.*  

Behold, now is a very acceptable time;  
behold, now is the day of salvation.

***

::: {.red}
#### Gospel Acclamation [Psalm 95:8]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
If today you hear his voice,
harden not your hearts. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Matthew 6:1-6, 16-18]{style="float:right" .small}
:::

Jesus said to his disciples:  
"Take care not to perform righteous deeds  
in order that people may see them;  
otherwise, you will have no recompense from your heavenly Father.  
When you give alms,  
do not blow a trumpet before you,  
as the hypocrites do in the synagogues and in the streets  
to win the praise of others.  
Amen, I say to you,  
they have received their reward.  
But when you give alms,  
do not let your left hand know what your right is doing,  
so that your almsgiving may be secret.  
And your Father who sees in secret will repay you.  

"When you pray,  
do not be like the hypocrites,  
who love to stand and pray in the synagogues and on street corners  
so that others may see them.  
Amen, I say to you,  
they have received their reward.  
But when you pray, go to your inner room,  
close the door, and pray to your Father in secret.  
And your Father who sees in secret will repay you.  

"When you fast,  
do not look gloomy like the hypocrites.  
They neglect their appearance,  
so that they may appear to others to be fasting.  
Amen, I say to you, they have received their reward.  
But when you fast,  
anoint your head and wash your face,  
so that you may not appear to be fasting,  
except to your Father who is hidden.  
And your Father who sees what is hidden will repay you."

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Years A, B, C
:::
{{< var text.yearabc >}}

```{python}
#| label: Year ABC
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['abc'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The Penitential Rite (***Kyrie eleison***) is omitted.
* The **Gloria** is omitted during Lent.