---
title: "FIRST SUNDAY OF LENT"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Lord, Who Throughout These Forty Days"
          verses: "1-3, at least"
          book: G
          priority: required
    psalm:
      list:
        - name: "Be merciful, O Lord, for we have sinned."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Forty Days and Forty Nights"
          book: G
          priority: required
    communion:
      list:
        - name: "Shepherd of Souls"
          book: G
          priority: required
    meditation:
      list:
        - name: "Psalm 91: Be With Me, Lord"
          book: G
          composer: Haugen
          priority: required
    recessional:
      list:
        - name: "Led By the Spirit"
          book: G
          priority: required
    anthems:
      list:
        - name: "Out Into the Wilderness"
  b:
    processional:
      list:
        - name: "Lord, Who Throughout These Forty Days"
          verses: "1-3, at least"
          book: G
          priority: required
    psalm:
      list:
        - name: "Your ways, O Lord, are love and truth to those who keep your covenant."
          book: G
          priority: required
    offertory:
      list:
        - name: "Led By the Spirit"
          book: G
          priority: required
    communion:
      list:
        - name: "On Eagle's Wings"
          book: G
          priority: required
    meditation:
      list:
        - name: "Gracious God"
          book: G
          priority: required
    recessional:
      list:
        - name: "Beyond the Days"
          book: G
          priority: required
    anthems:
      list:
        - name: "This is Our Accepted Time"
  c:
    processional:
      list:
        - name: "Forty Days and Forty Nights"
          book: G
          priority: required
    psalm:
      list:
        - name: "Be with me, Lord, when I am in trouble."
          book: RA
          priority: preferred
        - name: "Psalm 91: Be With Me, Lord"
          composer: Haugen
          book: G
          priority: optional
    offertory:
      list:
        - name: "You Are Near"
          book: G
          priority: required
    communion:
      list:
        - name: "On Eagle's Wings"
          book: G
          priority: required
    meditation:
      list:
        - name: "Psalm 91: Be With Me, Lord"
          composer: Haugen
          book: G
          priority: required
    recessional:
      list:
        - name: "Blest Be the Lord"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)
```

:::  {.red}
#### **Themes**
:::

penance, temptation, history of salvation, sin/grace

:::  {.red}
#### **Entrance Antiphon**
:::

> When he calls on me, I will answer him;  
> I will deliver him and give him glory,  
> I will grant him length of days.

:::  {.red}
#### **Communion Antiphon**
:::

> One does not live by bread alone,  
> but by every word that comes forth from the mouth of God.  
>  
> [Or:]{.red}  
>  
> The Lord will conceal you with his pinions,  
> and under his wings you will trust.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Genesis 2:7-9; 3:1-7]{style="float:right" .small}
:::

The LORD God formed man out of the clay of the ground  
and blew into his nostrils the breath of life,  
and so man became a living being.  

Then the LORD God planted a garden in Eden, in the east,  
and placed there the man whom he had formed.  
Out of the ground the LORD God made various trees grow  
that were delightful to look at and good for food,  
with the tree of life in the middle of the garden  
and the tree of the knowledge of good and evil.  

Now the serpent was the most cunning of all the animals  
that the LORD God had made.  
The serpent asked the woman,  
“Did God really tell you not to eat  
from any of the trees in the garden?”  
The woman answered the serpent:  
“We may eat of the fruit of the trees in the garden;  
it is only about the fruit of the tree  
in the middle of the garden that God said,  
‘You shall not eat it or even touch it, lest you die.’”  
But the serpent said to the woman:  
“You certainly will not die!  
No, God knows well that the moment you eat of it  
your eyes will be opened and you will be like gods  
who know what is good and what is evil.”  
The woman saw that the tree was good for food,  
pleasing to the eyes, and desirable for gaining wisdom.  
So she took some of its fruit and ate it;  
and she also gave some to her husband, who was with her,  
and he ate it.  
Then the eyes of both of them were opened,  
and they realized that they were naked;  
so they sewed fig leaves together  
and made loincloths for themselves.  

***

::: {.red}
#### Responsorial Psalm [Psalm 51:3-4, 5-6, 12-13, 17]{style="float:right" .small}
:::

**[℟.]{.red}** **Be merciful, O Lord, for we have sinned.**  

Have mercy on me, O God, in your goodness;  
in the greatness of your compassion wipe out my offense.  
Thoroughly wash me from my guilt  
and of my sin cleanse me. **[℟.]{.red}**  

For I acknowledge my offense,  
and my sin is before me always:  
“Against you only have I sinned,  
and done what is evil in your sight.” **[℟.]{.red}**  

A clean heart create for me, O God,  
and a steadfast spirit renew within me.  
Cast me not out from your presence,  
and your Holy Spirit take not from me. **[℟.]{.red}**. 

Give me back the joy of your salvation,  
and a willing spirit sustain in me.  
O Lord, open my lips,  
and my mouth shall proclaim your praise. **[℟.]{.red}**. 

***

::: {.red}
#### Second Reading [Romans 5:12-19 or 5:12, 17-19]{style="float:right" .small}
:::

Brothers and sisters:  
Through one man sin entered the world,  
and through sin, death,  
and thus death came to all men, inasmuch as all sinned—  
for up to the time of the law, sin was in the world,  
though sin is not accounted when there is no law.  
But death reigned from Adam to Moses,  
even over those who did not sin  
after the pattern of the trespass of Adam,  
who is the type of the one who was to come.  
But the gift is not like the transgression.  
For if by the transgression of the one, the many died,  
how much more did the grace of God  
and the gracious gift of the one man Jesus Christ  
overflow for the many.  
And the gift is not like the result of the one who sinned.  
For after one sin there was the judgment that brought condemnation;  
but the gift, after many transgressions, brought acquittal.  
For if, by the transgression of the one,  
death came to reign through that one,  
how much more will those who receive the abundance of grace  
and of the gift of justification  
come to reign in life through the one Jesus Christ.  
In conclusion, just as through one transgression  
condemnation came upon all,  
so, through one righteous act,  
acquittal and life came to all.  
For just as through the disobedience of the one man  
the many were made sinners,  
so, through the obedience of the one,  
the many will be made righteous.  

[Or:]{.red}

Brothers and sisters:  
Through one man sin entered the world,  
and through sin, death,  
and thus death came to all men, inasmuch as all sinned.  

For if, by the transgression of the one,  
death came to reign through that one,  
how much more will those who receive the abundance of grace  
and of the gift of justification  
come to reign in life through the one Jesus Christ.  
In conclusion, just as through one transgression  
condemnation came upon all,  
so, through one righteous act,  
acquittal and life came to all.  
For just as through the disobedience of the one man  
the many were made sinners,  
so, through the obedience of the one,  
the many will be made righteous.  

***

::: {.red}
#### Gospel Acclamation [Matthew 4:4b]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
One does not live on bread alone,  
but on every word that comes forth from the mouth of God. **[℟.]{.red}**

***

::: {.red}
#### Gospel [Matthew 4:1-11]{style="float:right" .small}
:::

At that time Jesus was led by the Spirit into the desert  
to be tempted by the devil.  
He fasted for forty days and forty nights,  
and afterwards he was hungry.  
The tempter approached and said to him,  
“If you are the Son of God,  
command that these stones become loaves of bread.”  
He said in reply,  
“It is written:  
*One does not live on bread alone,*  
*but on every word that comes forth*  
*from the mouth of God.*”  

Then the devil took him to the holy city,  
and made him stand on the parapet of the temple,  
and said to him, “If you are the Son of God, throw yourself down.  
For it is written:  
*He will command his angels concerning you*  
*and with their hands they will support you,*  
*lest you dash your foot against a stone.*”  
Jesus answered him,  
“Again it is written,  
*You shall not put the Lord, your God, to the test.*”  
Then the devil took him up to a very high mountain,  
and showed him all the kingdoms of the world in their magnificence,  
and he said to him, ""All these I shall give to you,  
if you will prostrate yourself and worship me.”  
At this, Jesus said to him,  
“Get away, Satan!  
It is written:  
*The Lord, your God, shall you worship*  
*and him alone shall you serve.*”  

Then the devil left him and, behold,  
angels came and ministered to him.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Genesis 9:8-15]{style="float:right" .small}
:::

God said to Noah and to his sons with him:  
"See, I am now establishing my covenant with you  
and your descendants after you  
and with every living creature that was with you:  
all the birds, and the various tame and wild animals  
that were with you and came out of the ark.  
I will establish my covenant with you,  
that never again shall all bodily creatures be destroyed  
by the waters of a flood;  
there shall not be another flood to devastate the earth."  
God added:  
"This is the sign that I am giving for all ages to come,  
of the covenant between me and you  
and every living creature with you:  
I set my bow in the clouds to serve as a sign  
of the covenant between me and the earth.  
When I bring clouds over the earth,  
and the bow appears in the clouds,  
I will recall the covenant I have made  
between me and you and all living beings,  
so that the waters shall never again become a flood  
to destroy all mortal beings."  

***

::: {.red}
#### Responsorial Psalm [Psalm 25:4-5, 6-7, 8-9]{style="float:right" .small}
:::

**[℟.]{.red}** **Your ways, O Lord, are love and truth to those who keep your covenant.**  

Your ways, O LORD, make known to me;  
teach me your paths,  
Guide me in your truth and teach me,  
for you are God my savior. **[℟.]{.red}**  

Remember that your compassion, O LORD,  
and your love are from of old.  
In your kindness remember me,  
because of your goodness, O LORD. **[℟.]{.red}**  

Good and upright is the LORD,  
thus he shows sinners the way.  
He guides the humble to justice,  
and he teaches the humble his way. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Peter 3:18-22]{style="float:right" .small}
:::

Beloved:  
Christ suffered for sins once,  
the righteous for the sake of the unrighteous,  
that he might lead you to God.  
Put to death in the flesh,  
he was brought to life in the Spirit.  
In it he also went to preach to the spirits in prison,  
who had once been disobedient  
while God patiently waited in the days of Noah  
during the building of the ark,  
in which a few persons, eight in all,  
were saved through water.  
This prefigured baptism, which saves you now.  
It is not a removal of dirt from the body  
but an appeal to God for a clear conscience,  
through the resurrection of Jesus Christ,  
who has gone into heaven  
and is at the right hand of God,  
with angels, authorities, and powers subject to him.  

***

::: {.red}
#### Gospel Acclamation [Matthew 4:4b]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
One does not live on bread alone,  
but on every word that comes forth from the mouth of God. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 1:12-15]{style="float:right" .small}
:::

The Spirit drove Jesus out into the desert,  
and he remained in the desert for forty days,  
tempted by Satan.  
He was among wild beasts,  
and the angels ministered to him.  

After John had been arrested,  
Jesus came to Galilee proclaiming the gospel of God:  
"This is the time of fulfillment.  
The kingdom of God is at hand.  
Repent, and believe in the gospel."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Deuteronomy 26:4-10]{style="float:right" .small}
:::

Moses spoke to the people, saying:  
“The priest shall receive the basket from you  
and shall set it in front of the altar of the LORD, your God.  
Then you shall declare before the Lord, your God,  
‘My father was a wandering Aramean  
who went down to Egypt with a small household  
and lived there as an alien.  
But there he became a nation  
great, strong, and numerous.  
When the Egyptians maltreated and oppressed us,  
imposing hard labor upon us,  
we cried to the LORD, the God of our fathers,  
and he heard our cry  
and saw our affliction, our toil, and our oppression.  
He brought us out of Egypt  
with his strong hand and outstretched arm,  
with terrifying power, with signs and wonders;  
and bringing us into this country,  
he gave us this land flowing with milk and honey.  
Therefore, I have now brought you the firstfruits  
of the products of the soil  
which you, O LORD, have given me.’  
And having set them before the LORD, your God,  
you shall bow down in his presence.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 91:1-2, 10-11, 12-13, 14-15]{style="float:right" .small}
:::

**[℟.]{.red}** **Be with me, Lord, when I am in trouble.**  

You who dwell in the shelter of the Most High,  
&emsp; who abide in the shadow of the Almighty,  
say to the LORD, “My refuge and fortress,  
&emsp; my God in whom I trust.” **[℟.]{.red}**  

No evil shall befall you,  
&emsp; nor shall affliction come near your tent,  
For to his angels he has given command about you,  
&emsp; that they guard you in all your ways. **[℟.]{.red}**  

Upon their hands they shall bear you up,  
&emsp; lest you dash your foot against a stone.  
You shall tread upon the asp and the viper;  
&emsp; you shall trample down the lion and the dragon. **[℟.]{.red}**  

Because he clings to me, I will deliver him;  
&emsp; I will set him on high because he acknowledges my name.  
He shall call upon me, and I will answer him;  
&emsp; I will be with him in distress;  
I will deliver him and glorify him. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Romans 10:8-13]{style="float:right" .small}
:::

Brothers and sisters:  
What does Scripture say?  
&emsp; *The word is near you,*  
&emsp; &emsp; *in your mouth and in your heart*  
—that is, the word of faith that we preach—,  
for, if you confess with your mouth that Jesus is Lord  
and believe in your heart that God raised him from the dead,  
you will be saved.  
For one believes with the heart and so is justified,  
and one confesses with the mouth and so is saved.  
For the Scripture says,  
&emsp; *No one who believes in him will be put to shame.*  
For there is no distinction between Jew and Greek;  
the same Lord is Lord of all,  
enriching all who call upon him.  
For “everyone who calls on the name of the Lord will be saved.”  

***

::: {.red}
#### Gospel Acclamation [Matthew 4:4b]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise to you, Lord Jesus Christ, king of endless glory.**  
One does not live on bread alone,  
but on every word that comes forth from the mouth of God. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [Luke 4:1-13]{style="float:right" .small}
:::

Filled with the Holy Spirit, Jesus returned from the Jordan  
and was led by the Spirit into the desert for forty days,  
to be tempted by the devil.  
He ate nothing during those days,  
and when they were over he was hungry.  
The devil said to him,  
“If you are the Son of God,  
command this stone to become bread.”  
Jesus answered him,  
“It is written, *One does not live on bread alone.*”  
Then he took him up and showed him  
all the kingdoms of the world in a single instant.  
The devil said to him,  
“I shall give to you all this power and glory;  
for it has been handed over to me,  
and I may give it to whomever I wish.  
All this will be yours, if you worship me.”  
Jesus said to him in reply,  
“It is written  
&emsp; *You shall worship the Lord, your God,*  
&emsp; &emsp; *and him alone shall you serve.*”  
Then he led him to Jerusalem,  
made him stand on the parapet of the temple, and said to him,  
“If you are the Son of God,  
throw yourself down from here, for it is written:  
&emsp; *He will command his angels concerning you, to guard you*,  
and:  
&emsp; *With their hands they will support you,*  
&emsp; *lest you dash your foot against a stone.*”  
Jesus said to him in reply,  
“It also says,  
&emsp; *You shall not put the Lord, your God, to the test.*”  
When the devil had finished every temptation,  
he departed from him for a time.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'])
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'])
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'])
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'])
```

::: {.red}
### Notes
:::

* The **Gloria** is omitted during Lent.