---
title: "ELEVENTH SUNDAY IN ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "O God, Our Help in Ages Past"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "We are his people: the sheep of his flock."
          book: RA
          priority: required
    offertory:
      list:
        - name: "All People That on Earth Do Dwell"
          book: G
          priority: required
    communion:
      list:
        - name: "Lord, Who at Your First Eucharist"
          book: G
          priority: preferred
        - name: "You Satisfy the Hungry Heart"
          book: G
          priority: optional
    meditation:
      list:
        - name: "On Eagle’s Wings"
          book: G
          priority: flexible
    recessional:
      list:
        - name: "Lord, You Give the Great Commission"
          book: G
          priority: required
  b:
    processional:
      list:
        - name: "Come, Ye Thankful People, Come"
          book: BB
          priority: preferred
    psalm:
      list:
        - name: "Lord, it is good to give thanks to you."
          book: RA
          priority: required
    offertory:
      list:
        - name: "We Walk By Faith"
          book: BB
          priority: required
    communion:
      list:
        - name: "Take and Eat"
          book: G
          priority: optional
        - name: "Many and Great"
          book: G
          priority: optional
    meditation:
      list:
        - name: "The Reign of God"
          book: G
          priority: preferred
    recessional:
      list:
        - name: "Let All Things Now Living"
          book: G
          priority: preferred
  c:
    processional:
      list:
        - name: "O God, Our Help in Ages Past"
          book: G
          priority: preferred
    psalm:
      list:
        - name: "Lord, forgive the wrong I have done."
          book: RA
          priority: required
    offertory:
      list:
        - name: "Remember Your Love"
          book: G
          priority: flexible
    communion:
      list:
        - name: "Pan de Vida"
          book: G
          priority: required
    meditation:
      list:
        - name: "Dwelling Place"
          book: G
          priority: preferred
    recessional:
      list:
        - name: "O God Beyond All Praising"
          book: G
          priority: flexible
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} service, discipleship, providence, apostles, mission  
[Year B:]{.red} parables, growth, justice, harvest  
[Year C:]{.red} forgiveness, repentance, salvation  

:::  {.red}
#### **Entrance Antiphon**
:::

> O Lord, hear my voice, for I have called to you; be my help.  
> Do not abandon or forsake me, O God, my Savior!  

:::  {.red}
#### **Communion Antiphon**
:::

> There is one thing I ask of the Lord, only this do I seek:  
> to live in the house of the Lord all the days of my life.  
>
> [Or:]{.red}
>
> Holy Father, keep in your name those you have given me,  
> that they may be one as we are one, says the Lord.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Exodus 19:2-6a]{style="float:right" .small}
:::

In those days, the Israelites came to the desert of Sinai and pitched camp.  
While Israel was encamped here in front of the mountain,  
Moses went up the mountain to God.  
Then the LORD called to him and said,  
“Thus shall you say to the house of Jacob;  
tell the Israelites:  
You have seen for yourselves how I treated the Egyptians  
and how I bore you up on eagle wings  
and brought you here to myself.  
Therefore, if you hearken to my voice and keep my covenant,  
you shall be my special possession,  
dearer to me than all other people,  
though all the earth is mine.  
You shall be to me a kingdom of priests, a holy nation.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 100:1-2, 3, 5]{style="float:right" .small}
:::

**[℟.]{.red}** **We are his people: the sheep of his flock.**  

Sing joyfully to the LORD, all you lands;  
&emsp; serve the LORD with gladness;  
&emsp; come before him with joyful song. **[℟.]{.red}**  

Know that the LORD is God;  
&emsp; he made us, his we are;  
&emsp; his people, the flock he tends. **[℟.]{.red}**  

The LORD is good:  
&emsp; his kindness endures forever,  
&emsp; and his faithfulness to all generations. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Romans 5:6-11]{style="float:right" .small}
:::

Brothers and sisters:  
Christ, while we were still helpless,  
yet died at the appointed time for the ungodly.  
Indeed, only with difficulty does one die for a just person,  
though perhaps for a good person  
one might even find courage to die.  
But God proves his love for us  
in that while we were still sinners Christ died for us.  
How much more then, since we are now justified by his blood,  
will we be saved through him from the wrath.  
Indeed, if, while we were enemies,  
we were reconciled to God through the death of his Son,  
how much more, once reconciled,  
will we be saved by his life.  
Not only that,  
but we also boast of God through our Lord Jesus Christ,  
through whom we have now received reconciliation.  

***

::: {.red}
#### Gospel Acclamation [Mark 1:15]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The kingdom of God is at hand.  
Repent and believe in the Gospel. **[℟.]{.red}**. 

***

::: {.red}
#### Gospel [Matthew 9:36—10:8]{style="float:right" .small}
:::

At the sight of the crowds, Jesus’ heart was moved with pity for them  
because they were troubled and abandoned,  
like sheep without a shepherd.  
Then he said to his disciples,  
“The harvest is abundant but the laborers are few;  
so ask the master of the harvest  
to send out laborers for his harvest.”  

Then he summoned his twelve disciples  
and gave them authority over unclean spirits  
to drive them out and to cure every disease and every illness.  
The names of the twelve apostles are these:  
first, Simon called Peter, and his brother Andrew;  
James, the son of Zebedee, and his brother John;  
Philip and Bartholomew, Thomas and Matthew the tax collector;  
James, the son of Alphaeus, and Thaddeus;  
Simon from Cana, and Judas Iscariot who betrayed him.  

Jesus sent out these twelve after instructing them thus,  
“Do not go into pagan territory or enter a Samaritan town.  
Go rather to the lost sheep of the house of Israel.  
As you go, make this proclamation: ‘The kingdom of heaven is at hand.’  
Cure the sick, raise the dead, cleanse lepers, drive out demons.  
Without cost you have received; without cost you are to give.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Ezekiel 17:22-24]{style="float:right" .small}
:::

Thus says the Lord GOD:  
I, too, will take from the crest of the cedar,  
from its topmost branches tear off a tender shoot,  
and plant it on a high and lofty mountain;  
on the mountain heights of Israel I will plant it.  
It shall put forth branches and bear fruit,  
and become a majestic cedar.  
Birds of every kind shall dwell beneath it,  
every winged thing in the shade of its boughs.  
And all the trees of the field shall know  
that I, the LORD,  
bring low the high tree,  
lift high the lowly tree,  
wither up the green tree,  
and make the withered tree bloom.  
As I, the LORD, have spoken, so will I do.  

***

::: {.red}
#### Responsorial Psalm [Psalm 92:2-3, 13-14, 15-16]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, it is good to give thanks to you.**  

It is good to give thanks to the LORD,  
to sing praise to your name, Most High,  
To proclaim your kindness at dawn  
and your faithfulness throughout the night. **[℟.]{.red}**  

The just one shall flourish like the palm tree,  
like a cedar of Lebanon shall he grow.  
They that are planted in the house of the LORD  
shall flourish in the courts of our God. **[℟.]{.red}**  

They shall bear fruit even in old age;  
vigorous and sturdy shall they be,  
Declaring how just is the LORD,  
my rock, in whom there is no wrong. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [2 Corinthians 5:6-10]{style="float:right" .small}
:::

Brothers and sisters:  
We are always courageous,  
although we know that while we are at home in the body  
we are away from the Lord,  
for we walk by faith, not by sight.  
Yet we are courageous,  
and we would rather leave the body and go home to the Lord.  
Therefore, we aspire to please him,  
whether we are at home or away.  
For we must all appear before the judgment seat of Christ,  
so that each may receive recompense,  
according to what he did in the body, whether good or evil.  

***

::: {.red}
#### Gospel Acclamation
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The seed is the word of God, Christ is the sower.  
All who come to him will live forever. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 4:26-34]{style="float:right" .small}
:::

Jesus said to the crowds:  
“This is how it is with the kingdom of God;  
it is as if a man were to scatter seed on the land  
and would sleep and rise night and day  
and through it all the seed would sprout and grow,  
he knows not how.  
Of its own accord the land yields fruit,  
first the blade, then the ear, then the full grain in the ear.  
And when the grain is ripe, he wields the sickle at once,  
for the harvest has come.”  

He said,  
“To what shall we compare the kingdom of God,  
or what parable can we use for it?  
It is like a mustard seed that, when it is sown in the ground,  
is the smallest of all the seeds on the earth.  
But once it is sown, it springs up and becomes the largest of plants  
and puts forth large branches,  
so that the birds of the sky can dwell in its shade.”  
With many such parables  
he spoke the word to them as they were able to understand it.  
Without parables he did not speak to them,  
but to his own disciples he explained everything in private.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [2 Samuel 12:7-10, 13]{style="float:right" .small}
:::

Nathan said to David:  
“Thus says the LORD God of Israel:  
‘I anointed you king of Israel.  
I rescued you from the hand of Saul.  
I gave you your lord’s house and your lord’s wives for your own.  
I gave you the house of Israel and of Judah.  
And if this were not enough, I could count up for you still more.  
Why have you rejected the LORD and done evil in his sight?  
You have cut down Uriah the Hittite with the sword;  
you took his wife as your own,  
and him you killed with the sword of the Ammonites.  
Now, therefore, the sword shall never depart from your house,  
because you have looked down on me  
and have taken the wife of Uriah to be your wife.’”  

Then David said to Nathan,  
“I have sinned against the LORD.”  
Nathan answered David:  
“The LORD on his part has forgiven your sin:  
you shall not die.”  

***

::: {.red}
#### Responsorial Psalm [Psalm 32:1-2, 5, 7, 11]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, forgive the wrong I have done.**  

Blessed is the one whose fault is taken away,  
whose sin is covered.  
Blessed the man to whom the LORD imputes not guilt,  
in whose spirit there is no guile. **[℟.]{.red}**  

I acknowledged my sin to you,  
my guilt I covered not.  
I said, "I confess my faults to the LORD,"  
and you took away the guilt of my sin. **[℟.]{.red}**  

You are my shelter; from distress you will preserve me;  
with glad cries of freedom you will ring me round. **[℟.]{.red}**  

Be glad in the LORD and rejoice, you just;  
exult, all you upright of heart. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Galatians 2:16, 19-21]{style="float:right" .small}
:::

Brothers and sisters:  
We who know that a person is not justified by works of the law  
but through faith in Jesus Christ,  
even we have believed in Christ Jesus  
that we may be justified by faith in Christ  
and not by works of the law,  
because by works of the law no one will be justified.  
For through the law I died to the law,  
that I might live for God.  
I have been crucified with Christ;  
yet I live, no longer I, but Christ lives in me;  
insofar as I now live in the flesh,  
I live by faith in the Son of God  
who has loved me and given himself up for me.  
I do not nullify the grace of God;  
for if justification comes through the law,  
then Christ died for nothing.  

***

::: {.red}
#### Gospel Acclamation [1 John 4:10b]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
God loved us and sent his Son  
as expiation for our sins. **[℟.]{.red}** 

***

::: {.red}
#### Gospel [Luke 7:36—8:3 or 7:36-50]{style="float:right" .small}
:::

A Pharisee invited Jesus to dine with him,  
and he entered the Pharisee's house and reclined at table.  
Now there was a sinful woman in the city  
who learned that he was at table in the house of the Pharisee.  
Bringing an alabaster flask of ointment,  
she stood behind him at his feet weeping  
and began to bathe his feet with her tears.  
Then she wiped them with her hair,  
kissed them, and anointed them with the ointment.  
When the Pharisee who had invited him saw this he said to himself,  
"If this man were a prophet,  
he would know who and what sort of woman this is who is touching him,  
that she is a sinner."  
Jesus said to him in reply,  
"Simon, I have something to say to you."  
"Tell me, teacher," he said.  
"Two people were in debt to a certain creditor;  
one owed five hundred days' wages and the other owed fifty.  
Since they were unable to repay the debt, he forgave it for both.  
Which of them will love him more?"  
Simon said in reply,  
"The one, I suppose, whose larger debt was forgiven."  
He said to him, "You have judged rightly."  

Then he turned to the woman and said to Simon,  
"Do you see this woman?  
When I entered your house, you did not give me water for my feet,  
but she has bathed them with her tears  
and wiped them with her hair.  
You did not give me a kiss,  
but she has not ceased kissing my feet since the time I entered.  
You did not anoint my head with oil,  
but she anointed my feet with ointment.  
So I tell you, her many sins have been forgiven  
because she has shown great love.  
But the one to whom little is forgiven, loves little."  
He said to her, "Your sins are forgiven."  
The others at table said to themselves,  
"Who is this who even forgives sins?"  
But he said to the woman,  
"Your faith has saved you; go in peace."  

Afterward he journeyed from one town and village to another,  
preaching and proclaiming the good news of the kingdom of God.  
Accompanying him were the Twelve  
and some women who had been cured of evil spirits and infirmities,  
Mary, called Magdalene, from whom seven demons had gone out,  
Joanna, the wife of Herod's steward Chuza,  
Susanna, and many others who provided for them  
out of their resources.  

[Or:]{.red}  

A Pharisee invited Jesus to dine with him,  
and he entered the Pharisee's house and reclined at table.  
Now there was a sinful woman in the city  
who learned that he was at table in the house of the Pharisee.  
Bringing an alabaster flask of ointment,  
she stood behind him at his feet weeping  
and began to bathe his feet with her tears.  
Then she wiped them with her hair,  
kissed them, and anointed them with the ointment.  
When the Pharisee who had invited him saw this he said to himself,  
"If this man were a prophet,  
he would know who and what sort of woman this is who is touching him,  
that she is a sinner."  
Jesus said to him in reply,  
"Simon, I have something to say to you."  
"Tell me, teacher," he said.  
"Two people were in debt to a certain creditor;  
one owed five hundred day's wages and the other owed fifty.  
Since they were unable to repay the debt, he forgave it for both.  
Which of them will love him more?"  
Simon said in reply,  
"The one, I suppose, whose larger debt was forgiven."  
He said to him, "You have judged rightly."  

Then he turned to the woman and said to Simon,  
"Do you see this woman?  
When I entered your house, you did not give me water for my feet,  
but she has bathed them with her tears  
and wiped them with her hair.  
You did not give me a kiss,  
but she has not ceased kissing my feet since the time I entered.  
You did not anoint my head with oil,  
but she anointed my feet with ointment.  
So I tell you, her many sins have been forgiven  
because she has shown great love.  
But the one to whom little is forgiven, loves little."  
He said to her, "Your sins are forgiven."  
The others at table said to themselves,  
"Who is this who even forgives sins?"  
But he said to the woman,  
"Your faith has saved you; go in peace."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
