---
title: "FOURTEENTH SUNDAY IN ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Come to Us"
          book: G
          priority: required
    psalm:
      list:
        - name: "I will praise your name for ever, my king and my God."
          book: RA
          priority: required
    offertory:
      list:
        - name: "I Heard the Voice of Jesus Say"
          book: G
          priority: required
    communion:
      list:
        - name: "Taste and See"
          composer: Moore
          book: G
          priority: required
    meditation:
      list:
        - name: "Come to Me"
          composer: Bell
          book: G
          priority: required
    recessional:
      list:
        - name: "We Shall Rise Again"
          book: G
          priority: required
  b:
    processional:
      list:
        - name: ""
          book: G
          priority: required
    psalm:
      list:
        - name: "Our eyes are fixed on the Lord, pleading for his mercy."
          book: RA
          priority: required
    offertory:
      list:
        - name: "" 
          book: G
          priority: required
    communion:
      list:
        - name: "Taste and See"
          composer: Moore
          book: G
          priority: required
    meditation:
      list:
        - name: "Come to Me"
          composer: Bell
          book: G
          priority: required
    recessional:
      list:
        - name: ""
          book: G
          priority: preferred
  c:
    processional:
      list:
        - name: ""
          book: G
          priority: required
    psalm:
      list:
        - name: "Let all the earth cry out to God with joy."
          book: RA
          priority: required
    offertory:
      list:
        - name: "The Servant Song"
          book: G
          priority: preferred
    communion:
      list:
        - name: "Taste and See"
          composer: Moore
          book: G
          priority: required
    meditation:
      list:
        - name: "Come to Me"
          composer: Bell
          book: G
          priority: required
    recessional:
      list:
        - name: "Lord, You Give the Great Commission"
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} mercy, majesty, glory of God, humility, Christ the
King, Sacred Heart  
[Year B:]{.red} discipleship, love, grace, suﬀering, prophecy  
[Year C:]{.red} witness, peace, renewal, comfort, blessing  

:::  {.red}
#### **Entrance Antiphon**
:::

> Your merciful love, O God,  
> we have received in the midst of your temple.  
> Your praise, O God, like your name,  
> reaches the ends of the earth;  
> your right hand is filled with saving justice.  

:::  {.red}
#### **Communion Antiphon**
:::

> Taste and see that the Lord is good;  
> blessed the man who seeks refuge in him.  
>
> [Or:]{.red}  
>
> Come to me, all who labor and are burdened,  
> and I will refresh you, says the Lord.

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Zechariah 9:9-10]{style="float:right" .small}
:::

Thus says the LORD:  
Rejoice heartily, O daughter Zion,  
shout for joy, O daughter Jerusalem!  
See, your king shall come to you;  
a just savior is he,  
meek, and riding on an ass,  
on a colt, the foal of an ass.  
He shall banish the chariot from Ephraim,  
and the horse from Jerusalem;  
the warrior's bow shall be banished,  
and he shall proclaim peace to the nations.  
His dominion shall be from sea to sea,  
and from the River to the ends of the earth.  

***

::: {.red}
#### Responsorial Psalm [Psalm 145:1-2, 8-9, 10-11, 13-14]{style="float:right" .small}
:::

**[℟.]{.red}** **I will praise your name for ever, my king and my God.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**

I will extol you, O my God and King,  
and I will bless your name forever and ever.  
Every day will I bless you,  
and I will praise your name forever and ever. **[℟.]{.red}**  

The LORD is gracious and merciful,  
slow to anger and of great kindness.  
The LORD is good to all  
and compassionate toward all his works. **[℟.]{.red}**  

Let all your works give you thanks, O LORD,  
and let your faithful ones bless you.  
Let them discourse of the glory of your kingdom  
and speak of your might. **[℟.]{.red}**  

The LORD is faithful in all his words  
and holy in all his works.  
The LORD lifts up all who are falling  
and raises up all who are bowed down. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Romans 8:9, 11-13]{style="float:right" .small}
:::

Brothers and sisters:  
You are not in the flesh;  
on the contrary, you are in the spirit,  
if only the Spirit of God dwells in you.  
Whoever does not have the Spirit of Christ does not belong to him.  
If the Spirit of the one who raised Jesus from the dead dwells in you,  
the one who raised Christ from the dead  
will give life to your mortal bodies also,  
through his Spirit that dwells in you.  
Consequently, brothers and sisters,  
we are not debtors to the flesh,  
to live according to the flesh.  
For if you live according to the flesh, you will die,  
but if by the Spirit you put to death the deeds of the body,  
you will live.  

***

::: {.red}
#### Gospel Acclamation [Cf. Matthew 11:25]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Blessed are you, Father, Lord of heaven and earth;  
you have revealed to little ones the mysteries of the kingdom.
 **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 11:25-30]{style="float:right" .small}
:::

At that time Jesus exclaimed:  
"I give praise to you, Father, Lord of heaven and earth,  
for although you have hidden these things  
from the wise and the learned  
you have revealed them to little ones.  
Yes, Father, such has been your gracious will.  
All things have been handed over to me by my Father.  
No one knows the Son except the Father,  
and no one knows the Father except the Son  
and anyone to whom the Son wishes to reveal him."  

"Come to me, all you who labor and are burdened,  
and I will give you rest.  
Take my yoke upon you and learn from me,  
for I am meek and humble of heart;  
and you will find rest for yourselves.  
For my yoke is easy, and my burden light."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Ezekiel 2:2-5]{style="float:right" .small}
:::

As the LORD spoke to me, the spirit entered into me  
and set me on my feet,  
and I heard the one who was speaking say to me:  
Son of man, I am sending you to the Israelites,  
rebels who have rebelled against me;  
they and their ancestors have revolted against me to this very day.  
Hard of face and obstinate of heart  
are they to whom I am sending you.  
But you shall say to them: Thus says the LORD GOD!  
And whether they heed or resist—for they are a rebellious house—  
they shall know that a prophet has been among them.  

***

::: {.red}
#### Responsorial Psalm [Psalm 123:1-2, 2, 3-4]{style="float:right" .small}
:::

**[℟.]{.red}** **Our eyes are fixed on the Lord, pleading for his mercy.**  

To you I lift up my eyes  
who are enthroned in heaven —  
As the eyes of servants  
are on the hands of their masters. **[℟.]{.red}**  

As the eyes of a maid  
are on the hands of her mistress,  
So are our eyes on the LORD, our God,  
till he have pity on us. **[℟.]{.red}**  

Have pity on us, O LORD, have pity on us,  
for we are more than sated with contempt;  
our souls are more than sated  
with the mockery of the arrogant,  
with the contempt of the proud. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [2 Corinthians 12:7-10]{style="float:right" .small}
:::

Brothers and sisters:  
That I, Paul, might not become too elated,  
because of the abundance of the revelations,  
a thorn in the flesh was given to me, an angel of Satan,  
to beat me, to keep me from being too elated.  
Three times I begged the Lord about this, that it might leave me,  
but he said to me, “My grace is sufficient for you,  
for power is made perfect in weakness.”  
I will rather boast most gladly of my weaknesses,  
in order that the power of Christ may dwell with me.  
Therefore, I am content with weaknesses, insults,  
hardships, persecutions, and constraints,  
for the sake of Christ;  
for when I am weak, then I am strong.  

***

::: {.red}
#### Gospel Acclamation [Cf. Luke 4:18]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
The Spirit of the Lord is upon me,  
for he sent me to bring glad tidings to the poor. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 6:1-6]{style="float:right" .small}
:::

Jesus departed from there and came to his native place, accompanied by his disciples.  
When the sabbath came he began to teach in the synagogue,  
and many who heard him were astonished.  
They said, “Where did this man get all this?  
What kind of wisdom has been given him?  
What mighty deeds are wrought by his hands!  
Is he not the carpenter, the son of Mary,  
and the brother of James and Joses and Judas and Simon?  
And are not his sisters here with us?”  
And they took offense at him.  
Jesus said to them,  
“A prophet is not without honor except in his native place  
and among his own kin and in his own house.”  
So he was not able to perform any mighty deed there,  
apart from curing a few sick people by laying his hands on them.  
He was amazed at their lack of faith.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Isaiah 66:10-14c]{style="float:right" .small}
:::

Thus says the LORD:  
Rejoice with Jerusalem and be glad because of her,  
all you who love her;  
exult, exult with her,  
all you who were mourning over her!  
Oh, that you may suck fully  
of the milk of her comfort,  
that you may nurse with delight  
at her abundant breasts!  
For thus says the LORD:  
Lo, I will spread prosperity over Jerusalem like a river,  
and the wealth of the nations like an overflowing torrent.  
As nurslings, you shall be carried in her arms,  
and fondled in her lap;  
as a mother comforts her child,  
so will I comfort you;  
in Jerusalem you shall find your comfort.  

When you see this, your heart shall rejoice  
and your bodies flourish like the grass;  
the LORD's power shall be known to his servants.  

***

::: {.red}
#### Responsorial Psalm [Psalm 66:1-3, 4-5, 6-7, 16, 20]{style="float:right" .small}
:::

**[℟.]{.red}** **Let all the earth cry out to God with joy.**  

Shout joyfully to God, all the earth,  
sing praise to the glory of his name;  
proclaim his glorious praise.  
Say to God, "How tremendous are your deeds!" **[℟.]{.red}**  

"Let all on earth worship and sing praise to you,  
sing praise to your name!"  
Come and see the works of God,  
his tremendous deeds among the children of Adam. **[℟.]{.red}**  

He has changed the sea into dry land;  
through the river they passed on foot;  
therefore let us rejoice in him.  
He rules by his might forever. **[℟.]{.red}**  

Hear now, all you who fear God, while I declare  
what he has done for me.  
Blessed be God who refused me not  
my prayer or his kindness! **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Galatians 6:14-18]{style="float:right" .small}
:::

Brothers and sisters:  
May I never boast except in the cross of our Lord Jesus Christ,  
through which the world has been crucified to me,  
and I to the world.  
For neither does circumcision mean anything, nor does uncircumcision,  
but only a new creation.  
Peace and mercy be to all who follow this rule  
and to the Israel of God.  

From now on, let no one make troubles for me;  
for I bear the marks of Jesus on my body.  

The grace of our Lord Jesus Christ be with your spirit,  
brothers and sisters. Amen.  

***

::: {.red}
#### Gospel Acclamation [Colossians 3:15a, 16a]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Let the peace of Christ control your hearts;  
let the word of Christ dwell in you richly. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 10:1-12, 17-20 or 10:1-9]{style="float:right" .small}
:::

At that time the Lord appointed seventy-two others  
whom he sent ahead of him in pairs  
to every town and place he intended to visit.  
He said to them,  
"The harvest is abundant but the laborers are few;  
so ask the master of the harvest  
to send out laborers for his harvest.  
Go on your way;  
behold, I am sending you like lambs among wolves.  
Carry no money bag, no sack, no sandals;  
and greet no one along the way.  
Into whatever house you enter, first say,  
'Peace to this household.'  
If a peaceful person lives there,  
your peace will rest on him;  
but if not, it will return to you.  
Stay in the same house and eat and drink what is offered to you,  
for the laborer deserves his payment.  
Do not move about from one house to another.  
Whatever town you enter and they welcome you,  
eat what is set before you,  
cure the sick in it and say to them,  
'The kingdom of God is at hand for you.'  
Whatever town you enter and they do not receive you,  
go out into the streets and say,  
'The dust of your town that clings to our feet,  
even that we shake off against you.'  
Yet know this: the kingdom of God is at hand.  
I tell you,  
it will be more tolerable for Sodom on that day than for that town."  

The seventy-two returned rejoicing, and said,  
"Lord, even the demons are subject to us because of your name."  
Jesus said, "I have observed Satan fall like lightning from the sky.  
Behold, I have given you the power to 'tread upon serpents' and scorpions  
and upon the full force of the enemy and nothing will harm you.  
Nevertheless, do not rejoice because the spirits are subject to you,  
but rejoice because your names are written in heaven."  

[Or:]{.red}  

At that time the Lord appointed seventy-two others  
whom he sent ahead of him in pairs  
to every town and place he intended to visit.  
He said to them,  
"The harvest is abundant but the laborers are few;  
so ask the master of the harvest  
to send out laborers for his harvest.  
Go on your way;  
behold, I am sending you like lambs among wolves.  
Carry no money bag, no sack, no sandals;  
and greet no one along the way.  
Into whatever house you enter, first say,  
'Peace to this household.'  
If a peaceful person lives there,  
your peace will rest on him;  
but if not, it will return to you.  
Stay in the same house and eat and drink what is offered to you,  
for the laborer deserves his payment.  
Do not move about from one house to another.  
Whatever town you enter and they welcome you,  
eat what is set before you,  
cure the sick in it and say to them,  
'The kingdom of God is at hand for you.'"  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```

::: {.red}
### Notes
:::

* “Servant Song” and “The Servant Song” are two diﬀerent songs.
