---
title: "TWENTIETH SUNDAY IN ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "As We Gather at Your Table"
          book: G
          priority: flexible
    psalm:
      list:
        - name: "O God, let all the nations praise you."
          book: RA
          priority: required
    offertory:
      list:
        - name: "We Cannot Measure How You Heal"
          book: G
          priority: optional
        - name: "Healing River of the Spirit"
          book: G
          priority: optional
    communion:
      list:
        - name: "Let Us Be Bread"
          book: G
          priority: preferred
    meditation:
      list:
        - name: "Dwelling Place"
          book: G
          priority: flexible
    recessional:
      list:
        - name: "There's a Wideness in God's Mercy"
          book: G
          priority: preferred
  b:
    processional:
      list:
        - name: ""
          book: G
          priority: required
    psalm:
      list:
        - name: "Taste and see the goodness of the Lord."
          book: RA
          priority: required
    offertory:
      list:
        - name: ""
          book: G
          priority: required
    communion:
      list:
        - name: "I Am the Bread of Life"
          book: G
          priority: required
    meditation:
      list:
        - name: ""
          book: G
          priority: preferred
    recessional:
      list:
        - name: ""
          book: G
          priority: preferred
    anthems:
      list:
        - name: "Wisdom's Feast"
  c:
    processional:
      list:
        - name: "Lift High the Cross"
          book: G
          priority: required
    psalm:
      list:
        - name: "Lord, come to my aid!"
          book: RA
          priority: required
    offertory:
      list:
        - name: ""
          book: G
          priority: required
    communion:
      list:
        - name: ""
          book: G
          priority: preferred
    meditation:
      list:
        - name: ""
          book: G
          priority: required
    recessional:
      list:
        - name: ""
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} power of God, salvation, faithful perseverance,
universality of the Church, healing, justice  
[Year B:]{.red} goodness of God, sing praise, bread of life, heavenly
banquet  
[Year C:]{.red} perseverance, discipleship, cross

:::  {.red}
#### **Entrance Antiphon**
:::

> Turn your eyes, O God, our shield;  
> and look on the face of your anointed one;  
> one day within your courts  
> is better than a thousand elsewhere.  

:::  {.red}
#### **Communion Antiphon**
:::

> With the Lord there is mercy;  
> in him is plentiful redemption.  
> 
> [Or:]{.red}  
>
> I am the living bread that came down from heaven, says the Lord.  
> Whoever eats of this bread will live for ever.  

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Isaiah 56:1, 6-7]{style="float:right" .small}
:::

Thus says the LORD:  
Observe what is right, do what is just;  
for my salvation is about to come,  
my justice, about to be revealed.  

The foreigners who join themselves to the LORD,  
ministering to him,  
loving the name of the LORD,  
and becoming his servants—  
all who keep the sabbath free from profanation  
and hold to my covenant,  
them I will bring to my holy mountain  
and make joyful in my house of prayer;  
their burnt offerings and sacrifices  
will be acceptable on my altar,  
for my house shall be called  
a house of prayer for all peoples.  

***

::: {.red}
#### Responsorial Psalm [Psalm 67:2-3, 5, 6, 8]{style="float:right" .small}
:::

**[℟.]{.red}** **O God, let all the nations praise you!**  

May God have pity on us and bless us;  
may he let his face shine upon us.  
So may your way be known upon earth;  
among all nations, your salvation. **[℟.]{.red}**  

May the nations be glad and exult  
because you rule the peoples in equity;  
the nations on the earth you guide. **[℟.]{.red}**  

May the peoples praise you, O God;  
may all the peoples praise you!  
May God bless us,  
and may all the ends of the earth fear him! **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Romans 11:13-15, 29-32]{style="float:right" .small}
:::

Brothers and sisters:  
I am speaking to you Gentiles.  
Inasmuch as I am the apostle to the Gentiles,  
I glory in my ministry in order to make my race jealous  
and thus save some of them.  
For if their rejection is the reconciliation of the world,  
what will their acceptance be but life from the dead?  

For the gifts and the call of God are irrevocable.  
Just as you once disobeyed God  
but have now received mercy because of their disobedience,  
so they have now disobeyed in order that,  
by virtue of the mercy shown to you,  
they too may now receive mercy.  
For God delivered all to disobedience,  
that he might have mercy upon all.  

***

::: {.red}
#### Gospel Acclamation [Cf. Matthew 4:23]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Jesus proclaimed the Gospel of the kingdom  
and cured every disease among the people. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 15:21-28]{style="float:right" .small}
:::

At that time, Jesus withdrew to the region of Tyre and Sidon.  
And behold, a Canaanite woman of that district came and called out,  
"Have pity on me, Lord, Son of David!  
My daughter is tormented by a demon."  
But Jesus did not say a word in answer to her.  
Jesus' disciples came and asked him,  
"Send her away, for she keeps calling out after us."  
He said in reply,  
"I was sent only to the lost sheep of the house of Israel."  
But the woman came and did Jesus homage, saying, "Lord, help me."  
He said in reply,  
"It is not right to take the food of the children  
and throw it to the dogs."  
She said, "Please, Lord, for even the dogs eat the scraps  
that fall from the table of their masters."  
Then Jesus said to her in reply,   
"O woman, great is your faith!  
Let it be done for you as you wish."  
And the woman's daughter was healed from that hour.  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Proverbs 9:1-6]{style="float:right" .small}
:::

Wisdom has built her house,  
she has set up her seven columns;  
she has dressed her meat, mixed her wine,  
yes, she has spread her table.  
She has sent out her maidens; she calls  
from the heights out over the city:  
"Let whoever is simple turn in here;  
To the one who lacks understanding, she says,  
Come, eat of my food,  
and drink of the wine I have mixed!  
Forsake foolishness that you may live;  
advance in the way of understanding."  

***

::: {.red}
#### Responsorial Psalm [Psalm 34:2-3, 4-5, 6-7]{style="float:right" .small}
:::

**[℟.]{.red}** **Taste and see the goodness of the Lord.**  

I will bless the LORD at all times;  
his praise shall be ever in my mouth.  
Let my soul glory in the LORD;  
the lowly will hear me and be glad. **[℟.]{.red}**  

Glorify the LORD with me,  
let us together extol his name.  
I sought the LORD, and he answered me  
and delivered me from all my fears. **[℟.]{.red}**  

Look to him that you may be radiant with joy,  
and your faces may not blush with shame.  
When the poor one called out, the LORD heard,  
and from all his distress he saved him. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Ephesians 5:15-20]{style="float:right" .small}
:::

Brothers and sisters:  
Watch carefully how you live,  
not as foolish persons but as wise,  
making the most of the opportunity,  
because the days are evil.  
Therefore, do not continue in ignorance,  
but try to understand what is the will of the Lord.  
And do not get drunk on wine, in which lies debauchery,  
but be filled with the Spirit,  
addressing one another in psalms and hymns and spiritual songs,  
singing and playing to the Lord in your hearts,  
giving thanks always and for everything  
in the name of our Lord Jesus Christ to God the Father.  

***

::: {.red}
#### Gospel Acclamation [John 6:56]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Whoever eats my flesh and drinks my blood  
remains in me and I in him, says the Lord. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [John 6:51-58]{style="float:right" .small}
:::

Jesus said to the crowds:  
"I am the living bread that came down from heaven;  
whoever eats this bread will live forever;  
and the bread that I will give  
is my flesh for the life of the world."  

The Jews quarreled among themselves, saying,  
"How can this man give us his flesh to eat?"  
Jesus said to them,  
"Amen, amen, I say to you,  
unless you eat the flesh of the Son of Man and drink his blood,  
you do not have life within you.  
Whoever eats my flesh and drinks my blood  
has eternal life,  
and I will raise him on the last day.  
For my flesh is true food,  
and my blood is true drink.  
Whoever eats my flesh and drinks my blood  
remains in me and I in him.  
Just as the living Father sent me  
and I have life because of the Father,  
so also the one who feeds on me  
will have life because of me.  
This is the bread that came down from heaven.  
Unlike your ancestors who ate and still died,  
whoever eats this bread will live forever."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Jeremiah 38:4-6, 8-10]{style="float:right" .small}
:::

In those days, the princes said to the king:  
"Jeremiah ought to be put to death;  
he is demoralizing the soldiers who are left in this city,  
and all the people, by speaking such things to them;  
he is not interested in the welfare of our people,  
but in their ruin."  
King Zedekiah answered: "He is in your power";  
for the king could do nothing with them.  
And so they took Jeremiah  
and threw him into the cistern of Prince Malchiah,  
which was in the quarters of the guard,  
letting him down with ropes.  
There was no water in the cistern, only mud,  
and Jeremiah sank into the mud.  

Ebed-melech, a court official,  
went there from the palace and said to him:  
"My lord king,  
these men have been at fault  
in all they have done to the prophet Jeremiah,  
casting him into the cistern.  
He will die of famine on the spot,  
for there is no more food in the city."  
Then the king ordered Ebed-melech the Cushite  
to take three men along with him,  
and draw the prophet Jeremiah out of the cistern before  
he should die.  

***

::: {.red}
#### Responsorial Psalm [Psalm 40:2, 3, 4, 18]{style="float:right" .small}
:::

**[℟.]{.red}** **Lord, come to my aid!**  

I have waited, waited for the LORD,  
and he stooped toward me. **[℟.]{.red}**  

The LORD heard my cry.  
He drew me out of the pit of destruction,  
out of the mud of the swamp;  
he set my feet upon a crag;  
he made firm my steps. **[℟.]{.red}**  

And he put a new song into my mouth,  
a hymn to our God.  
Many shall look on in awe  
and trust in the LORD. **[℟.]{.red}**  

Though I am afflicted and poor,  
yet the LORD thinks of me.  
You are my help and my deliverer;  
O my God, hold not back! **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Hebrews 12:1-4]{style="float:right" .small}
:::

Brothers and sisters:  
Since we are surrounded by so great a cloud of witnesses,  
let us rid ourselves of every burden and sin that clings to us  
and persevere in running the race that lies before us  
while keeping our eyes fixed on Jesus,  
the leader and perfecter of faith.  
For the sake of the joy that lay before him  
he endured the cross, despising its shame,  
and has taken his seat at the right of the throne of God.  
Consider how he endured such opposition from sinners,  
in order that you may not grow weary and lose heart.  
In your struggle against sin  
you have not yet resisted to the point of shedding blood.  

***

::: {.red}
#### Gospel Acclamation [John 10:27]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
My sheep hear my voice, says the Lord;  
I know them, and they follow me. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 12:49-53]{style="float:right" .small}
:::

Jesus said to his disciples:  
"I have come to set the earth on fire,  
and how I wish it were already blazing!  
There is a baptism with which I must be baptized,  
and how great is my anguish until it is accomplished!  
Do you think that I have come to establish peace on the earth?  
No, I tell you, but rather division.  
From now on a household of five will be divided,  
three against two and two against three;  
a father will be divided against his son  
and a son against his father,  
a mother against her daughter  
and a daughter against her mother,  
a mother-in-law against her daughter-in-law  
and a daughter-in-law against her mother-in-law."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
