---
title: "TWENTY-FIFTH SUNDAY IN ORDINARY TIME"
---

```{python}
#| label: Front matter params
#| echo: false

frontmatter = """
hymns:
  a:
    processional:
      list:
        - name: "Glory and Praise to Our God"
          book: G
          priority: flexible
    psalm:
      list:
        - name: "The Lord is near to all who call upon him."
          book: RA
          priority: required
    offertory:
      list:
        - name: "You Are Near"
          book: G
          priority: required
    communion:
      list:
        - name: "Seek Ye First"
          book: G
          priority: preferred
    meditation:
      list:
        - name: "You Are All We Have"
          tune: Taize
          book: G
          priority: preferred
    recessional:
      list:
        - name: "The Kingdom of God"
          tune: LAUDATE DOMINUM
          book: G
          priority: required
  b:
    processional:
      list:
        - name: ""
          book: G
          priority: required
    psalm:
      list:
        - name: "The Lord upholds my life."
          book: RA
          priority: required
    offertory:
      list:
        - name: ""
          book: G
          priority: required
    communion:
      list:
        - name: "We Remember"
          book: G
          priority: preferred
    meditation:
      list:
        - name: "You, Lord, Are Both Lamb and Shepherd"
          book: G
          priority: preferred
    recessional:
      list:
        - name: ""
          book: G
          priority: preferred
  c:
    processional:
      list:
        - name: ""
          book: G
          priority: required
    psalm:
      list:
        - name: "Praise the Lord who lifts up the poor."
          book: RA
          priority: required
    offertory:
      list:
        - name: "I Want to Walk as a Child of the Light"
          book: G
          priority: required
    communion:
      list:
        - name: "I Receive the Living God"
          book: G
          priority: required
    meditation:
      list:
        - name: ""
          book: G
          priority: required
    recessional:
      list:
        - name: ""
          book: G
          priority: required
"""
```

```{python}
#| label: Setup and helper functions
#| echo: false
import sys
import yaml
sys.path.append('/workspaces/planning-book')
sys.path.append('../../')
import utils

# Front matter YAML and check for errors
params = utils.get_params(frontmatter)

# Video links
with open('../../_hymns.yml', 'r') as vf:
    videos = yaml.safe_load(vf)
```

:::  {.red}
#### **Themes**
:::

[Year A:]{.red} generosity of God, mystery of God’s mercy and
goodness, justice  
[Year B:]{.red} humility, suﬀering, patience, submission, service  
[Year C:]{.red} riches/poverty, prayer  

:::  {.red}
#### **Entrance Antiphon**
:::

> I am the salvation of the people, says the Lord.  
> Should they cry to me in any distress,  
> I will hear them, and I will be their Lord for ever.  

:::  {.red}
#### **Communion Antiphon**
:::

> You have laid down your precepts to be carefully kept;  
> may my ways be firm in keeping your statutes.  
> 
> [Or:]{.red}  
>
> I am the Good Shepherd, says the Lord;  
> I know my sheep, and mine know me.  

:::: {.content-visible when-format="html"}
::: {.red}
### Readings
:::

<details>
  <summary>Click to view the readings for this liturgy.</summary>

::: {.titlered}
### &nbsp; Year A
:::

::: {.red}
#### First Reading [Isaiah 55:6-9]{style="float:right" .small}
:::

Seek the LORD while he may be found,  
call him while he is near.  
Let the scoundrel forsake his way,  
and the wicked his thoughts;  
let him turn to the LORD for mercy;  
to our God, who is generous in forgiving.  
For my thoughts are not your thoughts,  
nor are your ways my ways, says the LORD.  
As high as the heavens are above the earth,  
so high are my ways above your ways  
and my thoughts above your thoughts.  

***

::: {.red}
#### Responsorial Psalm [Psalm 145:2-3, 8-9, 17-18]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord is near to all who call upon him.**  

Every day will I bless you,  
and I will praise your name forever and ever.  
Great is the LORD and highly to be praised;  
his greatness is unsearchable. **[℟.]{.red}**  

The LORD is gracious and merciful,  
slow to anger and of great kindness.  
The LORD is good to all  
and compassionate toward all his works. **[℟.]{.red}**  

The LORD is just in all his ways  
and holy in all his works.  
The LORD is near to all who call upon him,  
to all who call upon him in truth. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [Philippians 1:20c-24, 27a]{style="float:right" .small}
:::

Brothers and sisters:  
Christ will be magnified in my body, whether by life or by death.  
For to me life is Christ, and death is gain.  
If I go on living in the flesh,  
that means fruitful labor for me.  
And I do not know which I shall choose.  
I am caught between the two.  
I long to depart this life and be with Christ,  
for that is far better.  
Yet that I remain in the flesh  
is more necessary for your benefit.  

Only, conduct yourselves in a way worthy of the gospel of Christ.  

***

::: {.red}
#### Gospel Acclamation [Cf. Acts 16:14b]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Open our hearts, O Lord,  
to listen to the words of your Son. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Matthew 20:1-16a]{style="float:right" .small}
:::

Jesus told his disciples this parable:  
"The kingdom of heaven is like a landowner  
who went out at dawn to hire laborers for his vineyard.  
After agreeing with them for the usual daily wage,  
he sent them into his vineyard.  
Going out about nine o'clock,  
the landowner saw others standing idle in the marketplace,  
and he said to them, 'You too go into my vineyard,  
and I will give you what is just.'  
So they went off.  
And he went out again around noon,  
and around three o'clock, and did likewise.  
Going out about five o'clock,  
the landowner found others standing around, and said to them,  
'Why do you stand here idle all day?'  
They answered, 'Because no one has hired us.'  
He said to them, 'You too go into my vineyard.'  
When it was evening the owner of the vineyard said to his foreman,  
'Summon the laborers and give them their pay,  
beginning with the last and ending with the first.'  
When those who had started about five o'clock came,  
each received the usual daily wage.  
So when the first came, they thought that they would receive more,  
but each of them also got the usual wage.  
And on receiving it they grumbled against the landowner, saying,  
'These last ones worked only one hour,  
and you have made them equal to us,  
who bore the day's burden and the heat.'  
He said to one of them in reply,  
'My friend, I am not cheating you.   
Did you not agree with me for the usual daily wage?  
Take what is yours and go.  
What if I wish to give this last one the same as you?  
Or am I not free to do as I wish with my own money?  
Are you envious because I am generous?'  
Thus, the last will be first, and the first will be last."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year B
:::

::: {.red}
#### First Reading [Wisdom 2:12, 17-20]{style="float:right" .small}
:::

The wicked say:  
Let us beset the just one, because he is obnoxious to us;  
he sets himself against our doings,  
reproaches us for transgressions of the law  
and charges us with violations of our training.  
Let us see whether his words be true;  
let us find out what will happen to him.  
For if the just one be the son of God, God will defend him  
and deliver him from the hand of his foes.  
With revilement and torture let us put the just one to the test  
that we may have proof of his gentleness  
and try his patience.  
Let us condemn him to a shameful death;  
for according to his own words, God will take care of him.  

***

::: {.red}
#### Responsorial Psalm [Psalm 54:3-4, 5, 6, 8]{style="float:right" .small}
:::

**[℟.]{.red}** **The Lord upholds my life.**  

O God, by your name save me,  
and by your might defend my cause.  
O God, hear my prayer;  
hearken to the words of my mouth. **[℟.]{.red}**  

For the haughty men have risen up against me,  
the ruthless seek my life;  
they set not God before their eyes. **[℟.]{.red}**  

Behold, God is my helper;  
the Lord sustains my life.  
Freely will I offer you sacrifice;  
I will praise your name, O LORD, for its goodness. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [James 3:16—4:3]{style="float:right" .small}
:::

Beloved:  
Where jealousy and selfish ambition exist,  
there is disorder and every foul practice.  
But the wisdom from above is first of all pure,  
then peaceable, gentle, compliant,  
full of mercy and good fruits,  
without inconstancy or insincerity.  
And the fruit of righteousness is sown in peace  
for those who cultivate peace.  

Where do the wars  
and where do the conflicts among you come from?  
Is it not from your passions  
that make war within your members?  
You covet but do not possess.  
You kill and envy but you cannot obtain;  
you fight and wage war.  
You do not possess because you do not ask.  
You ask but do not receive,  
because you ask wrongly, to spend it on your passions.  

***

::: {.red}
#### Gospel Acclamation [Cf. 2 Thessalonians 2:14]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
God has called us through the Gospel  
to possess the glory of our Lord Jesus Christ. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Mark 9:30-37]{style="float:right" .small}
:::

Jesus and his disciples left from there and began a journey through Galilee,  
but he did not wish anyone to know about it.  
He was teaching his disciples and telling them,  
“The Son of Man is to be handed over to men  
and they will kill him,  
and three days after his death the Son of Man will rise.”  
But they did not understand the saying,  
and they were afraid to question him.  

They came to Capernaum and, once inside the house,  
he began to ask them,  
“What were you arguing about on the way?”  
But they remained silent.  
They had been discussing among themselves on the way  
who was the greatest.  
Then he sat down, called the Twelve, and said to them,  
“If anyone wishes to be first,  
he shall be the last of all and the servant of all.”  
Taking a child, he placed it in their midst,  
and putting his arms around it, he said to them,  
“Whoever receives one child such as this in my name, receives me;  
and whoever receives me,  
receives not me but the One who sent me.”  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

::: {.titlered}
### &nbsp; Year C
:::

::: {.red}
#### First Reading [Amos 8:4-7]{style="float:right" .small}
:::

Hear this, you who trample upon the needy  
and destroy the poor of the land!  
"When will the new moon be over," you ask,  
"that we may sell our grain,  
and the saGath, that we may display the wheat?  
We will diminish the ephah,  
add to the shekel,  
and fix our scales for cheating!  
We will buy the lowly for silver,  
and the poor for a pair of sandals;  
even the refuse of the wheat we will sell!"  
The LORD has sworn by the pride of Jacob:  
Never will I forget a thing they have done!  

***

::: {.red}
#### Responsorial Psalm [Psalm 113:1-2, 4-6, 7-8]{style="float:right" .small}
:::

**[℟.]{.red}** **Praise the Lord who lifts up the poor.**  
[Or:]{.red}  
**[℟.]{.red}** **Alleluia.**  

Praise, you servants of the LORD,
praise the name of the LORD.
Blessed be the name of the LORD
both now and forever. **[℟.]{.red}**  

High above all nations is the LORD;
above the heavens is his glory.
Who is like the LORD, our God, who is enthroned on high
and looks upon the heavens and the earth below? **[℟.]{.red}**  

He raises up the lowly from the dust;  
from the dunghill he lifts up the poor  
to seat them with princes,  
with the princes of his own people. **[℟.]{.red}**  

***

::: {.red}
#### Second Reading [1 Timothy 2:1-8]{style="float:right" .small}
:::

Beloved:  
First of all, I ask that supplications, prayers,  
petitions, and thanksgivings be offered for everyone,  
for kings and for all in authority,  
that we may lead a quiet and tranquil life  
in all devotion and dignity.  
This is good and pleasing to God our savior,  
who wills everyone to be saved. 
and to come to knowledge of the truth.  
For there is one God.  
There is also one mediator between God and men,  
&emsp; the man Christ Jesus,  
who gave himself as ransom for all.  
This was the testimony at the proper time.  
For this I was appointed preacher and apostle. 
— I am speaking the truth, I am not lying —,  
teacher of the Gentiles in faith and truth.  

It is my wish, then, that in every place the men should pray,  
lifting up holy hands, without anger or argument.  

***

::: {.red}
#### Gospel Acclamation [Cf. 2 Corinthians 8:9]{style="float:right" .small}
:::

**[℟.]{.red}** **Alleluia, alleluia.**  
Though our Lord Jesus Christ was rich, he became poor,  
so that by his poverty you might become rich. **[℟.]{.red}**  

***

::: {.red}
#### Gospel [Luke 16:1-13 or 16:10-13]{style="float:right" .small}
:::

Jesus said to his disciples,  
"A rich man had a steward  
who was reported to him for squandering his property.  
He summoned him and said,  
'What is this I hear about you?  
Prepare a full account of your stewardship,  
because you can no longer be my steward.'  
The steward said to himself, 'What shall I do,  
now that my master is taking the position of steward away from me?  
I am not strong enough to dig and I am ashamed to beg.  
I know what I shall do so that,  
when I am removed from the stewardship,  
they may welcome me into their homes.'  
He called in his master's debtors one by one.  
To the first he said,  
'How much do you owe my master?'  
He replied, 'One hundred measures of olive oil.'  
He said to him, 'Here is your promissory note.  
Sit down and quickly write one for fifty.'  
Then to another the steward said, 'And you, how much do you owe?'  
He replied, 'One hundred kors of wheat.'  
The steward said to him, 'Here is your promissory note;  
write one for eighty.'  
And the master commended that dishonest steward for acting prudently.  
"For the children of this world  
are more prudent in dealing with their own generation  
than are the children of light.  
I tell you, make friends for yourselves with dishonest wealth,  
so that when it fails, you will be welcomed into eternal dwellings.  
The person who is trustworthy in very small matters  
is also trustworthy in great ones;  
and the person who is dishonest in very small matters  
is also dishonest in great ones.  
If, therefore, you are not trustworthy with dishonest wealth,  
who will trust you with true wealth?  
If you are not trustworthy with what belongs to another,  
who will give you what is yours?  
No servant can serve two masters.  
He will either hate one and love the other,  
or be devoted to one and despise the other.  
You cannot serve both God and mammon."  

[Or:]{.red}  

Jesus said to his disciples:  
"The person who is trustworthy in very small matters  
is also trustworthy in great ones;  
and the person who is dishonest in very small matters  
is also dishonest in great ones.  
If, therefore, you are not trustworthy with dishonest wealth,  
who will trust you with true wealth?  
If you are not trustworthy with what belongs to another,  
who will give you what is yours?  
No servant can serve two masters.  
He will either hate one and love the other,  
or be devoted to one and despise the other.  
You cannot serve both God and mammon."  

::: {.centered}
{{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}} &nbsp; {{< var symbols.cross >}}
:::

</details>
::::

::: {.red}
## Music Selections
:::

::: {.titlered}
### &nbsp; Year A
:::
{{< var text.yeara >}}

```{python}
#| label: Year A
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['a'], urls=videos)
```

::: {.titlered}
### &nbsp; Year B
:::
{{< var text.yearb >}}

```{python}
#| label: Year B
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['b'], urls=videos)
```

::: {.titlered}
### &nbsp; Year C
:::
{{< var text.yearc >}}

```{python}
#| label: Year C
#| echo: false
#| output: asis
utils.hymnlist(params['hymns']['c'], urls=videos)
```


```{python}
#| label: Anthems
#| echo: false
#| output: asis
utils.anthemlist(hymns=params['hymns'], urls=videos)
```
